import { b, type Bilingual } from "./types";

export type GlossaryEntry = {
  id: string;
  term: Bilingual;
  definition: Bilingual;
  engineerView: Bilingual;
  notation?: string;
};

const g = (
  id: string,
  ko: string,
  en: string,
  definitionKo: string,
  definitionEn: string,
  engineerKo: string,
  engineerEn: string,
  notation?: string,
): GlossaryEntry => ({
  id,
  term: b(ko, en),
  definition: b(definitionKo, definitionEn),
  engineerView: b(engineerKo, engineerEn),
  notation,
});

/**
 * Reader-facing definitions, ordered by the point at which each chapter needs
 * them. Hardware comparisons are deliberately approximate: they build an
 * initial mental model, while the definition remains the source of truth.
 */
export const chapterGlossaries: Record<string, GlossaryEntry[]> = {
  "predicate-logic": [
    g(
      "predicate-logic", "술어 논리", "predicate logic",
      "대상의 값과 관계를 변수, 논리 연산자, 그리고 ‘모든’·‘어떤’ 같은 수량자로 표현하는 논리 체계다. 명제가 한 비트의 참·거짓이라면, predicate는 입력값에 따라 참·거짓이 달라지는 조건이다.",
      "A logic for expressing values and relationships with variables, logical connectives, and quantifiers such as “for every” and “there exists.” If a proposition is one true/false bit, a predicate is a condition whose bit depends on its inputs.",
      "SystemVerilog assertion에서 `req |-> ack`가 신호에 대한 조건을 쓰듯, `x < y`는 x와 y가 정해질 때 판정되는 조건이다. `∀x`는 가능한 모든 x를 검사한다는 수학적 표현이다.",
      "Like a SystemVerilog assertion such as `req |-> ack`, `x < y` states a condition on signals or values. The quantifier `∀x` says the condition must pass for every possible x.",
      "∀x. P(x)    ∃x. P(x)",
    ),
    g(
      "syntax", "syntax", "syntax",
      "어떤 표현이 언어의 올바른 모양인지 정하는 규칙이다. 아직 그 표현이 무엇을 계산하는지는 말하지 않는다.",
      "The rules that determine which expressions are well-formed in a language. Syntax alone does not say what those expressions compute.",
      "HDL 문법이 `always_ff` 블록의 허용 형태를 정하지만 실제 회로 동작은 별도로 정의되는 것과 같다. 파서가 받아들인다는 사실과 설계가 원하는 동작을 한다는 사실은 다르다.",
      "An HDL grammar determines the legal shape of an `always_ff` block, while circuit behavior is defined separately. Being accepted by a parser is not the same as behaving as intended.",
    ),
    g(
      "semantics", "semantics", "semantics",
      "올바른 syntax에 정확한 의미를 부여하는 규칙 또는 수학적 함수다. 프로그램이 어떤 결과, 상태 변화, 또는 관찰 가능한 동작을 만드는지 설명한다.",
      "Rules or mathematical functions that assign precise meanings to well-formed syntax. They explain the result, state change, or observable behavior produced by a program.",
      "RTL 텍스트가 주어졌을 때 시뮬레이터가 시간에 따른 신호 값을 정하는 규칙에 가깝다. 같은 syntax라도 선택한 semantics이 다르면 초기화나 동시 실행을 다르게 해석할 수 있다.",
      "Think of the rules a simulator uses to turn RTL into signal values over time. The same-looking syntax can behave differently under different semantic rules for initialization or concurrency.",
      "⟦syntax⟧ = meaning",
    ),
    g(
      "state", "상태", "state",
      "특정 순간에 각 변수에 저장된 값을 한꺼번에 나타낸 지도다. 식의 의미는 대개 상태를 입력받아 값을 내놓는 함수로 정의된다.",
      "A map containing the value stored in every variable at one instant. The meaning of an expression is often defined as a function from a state to a value.",
      "한 클록 경계에서 레지스터 파일 전체를 찍은 스냅샷을 떠올리면 된다. `σ(x)=3`은 상태 σ에서 변수 x의 값이 3이라는 뜻이다.",
      "Picture a snapshot of the complete register file at a clock boundary. `σ(x)=3` says that variable x contains 3 in state σ.",
      "σ : Variable → Value",
    ),
    g(
      "assertion", "assertion", "assertion",
      "상태가 만족해야 하는 참·거짓 조건이다. 프로그램 명령이 아니라 프로그램이나 상태에 관해 우리가 확인하려는 주장이다.",
      "A true-or-false condition that a state may satisfy. It is a claim about a program or state, not a command executed by the program.",
      "`fifo_count <= DEPTH` 같은 설계 속성에 해당한다. assertion 자체가 FIFO를 제어하지는 않지만, 현재 상태가 안전 조건을 지키는지 판정한다.",
      "It corresponds to a design property such as `fifo_count <= DEPTH`. The assertion does not control the FIFO; it checks whether the current state obeys a safety condition.",
    ),
    g(
      "abstract-syntax", "abstract syntax", "abstract syntax",
      "괄호, 공백, 우선순위처럼 표기에만 필요한 부분을 버리고 표현의 실제 트리 구조만 남긴 것이다.",
      "The tree structure of an expression after discarding notational details such as parentheses, whitespace, and precedence conventions.",
      "회로도에서 선의 색이나 블록 배치를 지우고 인스턴스와 연결 관계만 남긴 netlist와 비슷하다. `x+y*z`는 Add(x, Mul(y,z))라는 구조로 보존된다.",
      "It resembles a netlist that keeps instances and connectivity while discarding drawing layout and wire colors. `x+y*z` becomes the structure Add(x, Mul(y,z)).",
    ),
    g(
      "constructor", "constructor", "constructor",
      "abstract syntax 트리에서 한 종류의 노드를 만드는 기본 형식이다. 상수, 덧셈, 수량자 등이 각각 constructor가 된다.",
      "A basic form that creates one kind of node in an abstract syntax tree. Constants, addition, and quantification are examples of constructors.",
      "netlist의 AND 게이트나 플립플롭 셀 종류처럼, constructor는 노드가 무엇이며 몇 개의 하위 부품을 받는지 정한다. Add는 두 하위 식을 받는다.",
      "Like AND-gate or flip-flop cell kinds in a netlist, a constructor determines what a node is and how many children it takes. Add takes two subexpressions.",
    ),
    g(
      "compositionality", "합성성", "compositionality",
      "전체 표현의 의미가 바로 아래 부분 표현들의 의미와 현재 constructor만으로 결정되는 성질이다.",
      "The property that the meaning of a whole expression is determined solely by its constructor and the meanings of its immediate parts.",
      "계층형 하드웨어 검증에서 각 IP 블록의 계약과 연결만으로 상위 모듈 동작을 설명하는 방식과 닮았다. 내부 소스 문자열을 다시 들여다볼 필요가 없어야 한다.",
      "It resembles hierarchical hardware verification: explain a top module from each IP block’s contract and the wiring between them, without reopening their source text.",
    ),
    g(
      "validity", "타당성", "validity",
      "assertion이 특정 상태 하나가 아니라 고려하는 모든 상태에서 참인 성질이다. ‘증명 규칙으로 증명했다’는 유도 가능성과는 별개의 semantic 개념이다.",
      "The property that an assertion is true in every state under consideration, not merely one state. It is a semantic notion distinct from derivability by proof rules.",
      "테스트 벡터 몇 개가 통과한 것이 아니라 모든 합법적인 입력과 상태에서 속성이 성립한다는 요구와 같다. 형식 검증은 이 전칭 요구를 다룬다.",
      "It is the demand that a property hold for all legal inputs and states, rather than just passing a few test vectors. Formal verification targets this universal claim.",
      "⊨ P",
    ),
    g(
      "structural-induction", "구조적 귀납법", "structural induction",
      "숫자의 크기가 아니라 syntax 트리가 만들어지는 방식에 따라 성질을 증명한다. 각 기본 constructor와 각 재귀 constructor를 처리하면 모든 유한 트리를 다룬다.",
      "A proof method that follows how syntax trees are built rather than the size of a number. Cover every base constructor and every recursive constructor to cover all finite trees.",
      "모든 계층형 설계에 대한 속성을 보이기 위해 leaf 셀을 확인하고, 속성을 만족하는 하위 모듈을 조합한 상위 모듈도 만족함을 확인하는 패턴과 같다.",
      "It is like proving a property for every hierarchical design by checking leaf cells and then checking that each composition preserves the property when its submodules have it.",
    ),
    g(
      "capture-avoiding-substitution", "캡처 회피 치환", "capture-avoiding substitution",
      "자유 변수를 다른 식으로 바꿀 때 새 식의 자유 이름이 주변 바인더에 우연히 묶이지 않도록 먼저 충돌하는 이름을 바꾸는 치환이다.",
      "Substitution that first renames conflicting binders so that free names in the inserted expression do not accidentally become bound.",
      "계층을 평탄화할 때 서로 다른 모듈의 내부 신호 이름이 충돌하지 않도록 신호를 고유하게 바꾸는 것과 비슷하다. 텍스트만 복사하면 연결 대상이 달라질 수 있다.",
      "It resembles uniquely renaming internal signals while flattening hierarchy so names from different modules do not collide. Blind textual copying can silently change connectivity.",
    ),
  ],

  "simple-imperative-language": [
    g(
      "domain", "domain", "domain",
      "domain (정보 순서 구조)은 계산 결과의 정보량을 순서로 나타내고 점점 더 정확해지는 approximation의 limit를 담는다. bottom element `⊥`는 아직 결과가 없거나 computation이 nonterminate함을 나타낸다.",
      "A mathematical space that orders computation results by information content and contains limits of increasingly precise approximations. Its bottom element ⊥ represents no result yet, including nontermination.",
      "4상태 논리에서 X가 구체적인 0이나 1보다 information이 적다고 보는 관점이 출발점에 가깝다. 단, domain은 단순 signal value를 넘어 program result의 approximation도 다룬다.",
      "The starting intuition resembles treating X as less informative than a concrete 0 or 1 in four-state logic. Domains extend that idea to approximations of whole computations.",
      "⊥ ⊑ d",
    ),
    g(
      "continuous-function", "continuous function", "continuous function",
      "continuous function (연속 함수)은 information이 증가하는 chain의 least upper bound (lub)를 보존한다. finite input information에서 갑자기 infinite evidence를 요구하지 않는다는 뜻이다.",
      "A function that preserves least upper bounds of increasing chains of information. Intuitively, it cannot demand infinitely much new information all at once from finite input evidence.",
      "반복 시뮬레이션에서 입력 근사를 조금씩 정교하게 할 때 출력 근사도 일관되게 정교해지고, 그 극한이 완전한 입력의 출력과 맞는 상황을 떠올리면 된다.",
      "Imagine iterative simulation where refining the input approximation consistently refines the output, and the limit agrees with the output for the fully known input.",
    ),
    g(
      "least-fixed-point", "least fixed point", "least fixed point",
      "least fixed point (최소 고정점)는 `F(x)=x`를 만족하는 solution 가운데 information order상 가장 작다. recursion이나 `while`의 finite unfolding이 정당화하는 behavior만 포함한다.",
      "The least solution, in the information order, of `F(x)=x`. For recursion or while loops, it includes only behavior justified by some finite unfolding.",
      "피드백 회로의 값을 미지 상태에서 시작해 전달 규칙을 반복 적용하여 안정점에 도달시키는 해석과 닮았다. ‘최소’는 근거 없는 추가 동작을 넣지 않는다.",
      "It resembles starting a feedback network from an unknown state and repeatedly applying propagation rules until a stable solution is reached. “Least” excludes unsupported extra behavior.",
      "fix(F) = ⨆ₙ Fⁿ(⊥)",
    ),
    g(
      "syntactic-sugar", "syntactic sugar", "syntactic sugar",
      "syntactic sugar는 core language의 기존 construct로 meaning-preserving translation할 수 있는 convenience notation이다. 쓰기 편해지지만 원칙적으로 새 computational power를 추가하지 않는다.",
      "Convenient notation that can be translated meaning-preservingly into existing core-language constructs. It improves usability without necessarily adding computational power.",
      "HDL의 generate construct나 repetition macro가 elaboration 뒤 더 basic한 instance set으로 바뀌는 것과 같다. translated form이 original intent를 preserve해야 한다.",
      "It is like an HDL generate construct or repetition macro elaborating into a more basic set of instances. The elaborated form must preserve the intended behavior.",
    ),
    g(
      "full-abstraction", "full abstraction", "full abstraction",
      "full abstraction (완전 추상성)은 semantic equality와 어떤 program context도 둘을 구별하지 못하는 contextual equivalence가 정확히 일치하는 성질이다.",
      "The property that semantic equality coincides exactly with indistinguishability by every program context.",
      "두 IP가 모든 허용 testbench에서 같은 핀 동작을 보일 때에만 모델도 둘을 같다고 보는 이상적인 대응이다. 모델이 testbench가 볼 수 없는 내부 차이를 구별하면 너무 세밀하다.",
      "Ideally, a model equates two IP blocks exactly when every permitted testbench sees the same pin behavior. A model that distinguishes invisible internal details is too fine-grained.",
    ),
  ],

  "program-specifications": [
    g(
      "hoare-triple", "Hoare 삼중항", "Hoare triple",
      "`{p} c {q}` 형태로, 전제조건 p를 만족하는 상태에서 명령 c를 실행해 종료하면 사후조건 q가 성립한다는 명세다.",
      "A specification `{p} c {q}` saying that if command c starts in a state satisfying precondition p and terminates, its final state satisfies postcondition q.",
      "IP 블록의 입력 가정, 동작, 출력 보장을 세 칸으로 나눈 계약과 비슷하다. 기본 형태는 종료 자체까지 보장하지 않는다는 점이 중요하다.",
      "It resembles an assume–operation–guarantee contract for an IP block. Importantly, the basic form does not by itself guarantee termination.",
      "{p} c {q}",
    ),
    g(
      "loop-invariant", "루프 불변식", "loop invariant",
      "루프에 들어가기 전 참이고, 본문을 한 번 실행해도 보존되며, 루프 종료 시 원하는 결과를 끌어내는 assertion이다.",
      "An assertion that is true before entering a loop, preserved by one body iteration, and strong enough to imply the desired result when the loop exits.",
      "순차 회로에서 매 클록 유지되는 프로토콜 속성과 같다. 초기화에서 성립하고 한 사이클 전이가 보존하면 모든 도달 가능한 사이클에서 성립한다.",
      "It is like a protocol property maintained on every clock: establish it at reset and prove one transition preserves it, then it holds for every reachable cycle.",
    ),
    g(
      "variant-function", "변량 함수", "variant function",
      "루프가 반복될 때마다 엄격히 감소하고 0 아래로 내려갈 수 없는 자연수 값이다. 무한 반복이 불가능함을 증명하는 데 쓴다.",
      "A natural-number measure that strictly decreases on every loop iteration and cannot fall below zero. It is used to prove that infinite iteration is impossible.",
      "카운터가 매 사이클 1씩 줄어 0에서 완료되는 FSM의 remaining-count와 같다. 불변식은 안전을, 변량은 결국 끝난다는 진행을 설명한다.",
      "It is the remaining-count of an FSM that decrements every cycle and completes at zero. An invariant explains safety; a variant explains eventual completion.",
    ),
    g(
      "rule-of-consequence", "결과 규칙", "rule of consequence",
      "이미 증명한 Hoare 삼중항의 전제조건을 더 강하게 하거나 사후조건을 더 약하게 하여 다른 유효한 명세를 얻는 규칙이다.",
      "A rule that derives another valid Hoare triple by strengthening the precondition or weakening the postcondition of one already proved.",
      "블록이 1.0V±10% 입력에서 동작하면 더 좁은 1.0V±5% 조건에서도 동작하고, 2ns 이내 응답을 보장하면 3ns 이내라는 약한 보장도 만족하는 것과 같다.",
      "If a block works for 1.0V±10%, it also works under the stronger 1.0V±5% assumption; if it guarantees 2 ns, it also meets the weaker 3 ns guarantee.",
    ),
    g(
      "soundness", "건전성", "soundness",
      "증명 규칙으로 유도할 수 있는 모든 결론이 실제 semantics에서도 참이라는 성질이다. 잘못된 프로그램을 규칙만으로 ‘증명’하지 못하게 한다.",
      "The property that every conclusion derivable by the proof rules is also true in the semantics. It prevents the rules from proving incorrect programs correct.",
      "형식 검증 도구가 PASS를 냈다면 실제 수학적 모델에서도 속성이 성립해야 한다는 신뢰 조건이다. 건전성은 도구가 모든 참을 찾는다는 완전성과 다르다.",
      "It is the trust condition that a PASS from a formal method must imply the property really holds in the mathematical model. Soundness differs from finding every truth.",
    ),
  ],

  "arrays": [
    g(
      "functional-update", "함수 갱신", "functional update",
      "기존 배열을 직접 바꾸는 대신 한 인덱스에서만 새 값을 돌려주고 나머지에서는 기존 값과 같은 새 함수를 만드는 관점이다.",
      "A view of array update that creates a new function returning the new value at one index and the old values everywhere else, rather than mutating the old array in place.",
      "레지스터 파일의 next-state 함수를 생각하면 된다. write address와 일치하는 엔트리만 새 data를 받고 나머지 엔트리는 이전 값을 유지한다.",
      "Think of a register file’s next-state function: only the entry matching the write address receives new data; every other entry retains its previous value.",
      "a[i ↦ v](j) = if i=j then v else a(j)",
    ),
    g(
      "function-domain", "정의역", "domain",
      "함수가 입력으로 받을 수 있도록 정의된 값들의 집합이다. 배열을 함수로 보면 유효한 인덱스 집합이 정의역이 된다.",
      "The set of inputs on which a function is defined. When an array is viewed as a function, its valid index set is the domain.",
      "깊이 16인 메모리의 유효 주소가 0부터 15까지인 것과 같다. ‘도메인 이론’의 도메인과 같은 영어 단어지만 여기서는 단순히 입력 범위를 뜻한다.",
      "It is the valid address set 0 through 15 for a depth-16 memory. This use of “domain” means input set, not the domain-theory structure from Chapter 2.",
    ),
    g(
      "bounds-error", "범위 오류", "bounds error",
      "배열의 정의역 밖 인덱스로 읽거나 쓰려고 할 때 생기는 오류다. semantics은 이를 실패, 중단, 또는 미정의 동작 중 하나로 명시해야 한다.",
      "An error caused by reading or writing an index outside an array’s domain. A semantics must say whether this means failure, abort, or undefined behavior.",
      "실제 SRAM에 없는 주소를 내거나 버스 address decoder의 빈 구간을 접근하는 상황과 비슷하다. 모델이 어떤 응답을 내는지 정하지 않으면 검증 결과도 모호해진다.",
      "It resembles addressing beyond a physical SRAM or hitting an unmapped bus region. Verification becomes ambiguous unless the model specifies the response.",
    ),
    g(
      "binary-search", "이진 탐색", "binary search",
      "정렬된 배열에서 중간 원소와 비교해 후보 구간을 매 단계 절반으로 줄이는 탐색 알고리즘이다.",
      "A search algorithm for sorted arrays that compares the middle element and halves the candidate interval at every step.",
      "successive-approximation ADC가 비교 결과로 탐색 범위를 절반씩 줄이는 과정과 닮았다. 정확성 증명에서는 목표가 아직 남아 있는 구간을 불변식으로 둔다.",
      "It resembles a successive-approximation ADC narrowing its search range by half after each comparison. A proof keeps “the target is still inside this interval” as an invariant.",
    ),
    g(
      "higher-order-assertion", "higher-order assertion", "higher-order assertion",
      "값뿐 아니라 함수나 predicate 자체를 변수로 받아 그 성질을 표현하는 assertion이다.",
      "An assertion that can quantify over or otherwise describe functions and predicates themselves, not only ordinary data values.",
      "특정 메모리 내용 하나가 아니라 ‘어떤 주소 변환 함수가 주어져도 이 인터페이스 법칙을 만족한다’고 쓰는 상위 수준 검증 계약에 가깝다.",
      "It is like a higher-level verification contract saying “for any address-mapping function, this interface law holds,” rather than checking one concrete memory image.",
    ),
  ],

  "failure-io-continuations": [
    g(
      "sequence-domain", "시퀀스 도메인", "sequence domain",
      "유한 또는 무한한 관찰 순서를 원소로 삼고, 짧은 prefix가 긴 실행의 근사가 되도록 순서를 둔 도메인이다.",
      "A domain whose elements are finite or infinite observation sequences, ordered so that a shorter prefix approximates a longer execution.",
      "logic analyzer trace를 앞의 10사이클, 100사이클, 계속된 전체 trace 순으로 점점 더 많이 아는 것으로 보는 방식이다. 비종료 실행도 무한 trace로 표현할 수 있다.",
      "Think of knowing a logic-analyzer trace for 10 cycles, then 100 cycles, then the entire ongoing trace. An infinite trace can represent a nonterminating interaction.",
    ),
    g(
      "recursive-domain-isomorphism", "재귀 도메인 동형", "recursive domain isomorphism",
      "정의하려는 의미 공간이 자기 자신을 포함하는 방정식의 해라는 뜻이다. 펼쳤다가 다시 접을 수 있는 구조적 대응으로 재귀 데이터를 엄밀히 만든다.",
      "A meaning space defined as a solution to an equation that contains the space itself. A structural correspondence for unfolding and folding makes recursive data precise.",
      "linked-list 노드 타입이 payload와 다음 노드 포인터를 포함하는 것과 비슷하다. 여기서는 단순 주소 대신 수학적 공간 자체가 재귀 방정식을 만족한다.",
      "It resembles a linked-list node type containing a payload and a pointer to another node. Here, the mathematical space itself satisfies a recursive equation.",
      "D ≅ F(D)",
    ),
    g(
      "resumption", "재개", "resumption",
      "입출력 하나를 내보낸 뒤 환경의 응답에 따라 계산을 이어 가는 나머지 동작을 담은 재귀적 의미 구조다.",
      "A recursive semantic structure that emits one interaction and contains the remaining computation to resume after the environment responds.",
      "버스 요청을 낸 뒤 응답 데이터에 따라 다음 상태로 이동하는 정지된 FSM 상태와 닮았다. 단순 결과가 아니라 상호작용 후 계속할 방법까지 보존한다.",
      "It resembles a paused FSM after issuing a bus request, with the next state determined by response data. It stores how to continue, not just a final result.",
    ),
    g(
      "continuation", "계속", "continuation",
      "현재 계산이 값을 만든 뒤 수행할 나머지 계산을 함수나 데이터로 나타낸 것이다.",
      "A representation, as a function or data structure, of the rest of the computation to perform after the current computation produces a value.",
      "파이프라인 단계가 결과와 함께 다음 단계의 destination과 제어 정보를 넘기거나, CPU가 return address를 보관하는 것과 비슷하다.",
      "It resembles a pipeline stage forwarding destination/control metadata with its result, or a CPU saving a return address that says where execution continues.",
      "k : Result → Answer",
    ),
    g(
      "cps", "CPS", "continuation-passing style",
      "함수가 결과를 직접 반환하지 않고, 그 결과를 받을 계속 함수를 명시적 인수로 받아 호출하는 프로그램 형태다.",
      "A program form in which a function does not return directly; instead it receives an explicit continuation function and calls it with the result.",
      "모듈이 출력값만 반환하는 대신 `done` 핸드셰이크와 다음 처리 블록을 명시적으로 구동하도록 인터페이스를 바꾼 것과 닮았다. 제어 흐름이 데이터 경로처럼 드러난다.",
      "It resembles changing a module interface so that it explicitly drives a `done` handshake and the next processing stage instead of merely returning a value. Control flow becomes explicit like a datapath.",
    ),
  ],

  "transition-semantics": [
    g(
      "configuration", "구성", "configuration",
      "실행의 한 순간을 완전히 설명하는 정보 묶음이다. 보통 남은 프로그램, 현재 상태, 저장소처럼 다음 단계를 결정하는 모든 요소를 담는다.",
      "A bundle containing everything needed to describe one instant of execution and determine its next step, such as the remaining program, state, and store.",
      "프로세서의 PC, 레지스터, 메모리, pipeline 상태를 함께 찍은 microarchitectural snapshot과 같다. 이 중 하나라도 빠지면 다음 사이클을 결정하지 못할 수 있다.",
      "It is like a microarchitectural snapshot containing the PC, registers, memory, and pipeline state. Omitting any required component may make the next cycle impossible to determine.",
      "⟨command, state⟩",
    ),
    g(
      "small-step-semantics", "small-step semantics", "small-step semantics",
      "프로그램 실행을 한 번에 최종 결과로 보내지 않고, 원자적인 한 단계 전이들의 연속으로 정의하는 방식이다.",
      "A style of semantics that defines execution as a sequence of atomic transitions rather than mapping a whole program directly to its final result.",
      "RTL 시뮬레이션을 한 클록 또는 한 delta-cycle씩 진행하며 각 중간 상태를 보는 것과 가깝다. 동시성이나 비종료처럼 중간 동작이 중요한 경우에 유용하다.",
      "It is close to advancing an RTL simulation one clock or delta cycle at a time and observing each intermediate state. This is useful when concurrency or divergence makes intermediate behavior important.",
      "C → C′",
    ),
    g(
      "transition-closure", "전이 폐쇄", "transition closure",
      "한 단계 전이 관계를 0회 이상 또는 1회 이상 이어 붙여 여러 단계 실행 관계를 만드는 연산이다.",
      "The operation that chains a one-step transition relation zero or more times, or one or more times, to obtain multi-step execution.",
      "한 사이클 next-state 관계에서 임의 개수의 사이클 뒤 도달 가능한 상태를 계산하는 것과 같다. 별표 `→*`는 아무 일도 하지 않은 0단계도 포함한다.",
      "It is like deriving all states reachable after any number of cycles from a one-cycle next-state relation. The star in `→*` includes the zero-step case.",
      "→*  = zero or more steps",
    ),
    g(
      "determinacy", "결정성", "determinacy",
      "같은 구성에서 가능한 다음 구성 또는 최종 관찰이 하나로 정해지는 성질이다.",
      "The property that a given configuration determines a unique next configuration or a unique final observation.",
      "동일한 현재 레지스터와 입력이 주어졌을 때 next-state logic이 하나의 다음 값을 내는 정상적인 동기 회로와 같다. 중재 선택이 명시되지 않으면 결정성이 깨질 수 있다.",
      "It matches ordinary synchronous next-state logic producing one next value from the same registers and inputs. An unspecified arbitration choice can break determinacy.",
    ),
    g(
      "labeled-transition", "라벨 전이", "labeled transition",
      "상태 사이의 전이에 입력, 출력, 통신 같은 관찰 가능한 사건 이름을 붙인 관계다.",
      "A transition relation whose edges carry labels for observable events such as inputs, outputs, or communications.",
      "FSM 다이어그램의 edge에 `req/ack` 같은 조건과 동작을 적는 것과 같다. 상태뿐 아니라 어떤 외부 사건으로 이동했는지를 trace에 남긴다.",
      "It is like labeling FSM edges with conditions and actions such as `req/ack`. A trace records not only states but the external events that caused transitions.",
      "C —event→ C′",
    ),
  ],

  "nondeterminism": [
    g(
      "guarded-command", "보호 명령", "guarded command",
      "Boolean 조건인 guard와, 그 조건이 참일 때 실행할 명령을 한 쌍으로 묶은 구성이다. 여러 guard가 참이면 그중 하나를 선택할 수 있다.",
      "A construct pairing a Boolean guard with a command enabled when that guard is true. If several guards are true, one of their commands may be selected.",
      "여러 request의 enable 조건과 처리 동작을 나열한 arbiter 규칙과 비슷하다. 둘 이상이 동시에 enable일 때 우선순위를 정하지 않으면 선택은 비결정적이다.",
      "It resembles listing enable conditions and actions for an arbiter. If multiple requests are enabled and no priority is specified, the choice is nondeterministic.",
      "g₁ → c₁ ▯ g₂ → c₂",
    ),
    g(
      "nondeterminism", "비결정성", "nondeterminism",
      "같은 시작 상태에서 언어 규칙이 둘 이상의 실행 결과나 다음 단계를 허용하지만 어느 것을 택할지 지정하지 않는 성질이다.",
      "The property that language rules permit more than one next step or result from the same starting state without specifying which one is chosen.",
      "동시에 들어온 request 중 어느 쪽을 먼저 서비스할지 명시하지 않은 arbiter 모델과 같다. 확률적 선택과 달리 각 경우의 확률을 말하지 않는다.",
      "It is like an arbiter model that leaves unspecified which simultaneous request is served first. Unlike randomness, nondeterminism assigns no probability to the choices.",
    ),
    g(
      "powerdomain", "파워도메인", "powerdomain",
      "비결정적 계산이 만들 수 있는 결과 집합을 도메인 이론의 정보 순서와 함께 다루도록 만든 의미 공간이다.",
      "A semantic domain designed to represent sets of possible outcomes of a nondeterministic computation while retaining an information ordering.",
      "한 입력에 대해 허용되는 모든 output trace를 모은 verification envelope와 비슷하다. 단순 집합만으로는 비종료와 근사 정보를 충분히 구분하지 못해 별도 구조가 필요하다.",
      "It resembles a verification envelope containing every permitted output trace for one input. Extra structure is needed because a plain set does not adequately represent divergence and approximation.",
    ),
    g(
      "nondeterministic-deadlock", "교착", "deadlock",
      "실행이 끝난 것은 아닌데 현재 참인 guard나 가능한 전이가 하나도 없어 더 진행할 수 없는 상태다.",
      "A non-final state in which no guard is enabled and no transition can proceed.",
      "FSM이 합법적인 done 상태가 아닌데 어떤 transition condition도 참이 아니어서 멈춘 경우와 같다. 무한히 움직이는 livelock과는 다르다.",
      "It is like an FSM stuck outside a legal done state because no transition condition is true. This differs from livelock, which keeps moving without useful progress.",
    ),
    g(
      "weakest-precondition", "최약 전제조건", "weakest precondition",
      "명령을 실행한 뒤 목표 사후조건이 반드시 성립하도록 보장하는 시작 조건 중 가장 약한, 즉 가장 많은 상태를 허용하는 조건이다.",
      "The least restrictive starting condition that guarantees a target postcondition after executing a command.",
      "출력 timing·protocol 요구에서 출발해 입력과 초기 상태가 만족해야 할 최소 제약을 combinational cone을 거슬러 계산하는 것과 비슷하다.",
      "It resembles propagating an output timing or protocol requirement backward through a combinational cone to derive the minimum constraints on inputs and initial state.",
      "wp(c, q)",
    ),
  ],

  "shared-variable-concurrency": [
    g(
      "interleaving", "인터리빙", "interleaving",
      "여러 실행 주체의 원자 단계를 각각의 내부 순서는 유지한 채 하나의 전체 순서로 섞어 동시 실행을 모델링하는 방식이다.",
      "A model of concurrency that mixes atomic steps from several participants into one total order while preserving each participant’s internal order.",
      "두 bus master의 transaction이 시간축에서 번갈아 나타나는 모든 합법적 schedule을 열거하는 것과 같다. 실제 병렬 동작을 가능한 직렬 순서들의 집합으로 본다.",
      "It is like enumerating every legal schedule in which transactions from two bus masters alternate on a timeline. Real parallel activity is represented by a set of possible serial orders.",
    ),
    g(
      "critical-region", "임계 구역", "critical region",
      "공유 자원의 일관성을 지키기 위해 다른 경쟁 실행과 섞이지 않고 원자적으로 수행되어야 하는 코드 구간이다.",
      "A section of code that must execute atomically, without interleaving with competitors, to preserve a shared resource’s consistency.",
      "공유 control register의 read-modify-write가 다른 master의 접근 사이에 끼어들지 못하도록 bus lock을 거는 구간과 같다.",
      "It is like locking a bus around a shared control-register read–modify–write so another master cannot intervene between the read and write.",
    ),
    g(
      "mutual-exclusion", "상호 배제", "mutual exclusion",
      "한 시점에 최대 하나의 실행 주체만 특정 임계 구역에 들어갈 수 있다는 안전 성질이다.",
      "A safety property stating that at most one participant can occupy a particular critical region at any time.",
      "one-hot grant가 보장되어 두 master가 동시에 단일-port SRAM을 구동하지 않는 조건이다. 누군가 언젠가 grant를 받는다는 공정성과는 별개다.",
      "It is the one-hot-grant condition preventing two masters from driving a single-port SRAM simultaneously. It is separate from fairness, which concerns eventual service.",
    ),
    g(
      "concurrency-deadlock", "교착", "deadlock",
      "둘 이상의 실행 주체가 서로가 가진 자원이나 사건을 기다려 어느 쪽도 다음 단계로 갈 수 없는 상태다.",
      "A state where two or more participants wait on resources or events held by one another, so none can take a next step.",
      "master A가 lock X를 잡고 Y를 기다리며, master B가 Y를 잡고 X를 기다리는 순환 대기와 같다. 단순히 오래 걸리는 상태와 구분해야 한다.",
      "It is the circular wait where master A holds lock X and waits for Y while master B holds Y and waits for X. This differs from a merely slow state.",
    ),
    g(
      "fairness", "공정성", "fairness",
      "계속 실행 가능하거나 반복해서 요청하는 참여자가 scheduler에 의해 영원히 무시되지 않는다는 실행 가정이다.",
      "An assumption that a participant which remains enabled, or requests repeatedly, is not ignored forever by the scheduler.",
      "round-robin arbiter가 지속되는 request에 결국 grant를 준다는 보장과 같다. mutual exclusion은 동시에 둘을 허용하지 않는 안전이고, 공정성은 starvation을 막는 진행 조건이다.",
      "It is the guarantee that a round-robin arbiter eventually grants a persistent request. Mutual exclusion is safety; fairness is the progress condition that prevents starvation.",
    ),
    g(
      "stuttering-mumbling", "말더듬/뭉개기", "stuttering/mumbling",
      "말더듬은 관찰상 변화 없는 단계를 trace에 추가하는 것이고, 뭉개기는 여러 내부 단계를 하나의 큰 단계로 합치는 것이다.",
      "Stuttering inserts steps with no observable change into a trace; mumbling combines several internal steps into one larger step.",
      "waveform에 idle cycle을 더 넣어도 protocol 의미가 같다고 보거나, 여러 micro-operation을 하나의 architectural transaction으로 묶어 보는 추상화와 같다.",
      "It resembles treating extra idle cycles as protocol-equivalent, or abstracting several micro-operations into one architectural transaction.",
    ),
  ],

  "communicating-sequential-processes": [
    g(
      "csp", "CSP", "communicating sequential processes",
      "독립적인 순차 process들이 공유 변수 대신 이름 붙은 통신 사건으로 상호작용하도록 모델링하는 동시성 체계다.",
      "A concurrency model in which independent sequential processes interact through named communication events instead of shared variables.",
      "각 IP가 내부 상태를 숨기고 channel handshake만으로 연결되는 SoC 모델과 가깝다. 시스템 동작은 각 process의 순서와 통신 동기화로 정해진다.",
      "It is close to an SoC model where each IP hides its internal state and connects only through channel handshakes. Behavior follows process order plus communication synchronization.",
    ),
    g(
      "rendezvous", "랑데부", "rendezvous",
      "보내는 process와 받는 process가 모두 준비된 바로 그때 하나의 통신 사건이 발생하는 동기화다.",
      "A synchronization in which one communication event occurs exactly when both the sending and receiving processes are ready.",
      "buffer가 없는 ready/valid 연결에서 valid와 ready가 동시에 참인 사이클에만 transfer가 일어나는 것과 같다.",
      "It is like an unbuffered ready/valid link where a transfer occurs only on a cycle in which both valid and ready are asserted.",
    ),
    g(
      "channel", "채널", "channel",
      "process 사이의 통신 사건을 식별하고 전달 방향과 값의 종류를 정하는 이름 붙은 연결이다.",
      "A named connection that identifies communication events between processes and determines direction and the kind of values transferred.",
      "module port나 on-chip link의 논리적 이름과 비슷하다. 채널은 공유 메모리 위치가 아니라 두 process가 동기화하는 경계다.",
      "It resembles the logical name of a module port or on-chip link. A channel is a synchronization boundary between processes, not a shared memory location.",
    ),
    g(
      "synchronous-communication", "동기식 통신", "synchronous communication",
      "송신과 수신이 같은 사건으로 함께 일어나며, 상대가 준비되지 않으면 준비된 쪽도 기다리는 통신 방식이다.",
      "Communication where send and receive occur together as one event, and a ready participant waits if its counterpart is not ready.",
      "중간 FIFO 없이 직접 연결된 blocking handshake와 같다. asynchronous FIFO에 값을 넣고 송신자가 먼저 진행하는 buffered 통신과 대비된다.",
      "It is like a blocking handshake with no intermediate FIFO. This contrasts with buffered communication, where a sender can enqueue data and proceed first.",
    ),
    g(
      "communication-deadlock", "통신 교착", "communication deadlock",
      "각 process가 상대가 먼저 수행해야 하는 통신을 기다리며 전체 시스템에 가능한 통신 사건이 사라진 상태다.",
      "A state where every process waits for communication that another process must perform first, leaving the whole system with no possible communication event.",
      "두 인터페이스가 모두 상대의 ready를 본 뒤에만 valid를 올리도록 설계해 아무도 먼저 신호를 내지 않는 경우와 같다.",
      "It is like two interfaces each waiting to see the other’s ready before asserting valid, so neither side ever initiates the handshake.",
    ),
  ],

  "lambda-calculus": [
    g(
      "lambda-abstraction", "람다 추상화", "lambda abstraction",
      "입력 매개변수 하나와 그 매개변수를 사용하는 본문을 묶어 익명 함수를 만드는 항이다.",
      "A term that creates an anonymous function by pairing one input parameter with a body that may use that parameter.",
      "이름을 붙이지 않은 parameterized combinational block을 값처럼 다루는 추상화로 생각할 수 있다. `λx. x+1`은 입력 x를 받아 1을 더하는 계산이다.",
      "Think of an unnamed parameterized combinational block treated as a value. `λx. x+1` is a computation that accepts x and adds one.",
      "λx. e",
    ),
    g(
      "beta-reduction", "β-축약", "beta-reduction",
      "함수 적용 `(λx.e) v`에서 본문의 자유로운 x를 인수 v로 안전하게 치환하여 `e[x↦v]`로 바꾸는 계산 단계다.",
      "The computation step that turns an application `(λx.e) v` into `e[x↦v]` by safely substituting argument v for free occurrences of x in the body.",
      "모듈 parameter를 실제 값으로 바꾸어 specialize하거나 inline하는 elaboration과 닮았다. 이름 충돌을 피해야 한다는 점도 같다.",
      "It resembles elaborating or inlining a parameterized module with an actual value. The transformation must likewise avoid name collisions.",
      "(λx.e) v →β e[x ↦ v]",
    ),
    g(
      "normal-order", "정상 순서", "normal order",
      "항의 가장 바깥쪽, 가장 왼쪽에 있는 β-redex를 먼저 줄이는 평가 순서다. 정상형이 존재한다면 이 전략은 결국 그것을 찾는다.",
      "An evaluation order that reduces the leftmost, outermost beta redex first. If a normal form exists, this strategy eventually finds it.",
      "필요한 출력 cone부터 펼쳐 내부 블록은 실제로 요구될 때만 계산하는 demand-driven 접근과 비슷하다. 쓰이지 않는 인수 계산은 건너뛸 수 있다.",
      "It resembles a demand-driven approach that expands the output cone first and computes internal blocks only when needed. An unused argument computation may be skipped.",
    ),
    g(
      "eager-evaluation", "적극 평가", "eager evaluation",
      "함수 본문에 들어가기 전에 인수를 먼저 값으로 계산하는 평가 전략이다. call-by-value가 대표적인 형태다.",
      "An evaluation strategy that computes a function’s argument to a value before entering the function body. Call-by-value is the standard example.",
      "downstream block이 결과를 사용할지와 관계없이 upstream 연산을 먼저 완료하고 register에 넣는 pipeline과 닮았다.",
      "It resembles a pipeline that completes and registers an upstream computation before the downstream block runs, whether or not it will ultimately use that result.",
    ),
    g(
      "fixed-point-combinator", "고정점 결합자", "fixed-point combinator",
      "함수 F를 받아 `F(f)=f`를 만족하는 고정점 f를 만들어 이름 없는 람다 계산 안에서 재귀를 표현하게 하는 항이다.",
      "A lambda term that takes a function F and produces a fixed point f satisfying `F(f)=f`, enabling recursion without named recursive definitions.",
      "명시적 자기 인스턴스 이름 없이 피드백 경로를 구성해 블록 출력이 다시 블록 입력 정의에 들어가게 만드는 것과 비슷하다. 계산 semantics에서는 비종료 가능성도 함께 생긴다.",
      "It resembles constructing a feedback path without an explicitly named self-instance, so a block’s output re-enters its own definition. In computation this also introduces possible nontermination.",
      "Y F = F (Y F)",
    ),
  ],

  "eager-functional-language": [
    g(
      "evaluation-semantics", "evaluation semantics", "evaluation semantics",
      "식이 여러 작은 단계를 거치는 대신 어떤 값으로 평가되는지를 직접 나타내는 판단 규칙 체계다. 환경과 식에서 시작해 값으로 끝나는 큰 단계 설명으로 자주 쓴다.",
      "A system of judgment rules that directly relates an expression to the value it evaluates to, often as a big-step description from environment and expression to value.",
      "조합 논리의 내부 gate 전파를 모두 기록하지 않고 입력 벡터와 안정된 출력값 사이의 관계만 적는 behavioral model과 비슷하다.",
      "It resembles a behavioral model that relates an input vector directly to the stable output without recording every internal gate-propagation step.",
      "ρ ⊢ e ⇓ v",
    ),
    g(
      "closure", "클로저", "closure",
      "함수의 코드와 그 함수가 정의될 때 자유 변수 값을 찾을 환경을 함께 묶은 실행 값이다.",
      "A runtime value pairing function code with the environment used to resolve the function’s free variables when it was defined.",
      "parameterized IP 인스턴스가 공통 RTL 본문뿐 아니라 자기 parameter 설정값도 함께 가져야 정확히 동작하는 것과 비슷하다. 코드만 복사하면 정의 당시 문맥을 잃는다.",
      "It resembles an instantiated parameterized IP needing both shared RTL and its own parameter settings. Copying only the code loses the context captured at definition time.",
      "⟨λx.e, ρ⟩",
    ),
    g(
      "pattern-matching", "패턴 매칭", "pattern matching",
      "값의 constructor 모양을 검사하고 그 안의 구성 요소에 이름을 붙여 알맞은 분기를 선택하는 연산이다.",
      "An operation that inspects a value’s constructor shape, binds names to its components, and selects the corresponding branch.",
      "packet header의 opcode를 decode해 형식별 datapath로 보내고 field를 뽑는 것과 같다. 단순 비교를 넘어 구조 분해와 이름 연결을 함께 한다.",
      "It is like decoding a packet opcode, routing to a format-specific datapath, and extracting fields. Pattern matching combines selection with structural unpacking and name binding.",
    ),
    g(
      "recursive-environment", "재귀 환경", "recursive environment",
      "함수 이름이 자기 자신이나 같은 그룹의 다른 함수를 가리킬 수 있도록 고정점으로 묶인 환경이다.",
      "An environment tied as a fixed point so a function name can refer to itself or to other functions in the same recursive group.",
      "서로 연결된 FSM 블록의 symbolic name을 먼저 마련한 뒤 feedback 연결을 닫는 것과 비슷하다. 정의가 완성되기 전에 이름을 참조할 수 있어야 한다.",
      "It resembles allocating symbolic names for mutually connected FSM blocks before closing their feedback wiring. Names must be referable while the definitions are being completed.",
    ),
    g(
      "dynamic-binding", "동적 바인딩", "dynamic binding",
      "자유 변수의 값을 함수가 정의된 위치가 아니라 함수가 호출된 시점의 호출 환경에서 찾는 이름 해석 방식이다.",
      "A name-resolution strategy that looks up a function’s free variables in the caller’s environment at call time rather than where the function was defined.",
      "고정된 module hierarchy의 parameter를 쓰는 대신 현재 debug context나 호출 stack에서 같은 이름의 설정을 찾아 쓰는 것에 가깝다. 호출자에 따라 함수 동작이 바뀔 수 있다.",
      "It is closer to reading a same-named setting from the current debug context or call stack than using a fixed module-hierarchy parameter. Behavior may change with the caller.",
    ),
  ],

  "functional-continuations": [
    g(
      "continuation-passing-style", "계속 전달 방식", "continuation-passing style",
      "모든 함수가 정상 반환 대신 ‘다음에 할 일’을 나타내는 계속을 명시적 인수로 받도록 프로그램 전체를 쓰거나 변환하는 방식이다.",
      "A style or transformation in which every function receives an explicit continuation representing what to do next instead of returning normally.",
      "각 datapath stage가 결과와 함께 다음 state ID 또는 downstream enable을 명시적으로 전달하도록 control을 배선한 구조와 닮았다.",
      "It resembles wiring control so every datapath stage explicitly forwards a next-state ID or downstream enable together with its result.",
    ),
    g(
      "first-class-continuation", "일급 계속", "first-class continuation",
      "현재 남은 계산을 보통 값처럼 저장하고, 전달하고, 나중에 다시 호출할 수 있게 만든 계속이다.",
      "A continuation made into an ordinary value that can be stored, passed, and invoked later to resume the remaining computation.",
      "PC와 필요한 control state를 checkpoint record로 저장해 다른 곳에 전달하고 나중에 복원할 수 있게 한 것과 비슷하다. 단순 return address보다 넓은 제어 문맥을 담는다.",
      "It resembles packaging the PC and required control state into a checkpoint record that can be passed around and restored later. It captures more context than a simple return address.",
    ),
    g(
      "call-cc", "call/cc", "call/cc",
      "현재 계속을 일급 값으로 함수에 넘기는 제어 연산이다. 받은 계속을 호출하면 현재 흐름을 버리고 캡처한 지점 이후로 이동한다.",
      "A control operator that passes the current continuation to a function as a first-class value. Invoking it abandons the current flow and resumes after the capture point.",
      "현재 control checkpoint를 callback으로 노출해 오류나 성공 조건에서 즉시 그 state로 복귀하게 하는 강력한 escape mechanism과 비슷하다.",
      "It resembles exposing the current control checkpoint as a callback that can immediately restore that state on an error or success condition.",
      "call/cc : ((A → R) → A) → A",
    ),
    g(
      "nonlocal-exit", "비지역 탈출", "nonlocal exit",
      "현재 함수 하나만 반환하는 것이 아니라 여러 겹의 호출 문맥을 한 번에 건너뛰어 바깥 처리 지점으로 제어를 옮기는 동작이다.",
      "A control transfer that skips several nested call contexts at once and resumes at an outer handler rather than returning from only the current function.",
      "깊은 submodule 처리 중 fatal error가 나면 중간 완료 상태를 거치지 않고 top-level recovery FSM으로 바로 전이하는 것과 같다.",
      "It is like a fatal error deep in submodule processing transferring directly to a top-level recovery FSM without passing through ordinary intermediate completion states.",
    ),
    g(
      "defunctionalization", "비함수화", "defunctionalization",
      "가능한 함수 값들을 유한한 data constructor들로 바꾸고, 하나의 apply dispatcher가 각 경우를 실행하도록 만드는 변환이다.",
      "A transformation that replaces possible function values with a finite set of data constructors and one apply dispatcher that interprets each case.",
      "여러 callback 회로를 직접 들고 다니는 대신 opcode와 payload record로 바꾸고 중앙 FSM의 case 문이 실행하게 하는 것과 같다.",
      "It is like replacing a collection of callback circuits with opcode-plus-payload records interpreted by a central FSM case statement.",
    ),
  ],

  "iswim-like-languages": [
    g(
      "location", "위치", "location",
      "저장소에서 값을 넣어 둘 수 있는 식별 가능한 자리다. 위치 자체와 그 위치에 현재 저장된 값은 구분된다.",
      "An identifiable place in the store where a value can reside. The location itself is distinct from the value currently stored there.",
      "SRAM의 address가 위치이고 그 address에서 읽히는 bit pattern이 값인 것과 같다. write 후 값은 달라져도 address 정체성은 유지된다.",
      "It is exactly the distinction between an SRAM address and the bit pattern currently read from that address. A write changes the value but not the address identity.",
    ),
    g(
      "reference", "참조", "reference",
      "저장소의 위치를 가리키는 일급 값이다. 역참조하면 현재 값을 읽고, 대입하면 그 위치의 값을 바꾼다.",
      "A first-class value that designates a location in the store. Dereferencing reads its current content; assignment changes the content at that location.",
      "memory-mapped register의 address를 data로 전달하는 포인터와 같다. 참조를 복사하면 register 값이 복사되는 것이 아니라 같은 address를 가리키는 값이 복사된다.",
      "It is like passing the address of a memory-mapped register as data. Copying the reference copies the address, not the register’s contents.",
    ),
    g(
      "store", "저장소", "store",
      "각 위치를 그 위치에 현재 들어 있는 값으로 보내는 전체 메모리 상태다.",
      "The complete memory state, modeled as a map from every allocated location to the value currently stored there.",
      "특정 시점의 RAM과 register file 내용을 address-to-data map으로 나타낸 것과 같다. 환경이 이름을 위치에 연결한다면 저장소는 위치를 값에 연결한다.",
      "It is the contents of RAM and register files at one instant represented as an address-to-data map. An environment maps names to locations; a store maps locations to values.",
      "μ : Location → Value",
    ),
    g(
      "aliasing", "별칭", "aliasing",
      "서로 다른 두 이름이나 참조가 같은 저장 위치를 가리키는 현상이다. 한 경로로 쓴 값이 다른 경로의 읽기에도 보인다.",
      "The situation where two distinct names or references designate the same storage location. A write through one path is visible through the other.",
      "CPU와 DMA가 같은 physical buffer를 서로 다른 virtual address나 interface 이름으로 접근하는 경우와 같다. 독립된 값이라 생각하면 coherency bug가 생긴다.",
      "It is like a CPU and DMA accessing the same physical buffer through different virtual addresses or interface names. Treating them as independent causes coherency bugs.",
    ),
    g(
      "exception-handler", "예외 처리기", "exception handler",
      "정상 계산 중 특정 예외가 발생하면 일반 계속 대신 제어를 넘겨받아 복구하거나 다른 결과를 만드는 코드다.",
      "Code that receives control when a particular exception occurs during normal computation, replacing the ordinary continuation to recover or produce another result.",
      "error interrupt vector와 recovery FSM을 합친 것과 비슷하다. 오류가 발생한 위치의 정상 datapath 대신 등록된 처리 경로가 선택된다.",
      "It resembles an error interrupt vector combined with a recovery FSM. The registered handler path replaces the normal datapath continuation at the fault point.",
    ),
    g(
      "backtracking", "백트래킹", "backtracking",
      "한 선택 뒤 계산이 실패하면 이전 선택 지점의 상태와 남은 대안을 복원해 다른 경로를 시도하는 제어 방식이다.",
      "A control strategy that, after a chosen path fails, restores an earlier choice point and tries a remaining alternative.",
      "speculative execution checkpoint로 돌아가 register rename과 control state를 복원한 뒤 다른 branch를 실행하는 과정과 닮았다.",
      "It resembles rolling back to a speculative-execution checkpoint, restoring renamed registers and control state, and executing a different branch.",
    ),
  ],

  "normal-order-language": [
    g(
      "call-by-name", "이름에 의한 호출", "call-by-name",
      "인수 식을 먼저 계산하지 않고 함수 본문에 전달하며, 매개변수가 사용될 때마다 그 식을 다시 계산하는 호출 방식이다.",
      "A calling convention that passes an unevaluated argument expression into the body and reevaluates it each time the parameter is used.",
      "실제 신호값을 sample해 넘기기보다 상위 조합식에 대한 연결을 넘겨 각 사용 지점에서 다시 읽는 macro-like 연결과 비슷하다. 부작용이 있으면 매번 결과가 달라질 수 있다.",
      "It resembles passing a connection to an upstream combinational expression rather than sampling its value, so each use reads it again. With effects, repeated uses may differ.",
    ),
    g(
      "lazy-evaluation", "지연 평가", "lazy evaluation",
      "인수 계산을 실제로 필요할 때까지 미루고, 한 번 계산한 결과를 공유해 같은 식을 반복 계산하지 않는 전략이다.",
      "An evaluation strategy that delays a computation until its value is needed and shares the result after the first evaluation to avoid repeated work.",
      "clock gating으로 consumer가 요청할 때만 블록을 켜고, 첫 결과를 register에 저장해 이후 요청에 재사용하는 구조와 닮았다.",
      "It resembles clock-gating a block until a consumer requests its output, then registering the first result and reusing it for later requests.",
    ),
    g(
      "thunk", "썽크", "thunk",
      "아직 실행하지 않은 식과 나중에 그 식을 계산하는 데 필요한 환경을 묶어 둔 지연 계산 객체다.",
      "A delayed-computation object pairing an unevaluated expression with the environment needed to evaluate it later.",
      "보류된 micro-op와 operand source 정보를 queue entry에 넣어 두었다가 ready가 되면 issue하는 것과 비슷하다.",
      "It is like storing a pending micro-operation and its operand-source metadata in a queue entry until it becomes ready to issue.",
    ),
    g(
      "forcing", "강제", "forcing",
      "썽크가 나타내는 지연 계산의 실제 값을 요구해 평가를 시작하고 그 결과를 얻는 동작이다.",
      "The operation of demanding the actual value represented by a thunk, triggering its evaluation and obtaining the result.",
      "consumer가 valid data를 요구해 power-gated producer를 깨우고 결과가 준비될 때까지 handshake를 진행하는 순간에 해당한다.",
      "It corresponds to a consumer demanding valid data, waking a gated producer, and completing the handshake when the result becomes available.",
    ),
    g(
      "memoization", "메모화", "memoization",
      "계산 결과를 저장해 같은 계산이 다시 요구될 때 실행하지 않고 저장된 값을 돌려주는 기법이다.",
      "A technique that stores a computed result and returns the stored value rather than rerunning the same computation on later demand.",
      "동일한 address나 key의 결과를 재사용하는 cache와 같다. lazy evaluation에서는 같은 썽크의 부작용까지 반복되지 않게 한다는 점도 중요하다.",
      "It is like a cache reusing the result for the same address or key. In lazy evaluation it also ensures effects inside one thunk are not repeated.",
    ),
    g(
      "infinite-list", "무한 리스트", "infinite list",
      "끝을 미리 모두 만들지 않고 현재 원소와 다음 원소를 계산할 지연 recipe로 표현한 끝없는 데이터 구조다.",
      "An unbounded data structure represented by a current element and a delayed recipe for computing the rest, rather than being fully constructed in advance.",
      "필요한 cycle의 sample만 계속 만들어 내는 stream generator와 같다. 소비한 prefix만 실제로 존재하므로 유한 메모리로 유한 부분을 다룰 수 있다.",
      "It is like a stream generator that produces samples only for cycles requested by the consumer. Only the consumed prefix is materialized, so finite prefixes fit in finite memory.",
    ),
  ],

  "simple-type-system": [
    g(
      "typing-context", "타입 문맥", "typing context",
      "현재 범위에서 각 자유 변수에 어떤 타입이 약속되어 있는지 기록한 지도다.",
      "A map recording the type promised for every free variable currently in scope.",
      "elaboration symbol table이 signal 이름을 bit width, signedness, interface type에 연결하는 것과 같다. 문맥은 값 자체가 아니라 정적 분류 정보를 담는다.",
      "It is like an elaboration symbol table mapping signal names to bit widths, signedness, and interface types. It stores static classification, not runtime values.",
      "Γ = x₁:τ₁, …, xₙ:τₙ",
    ),
    g(
      "typing-judgment", "타입 판단", "typing judgment",
      "타입 문맥 Γ 아래에서 식 e가 타입 τ를 가진다고 증명 규칙으로 유도할 수 있다는 형식적 statement다.",
      "A formal statement, derivable by typing rules, that expression e has type τ under typing context Γ.",
      "lint나 elaboration이 주어진 port 선언 아래 연결식의 width와 kind가 맞다고 판정하는 정적 확인과 비슷하다.",
      "It resembles a linter or elaborator proving that a connection expression has the right width and kind under the declared ports.",
      "Γ ⊢ e : τ",
    ),
    g(
      "preservation", "보존", "preservation",
      "잘 타입된 항이 한 단계 계산한 뒤에도 같은 타입을 유지한다는 성질이다.",
      "The property that when a well-typed term takes one computation step, the resulting term still has the same type.",
      "정상적인 pipeline 변환을 한 단계 거쳐도 packet format이나 bus interface contract가 깨지지 않는다는 단계별 invariant와 같다.",
      "It is a stepwise invariant saying a valid pipeline transformation does not corrupt the packet format or bus-interface contract.",
      "e:τ and e→e′ implies e′:τ",
    ),
    g(
      "progress", "진행", "progress",
      "닫혀 있고 잘 타입된 항은 이미 값이거나 적어도 한 단계 계산할 수 있으며, 타입 오류 때문에 막히지 않는다는 성질이다.",
      "The property that a closed, well-typed term is either already a value or can take a computation step; it is not stuck because of a type mismatch.",
      "protocol과 width가 정적으로 올바른 FSM이 적어도 합법적인 완료 상태이거나 다음 transition을 가진다는 조건과 비슷하다. deadlock 같은 다른 원인까지 모두 없애 주지는 않는다.",
      "It resembles saying a statically protocol- and width-correct FSM is either in a legal completed state or has a next transition. It does not rule out every other source of deadlock.",
    ),
    g(
      "extrinsic-semantics", "외재적 의미", "extrinsic semantics",
      "먼저 타입 없는 전체 항의 의미 공간을 만들고, 타입 규칙을 그중 안전한 항을 골라내는 별도 predicate로 보는 접근이다.",
      "An approach that first gives meaning to all untyped terms, then treats typing as a separate predicate selecting the safe subset.",
      "모든 raw bit-vector netlist를 같은 simulator가 실행하고 별도 lint pass가 합법적인 interface 연결만 표시하는 구조와 비슷하다.",
      "It resembles one simulator running every raw bit-vector netlist while a separate lint pass marks only the interface-correct designs.",
    ),
    g(
      "intrinsic-semantics", "내재적 의미", "intrinsic semantics",
      "타입마다 별도의 의미 공간을 두어 애초에 잘 타입된 항만 표현되도록 만드는 접근이다.",
      "An approach that gives each type its own semantic space so only well-typed terms can be represented in the first place.",
      "port type이 다른 신호는 연결 객체 자체를 만들 수 없게 한 strongly typed hardware IR과 같다. 잘못된 설계를 나중에 거르는 대신 표현 단계에서 배제한다.",
      "It resembles a strongly typed hardware IR in which a connection object cannot even be constructed for incompatible port types. Invalid designs are excluded by representation.",
    ),
    g(
      "recursive-type", "재귀 타입", "recursive type",
      "자기 자신의 타입을 정의 안에 다시 포함하는 타입이다. fold와 unfold를 통해 유한 syntax로 재귀 데이터 구조를 표현한다.",
      "A type whose definition refers back to itself. Folding and unfolding let finite syntax describe recursive data structures.",
      "linked-list node가 data와 같은 node 타입의 next를 포함하거나, tree node가 child tree들을 포함하는 타입 선언과 같다.",
      "It is the familiar type pattern where a linked-list node contains data plus a next node, or a tree node contains child trees.",
      "μ α. F(α)",
    ),
  ],

  "subtypes-intersection-types": [
    g(
      "subtyping", "서브타이핑", "subtyping",
      "S 타입의 모든 값을 T가 필요한 곳에서 안전하게 사용할 수 있을 때 성립하는 `S <: T` 관계다. 단순히 두 타입의 표현이 비슷하다는 뜻은 아니다.",
      "A relation `S <: T` holding when every value of type S can be used safely wherever T is expected. It is not merely similarity of representations.",
      "더 강한 timing·protocol 보장을 제공하는 IP가 더 약한 요구만 하는 socket에 들어갈 수 있는 interface refinement와 비슷하다.",
      "It resembles interface refinement: an IP block providing stronger timing or protocol guarantees can occupy a socket that requires only weaker ones.",
      "S <: T",
    ),
    g(
      "substitutability", "대체 가능성", "substitutability",
      "프로그램이 기대하는 관찰 가능한 동작을 깨뜨리지 않고 한 타입의 값을 다른 타입 자리에서 바꿔 쓸 수 있는 성질이다.",
      "The ability to replace a value with one of another type without violating the observable behavior expected by the surrounding program.",
      "pinout과 protocol 계약을 지키는 새 IP revision을 기존 board나 SoC integration에 그대로 꽂을 수 있는 조건과 같다.",
      "It is the condition under which a new IP revision can be dropped into an existing board or SoC integration because it preserves pinout and protocol contracts.",
    ),
    g(
      "covariance", "공변성", "covariance",
      "구성 타입 안쪽의 서브타입 방향과 바깥 구성 타입의 서브타입 방향이 같은 성질이다. 보통 읽기만 하는 결과 위치에서 안전하다.",
      "The property that a type constructor preserves the subtype direction of its component. It is typically safe in output-only or read-only positions.",
      "더 구체적인 packet을 출력하는 source는 일반 packet을 받는 sink에도 연결할 수 있다는 방향과 같다. producer 결과 타입은 대개 공변적이다.",
      "It matches the fact that a source producing a more specific packet can feed a sink accepting general packets. Producer result types are commonly covariant.",
      "S <: T ⇒ F(S) <: F(T)",
    ),
    g(
      "contravariance", "반공변성", "contravariance",
      "구성 타입 안쪽의 서브타입 방향이 바깥에서는 반대로 뒤집히는 성질이다. 함수의 입력처럼 값을 받아들이는 위치에서 나타난다.",
      "The property that a type constructor reverses the subtype direction of its component. It appears in consuming positions such as function inputs.",
      "더 넓은 범위의 packet을 받아들일 수 있는 sink라야 특정 packet 전용 sink를 기대한 자리를 안전하게 대신할 수 있다. consumer 요구 방향이 뒤집힌다.",
      "A sink accepting a wider class of packets can safely replace one expected to accept a specific packet. The direction reverses for consumers.",
      "S <: T ⇒ (T→R) <: (S→R)",
    ),
    g(
      "intersection-type", "교차 타입", "intersection type",
      "같은 값이 타입 S와 타입 T의 요구를 모두 만족함을 나타내는 `S ∩ T` 타입이다.",
      "A type `S ∩ T` describing values that satisfy the requirements of both type S and type T.",
      "하나의 IP가 AXI target 계약과 debug interface 계약을 동시에 제공한다고 분류하는 것과 같다. 둘 중 하나를 고르는 union이 아니라 둘 다 갖춘 값이다.",
      "It is like classifying one IP block as satisfying both an AXI-target contract and a debug-interface contract. Unlike a union, the value provides both.",
      "v : S ∩ T",
    ),
    g(
      "coherence", "일관성", "coherence",
      "같은 typing judgment를 만드는 서로 다른 유도 경로가 있더라도 프로그램의 최종 의미가 경로에 따라 달라지지 않는 성질이다.",
      "The property that different derivation paths for the same typing judgment do not give the program different final meanings.",
      "여러 합법적인 adapter 삽입 경로가 모두 같은 pin-level behavior를 만들어야 하는 것과 같다. compiler의 선택이 사용자에게 관찰되면 일관성이 깨진다.",
      "It is like requiring all legal adapter-insertion paths to produce the same pin-level behavior. Coherence fails if the compiler’s chosen path becomes observable.",
    ),
  ],

  "polymorphism": [
    g(
      "universal-polymorphism", "전칭 다형성", "universal polymorphism",
      "하나의 항이 모든 타입 α에 대해 같은 구조로 동작함을 `∀α.T`로 표현하는 타입 체계 기능이다.",
      "A type-system feature, written `∀α.T`, stating that one term works uniformly for every choice of type α.",
      "data width나 payload type을 parameter로 받되 control 구조는 동일한 재사용 IP와 비슷하다. 특정 타입 내부 표현에 의존하면 진정한 전칭 동작이 아니다.",
      "It resembles reusable IP parameterized by data width or payload type while keeping the same control structure. Depending on a specific type’s representation would violate uniformity.",
      "∀α. T",
    ),
    g(
      "type-abstraction", "타입 추상화", "type abstraction",
      "타입 변수를 매개변수로 묶어, 나중에 어떤 타입을 넣을지 정하는 다형적 값을 만드는 항이다.",
      "A term that binds a type variable as a parameter, creating a polymorphic value whose concrete type argument will be chosen later.",
      "아직 WIDTH를 정하지 않은 parameterized module definition과 같다. 정의 안에서는 특정 폭에만 가능한 연산을 가정할 수 없다.",
      "It is like a parameterized module definition before WIDTH has been chosen. Its body cannot assume operations available only at one concrete width.",
      "Λα. e",
    ),
    g(
      "type-application", "타입 적용", "type application",
      "다형적 값의 타입 매개변수에 구체 타입을 넣어 해당 인스턴스로 사용하는 항이다.",
      "A term that supplies a concrete type argument to a polymorphic value, selecting an instance for that type.",
      "parameterized IP를 `WIDTH=32`로 elaborate해 32-bit 인스턴스를 얻는 것과 같다. 실행 데이터 인수를 넣는 일반 함수 적용과는 구분된다.",
      "It is like elaborating parameterized IP with `WIDTH=32` to obtain a 32-bit instance. This differs from supplying ordinary runtime data.",
      "e [τ]",
    ),
    g(
      "system-f", "System F", "System F",
      "타입 추상화와 타입 적용을 명시적으로 포함하는, 전칭 다형성의 핵심 람다 계산이다. 2차 람다 계산이라고도 한다.",
      "The core lambda calculus of universal polymorphism, with explicit type abstraction and type application. It is also called the second-order lambda calculus.",
      "typed IR에서 data operand뿐 아니라 type parameter의 binding과 instantiation까지 노드로 드러낸 최소 intermediate language에 가깝다.",
      "It resembles a minimal typed IR in which binding and instantiation of type parameters are explicit nodes alongside ordinary data operands.",
    ),
    g(
      "polymorphic-encoding", "다형적 인코딩", "polymorphic encoding",
      "별도 primitive data type 없이 전칭 다형 함수의 사용 규칙만으로 Boolean, pair, list 같은 구조를 표현하는 방법이다.",
      "A method of representing structures such as Booleans, pairs, or lists using only the behavior of universally polymorphic functions, without primitive data types.",
      "새 storage primitive를 추가하지 않고 표준 ready/valid 조합 패턴만으로 queue나 selector protocol을 표현하는 구조적 encoding과 비슷하다.",
      "It resembles structurally encoding a queue or selector protocol from standard ready/valid composition patterns without adding a new storage primitive.",
    ),
  ],

  "module-specification": [
    g(
      "abstract-type", "추상 타입", "abstract type",
      "모듈 밖에서는 내부 표현을 알 수 없고 공개된 연산을 통해서만 값을 만들고 관찰할 수 있는 타입이다.",
      "A type whose internal representation is hidden outside a module, so clients can create and observe values only through exported operations.",
      "내부 register map을 숨기고 command/status interface만 공개한 IP와 같다. integration 코드는 구현 bit layout에 직접 의존할 수 없다.",
      "It is like an IP block that hides its internal register map and exposes only command/status operations. Integration code cannot depend on the implementation’s bit layout.",
    ),
    g(
      "existential-type", "실존 타입", "existential type",
      "‘어떤 숨겨진 표현 타입 α가 존재하고, 그 α로 이 인터페이스 T를 구현한다’를 `∃α.T`로 나타내는 패키지 타입이다.",
      "A package type `∃α.T` saying that some hidden representation type α exists together with an implementation of interface T at that α.",
      "내부 SRAM인지 register array인지 밝히지 않은 채 read/write 계약만 제공하는 sealed IP package와 같다.",
      "It is like a sealed IP package that exposes a read/write contract without revealing whether its storage is SRAM or a register array.",
      "∃α. T",
    ),
    g(
      "packing", "패키징", "packing",
      "구체 표현 타입과 그 구현 값을 실존 타입 뒤에 봉인하여 클라이언트가 표현을 직접 사용하지 못하게 하는 연산이다.",
      "The operation that seals a concrete representation type and implementation value behind an existential type so clients cannot use the representation directly.",
      "검증된 RTL과 내부 parameter를 encrypted IP wrapper 안에 넣고 공개 port 계약만 남기는 과정과 비슷하다.",
      "It resembles placing verified RTL and internal parameters inside an encrypted IP wrapper while exposing only the public port contract.",
      "pack [R, m] as ∃α.T",
    ),
    g(
      "unpacking", "개봉", "unpacking",
      "실존 패키지를 열어 숨겨진 타입을 신선한 추상 이름으로, 구현을 인터페이스 값으로 잠시 사용하되 표현이 밖으로 새지 못하게 하는 연산이다.",
      "The operation that opens an existential package, temporarily naming its hidden type abstractly and its implementation as an interface value, without allowing the representation to escape.",
      "IP wrapper 안쪽에서만 private bus type을 연결하고 외부에는 표준 interface만 계속 노출하는 integration scope와 비슷하다.",
      "It resembles an integration scope where a private bus type is connected only inside an IP wrapper while the outside continues to see a standard interface.",
      "unpack [α, x] = p in e",
    ),
    g(
      "representation-independence", "표현 독립성", "representation independence",
      "공개 연산의 관찰 결과를 보존하는 한 내부 표현을 다른 것으로 바꿔도 모든 올바른 클라이언트의 동작이 같다는 성질이다.",
      "The property that one internal representation can replace another without changing any well-behaved client, provided observations through exported operations are preserved.",
      "FIFO를 flip-flop array에서 SRAM macro로 바꿔도 latency·ordering·handshake 계약이 같으면 상위 RTL을 수정할 필요가 없는 것과 같다.",
      "It is like replacing a FIFO’s flip-flop array with an SRAM macro without changing surrounding RTL because latency, ordering, and handshake contracts remain identical.",
    ),
  ],

  "algol-like-languages": [
    g(
      "phrase-type", "구절 타입", "phrase type",
      "저장되는 데이터의 종류가 아니라 expression, 쓰기 대상, command, procedure처럼 프로그램 조각이 제공하는 계산 능력을 분류하는 타입이다.",
      "A type classifying the computational capability provided by a program phrase—expression, writable target, command, or procedure—rather than the kind of stored data.",
      "같은 32-bit data라도 source-only port, sink-only port, 양방향 register interface가 다른 capability type을 갖는 것과 같다.",
      "It is like giving different capability types to a source-only port, sink-only port, and bidirectional register interface even though all carry 32-bit data.",
    ),
    g(
      "acceptor", "acceptor", "acceptor",
      "주어진 타입의 값을 받아 저장하거나 반영할 수 있는 쓰기 능력을 나타내는 구절이다. 값을 읽어 내는 expression과 반대 방향이다.",
      "A phrase representing the capability to accept and store or otherwise act on a value of a given type. Its direction contrasts with an expression that produces a value.",
      "write-only register port나 ready를 가진 data sink와 같다. 값을 어디서 읽는지는 제공하지 않고 값을 보낼 수 있는 endpoint만 제공한다.",
      "It is like a write-only register port or a data sink with ready. It provides an endpoint for sending a value, not a way to read one back.",
      "acc[τ]",
    ),
    g(
      "variable", "variable", "variable",
      "같은 저장 대상을 읽는 expression 능력과 쓰는 acceptor 능력을 함께 제공하는 구절이다.",
      "A phrase combining an expression capability for reading a storage object with an acceptor capability for writing it.",
      "read data port와 write data/enable port가 한 register abstraction을 이루는 것과 같다. 단순 값이 아니라 읽기와 쓰기라는 두 동작을 묶는다.",
      "It is like the read-data and write-data/enable ports together forming one register abstraction. A variable packages two operations, not just a value.",
      "var[τ] ≈ exp[τ] × acc[τ]",
    ),
    g(
      "declarator", "선언자", "declarator",
      "새 저장 공간과 그 이름 또는 능력을 만들고, 정해진 본문 범위에 제공한 뒤 범위가 끝나면 회수하는 프로그램 구성이다.",
      "A program construct that allocates fresh storage and a name or capability for it, supplies it within a body scope, and reclaims it when that scope ends.",
      "submodule 진입 시 local scratchpad를 할당해 내부 datapath에만 연결하고 작업이 끝나면 재사용 가능하게 만드는 lifetime controller와 비슷하다.",
      "It resembles a lifetime controller allocating a local scratchpad for one submodule operation, wiring it only to the internal datapath, then reclaiming it afterward.",
    ),
    g(
      "stack-discipline", "스택 규율", "stack discipline",
      "나중에 할당된 지역 저장이 먼저 해제되고, 지역 위치가 그 범위보다 오래 살아남지 못하도록 하는 LIFO 수명 규칙이다.",
      "A LIFO lifetime rule under which later local allocations are released first and no local location survives beyond its scope.",
      "nested procedure마다 stack frame을 push하고 return 때 pop하는 CPU runtime과 같다. local address가 밖으로 escape하면 pop 뒤 dangling reference가 생겨 규율이 깨진다.",
      "It is the CPU runtime pattern of pushing a stack frame for each nested procedure and popping it on return. An escaping local address would become a dangling reference after the pop.",
    ),
    g(
      "algol", "Algol", "Algol",
      "block structure, lexical scope, 지역 변수, procedure를 현대적 형태로 정립한 초기 언어 계열이다. 이 장에서는 그 설계 원리를 의미와 타입으로 분석한다.",
      "An early language family that established modern forms of block structure, lexical scope, local variables, and procedures. This chapter studies its design principles semantically and through types.",
      "현대 HDL의 nested scope, automatic variable, task/function 같은 기능의 역사적 조상 중 하나로 볼 수 있다. 특정 최신 언어 문법을 배우는 장은 아니다.",
      "It can be viewed as one historical ancestor of nested scope, automatic variables, and task/function concepts found in modern HDLs. The chapter is not a tutorial for one modern language.",
    ),
  ],

  "mathematical-background": [
    g(
      "powerset", "멱집합", "powerset",
      "집합 S에서 만들 수 있는 모든 부분집합을 원소로 갖는 집합이다. 빈 집합과 S 자체도 포함한다.",
      "The set of every subset that can be formed from S, including the empty set and S itself.",
      "가능한 interrupt source 집합 S가 있을 때, 한 순간 활성화될 수 있는 모든 source 조합의 집합이 `P(S)`다. source가 n개면 멱집합 원소는 2ⁿ개다.",
      "If S is the set of possible interrupt sources, `P(S)` is the set of every combination that could be active at one instant. For n sources it has 2ⁿ elements.",
      "P(S) = { X | X ⊆ S }",
    ),
    g(
      "relational-composition", "관계 합성", "relational composition",
      "관계 R로 한 번 이동하고 이어서 관계 S로 이동할 수 있을 때 시작과 끝을 직접 연결하는 새 관계를 만드는 연산이다.",
      "An operation forming a new relation between start and end points whenever one can first follow relation R and then relation S through an intermediate point.",
      "한 클록의 next-state relation을 두 번 합성해 2클록 뒤 가능한 상태 관계를 얻는 것과 같다. 함수 합성과 달리 중간값이 여러 개일 수 있다.",
      "It is like composing a one-clock next-state relation with itself to obtain possible states two clocks later. Unlike function composition, several intermediate states may exist.",
    ),
    g(
      "partial-function", "부분 함수", "partial function",
      "정의역의 일부 입력에서는 결과가 존재하지 않을 수 있는 함수다. 결과가 존재하는 입력에서는 여전히 하나의 결과만 갖는다.",
      "A function that may have no result for some inputs in its intended input set. Wherever it is defined, it still has only one result.",
      "일부 opcode나 address에서만 유효한 decoder table과 비슷하다. 프로그램 semantics에서는 비종료나 오류 때문에 최종 결과가 없는 경우를 나타낼 수 있다.",
      "It resembles a decoder table valid only for selected opcodes or addresses. In program semantics, undefinedness can represent nontermination or failure to produce a final result.",
      "f : A ⇀ B",
    ),
    g(
      "cartesian-product", "데카르트 곱", "Cartesian product",
      "A의 원소 하나와 B의 원소 하나를 순서쌍으로 함께 담는 모든 경우의 집합이다.",
      "The set of every ordered pair containing one element from A together with one element from B.",
      "address 집합 A와 data 집합 D의 곱 `A×D`는 가능한 모든 address-data pair의 type과 같다. 둘 중 하나를 고르는 것이 아니라 둘을 동시에 담는다.",
      "The product `A×D` of address set A and data set D is the type of every possible address–data pair. It contains both components, not a choice between them.",
      "A × B = { (a,b) | a∈A, b∈B }",
    ),
    g(
      "disjoint-union", "분리합", "disjoint union",
      "A의 값 또는 B의 값 중 하나를, 어느 쪽에서 왔는지 나타내는 tag와 함께 담는 집합이다.",
      "A set containing either a value from A or a value from B together with a tag recording which side it came from.",
      "packet payload를 `{tag, normal_data}` 또는 `{tag, error_code}` 형식으로 보내는 tagged union과 같다. 양쪽 bit pattern이 같아도 tag 덕분에 경우를 구분한다.",
      "It is a tagged union carrying either `{tag, normal_data}` or `{tag, error_code}`. The tag preserves the case even when both sides could use the same bit pattern.",
      "A + B",
    ),
    g(
      "reflexive-transitive-closure", "반사·추이 폐쇄", "reflexive-transitive closure",
      "관계 R을 0회 이상 이어서 도달할 수 있는 모든 쌍을 포함하는 가장 작은 관계다. 0회 경로 때문에 각 원소는 자기 자신과도 관계된다.",
      "The smallest relation containing every pair reachable by following R zero or more times. Zero-length paths make every element related to itself.",
      "한 사이클 전이 R에서 임의의 사이클 수 뒤 도달 가능성을 구한 `R*`와 같다. reset 직후 그대로 있는 0사이클 경우도 반드시 포함한다.",
      "It is `R*`, reachability after any number of cycles from a one-cycle relation R. It necessarily includes the zero-cycle case of remaining in the current state.",
      "R* = I ∪ R ∪ R² ∪ …",
    ),
  ],
};

export function getChapterGlossary(slug: string): GlossaryEntry[] | undefined {
  return chapterGlossaries[slug];
}
