import { b, type StudyUnit } from "./types";

export const units06to10: StudyUnit[] = [
  {
    number:"06",slug:"transition-semantics",part:2,pages:"126–135",minutes:60,
    title:b("transition semantics","Transition Semantics"),eyebrow:b("실행을 작은 단계로 분해하기","Decomposing execution into small steps"),
    overview:b("structural operational semantics을 사용해 프로그램 실행을 구성 사이의 한 단계 전이로 정의한다. 실패와 입출력은 종료 구성과 전이 라벨을 확장한다.","Structural operational semantics defines execution as one-step transitions between configurations. Failure and I/O extend terminal configurations and transition labels."),
    goals:[b("구성, 전이, 실행을 구분한다.","Distinguish configurations, transitions, and executions."),b("프로그램 syntax별 전이 규칙을 읽고 유도한다.","Read and derive syntax-directed transition rules."),b("라벨 있는 전이로 입출력을 표현한다.","Represent I/O with labeled transitions.")],
    keyTerms:[b("구성","configuration"),b("small-step semantics","small-step semantics"),b("전이 폐쇄","transition closure"),b("결정성","determinacy"),b("라벨 전이","labeled transition")],
    steps:[
      {id:"configurations",covers:"§6.1",title:b("1단계 — 실행 상태를 구성으로 만들기","Step 1 — Package execution state as a configuration"),summary:b("비종료 구성은 남은 명령과 상태를, 종료 구성은 결과 상태를 담는다.","A nonterminal configuration contains the remaining command and state; a terminal configuration is a result state."),detail:b("한 단계 관계 `γ → γ′`를 반복하면 유한 또는 무한 실행이 된다. 반사·추이 폐쇄 `→*`는 0회 이상의 이동을, 무한 전이열은 발산을 표현한다.","Repeating the one-step relation `γ → γ′` yields finite or infinite executions. Its reflexive-transitive closure `→*` represents zero or more steps, while an infinite transition sequence represents divergence."),checkpoint:b("`→`와 `→*`가 각각 답하는 질문을 한 문장씩 써 보라.","State in one sentence each what questions `→` and `→*` answer."),notation:"(c, σ) → (c′, σ′)    and    (c, σ) →* σ′"},
      {id:"rules",covers:"§6.2",title:b("2단계 — 규칙으로 인터프리터 읽기","Step 2 — Read the rules as an interpreter"),summary:b("대입과 skip은 즉시 움직이고, 복합 명령은 부분 명령의 한 단계를 바깥 문맥으로 올린다.","Assignment and skip move immediately; compound commands lift a subcommand step through an outer context."),detail:b("순차 규칙은 왼쪽 명령이 끝나면 오른쪽으로 넘어가고, 아직 끝나지 않았으면 왼쪽의 한 단계를 전체의 한 단계로 전파한다. 규칙의 적용 가능성이 겹치지 않으면 언어는 결정적이다.","Sequencing moves to the right command when the left terminates; otherwise it propagates one left-hand step to the whole command. If applicable rules never conflict, the language is deterministic."),checkpoint:b("`(skip;c,σ)→(c,σ)`와 `c₀`의 내부 단계를 올리는 규칙의 역할 차이는?", "What different roles are played by `(skip;c,σ)→(c,σ)` and the rule that lifts an internal step of `c₀`?")},
      {id:"failure",covers:"§6.3",title:b("3단계 — 비정상 종료 전파","Step 3 — Propagate abnormal termination"),summary:b("실패는 `(abort,σ)`라는 별도 종료 구성을 만들고 복합 syntax은 이를 바깥으로 전파한다.","Failure produces a distinct terminal configuration `(abort,σ)`, which compound constructs propagate outward."),detail:b("정상 상태만 전제로 한 기존 규칙에 실패 전파 규칙을 추가해야 한다. 이 작업은 새 효과를 언어에 넣을 때 기존 모든 평가 문맥을 다시 점검해야 함을 보여 준다.","Rules written only for normal states need companion abort-propagation rules. This illustrates why adding an effect requires auditing every existing evaluation context."),checkpoint:b("순차 구성에서 앞 명령이 실패하면 뒤 명령을 실행하면 안 되는 이유를 규칙으로 표현하라.","State as a rule why the second command of a sequence must not run after the first fails.")},
      {id:"io",covers:"§6.4",title:b("4단계 — 관찰을 전이에 라벨링","Step 4 — Label transitions with observations"),summary:b("침묵 전이와 입력 `?n`, 출력 `!n` 전이를 구분하면 실행 흔적이 외부 상호작용을 기록한다.","Distinguishing silent transitions from input `?n` and output `!n` transitions records external interaction in an execution trace."),detail:b("입력은 환경이 고른 n마다 가능한 전이를 만들고, 출력은 현재 식 값으로 라벨이 결정된다. 복합 명령 규칙은 부분 명령의 라벨을 그대로 보존해야 한다.","Input permits a transition for every n supplied by the environment; output determines its label from the current expression value. Compound-command rules must preserve the subcommand label."),checkpoint:b("출력 전이가 상태 변경 없이도 의미 있는 이유는?", "Why is an output transition meaningful even if it does not change the state?")},
    ],
    quiz:[
      {question:b("small-step semantics의 기본 판단은?","What is the basic judgment of small-step semantics?"),options:[b("한 구성이 한 단계 뒤 어떤 구성으로 가는가","Which configuration follows in one step"),b("프로그램의 타입은 무엇인가","What type a program has"),b("최종 값만 무엇인가","Only what the final value is")],correct:0,explanation:b("다단계 실행은 한 단계 관계의 반복으로 얻는다.","Multi-step execution is built by iterating the one-step relation.")},
      {question:b("결정적 transition semantics에서 가능한 다음 구성의 수는?","In deterministic transition semantics, how many next configurations are possible?"),options:[b("항상 무한 개","Always infinitely many"),b("최대 하나","At most one"),b("정확히 두 개","Exactly two")],correct:1,explanation:b("한 비종료 구성에서 서로 다른 두 다음 단계가 없어야 한다.","A nonterminal configuration cannot have two distinct next steps.")},
      {question:b("입출력 라벨의 목적은?","What is the purpose of I/O labels?"),options:[b("외부 관찰 사건을 전이열에 보존","Preserve external observations in the transition sequence"),b("변수 범위를 정함","Determine variable scope"),b("루프를 최적화","Optimize loops")],correct:0,explanation:b("상태 변화만으로 보이지 않는 상호작용을 기록한다.","They record interactions invisible in state changes alone.")},
    ],
    bridge:b("전이가 함수가 아닌 관계가 되도록 허용하면 여러 가능한 실행을 갖는 비결정적 언어를 설명할 수 있다.","Allowing transition to be a relation rather than a function opens the door to nondeterministic languages with many possible executions."),
  },
  {
    number:"07",slug:"nondeterminism",part:2,pages:"136–154",minutes:85,
    title:b("비결정성과 보호 명령","Nondeterminism and Guarded Commands"),eyebrow:b("하나의 프로그램, 여러 가능한 결과","One program, many possible outcomes"),
    overview:b("Dijkstra의 보호 명령을 통해 비결정적 선택과 반복을 도입하고, 전이 관계·파워도메인·명세·최약 전제조건을 연결한다.","Dijkstra's guarded commands introduce nondeterministic choice and iteration, connecting transition relations, powerdomains, specifications, and weakest preconditions."),
    goals:[b("선택 가능성과 선택 결과를 구분한다.","Distinguish enabled choices from selected outcomes."),b("may와 must 관찰의 차이를 설명한다.","Explain the difference between may and must observations."),b("최약 전제조건을 명세와 계산 양쪽에서 사용한다.","Use weakest preconditions both as specifications and calculations.")],
    keyTerms:[b("보호 명령","guarded command"),b("비결정성","nondeterminism"),b("파워도메인","powerdomain"),b("교착","deadlock"),b("최약 전제조건","weakest precondition")],
    steps:[
      {id:"guards",covers:"§7.1",title:b("1단계 — 활성 가드 중 하나를 고르기","Step 1 — Choose among enabled guards"),summary:b("여러 가드가 참이면 어느 분기든 실행될 수 있고, 모두 거짓이면 선택문은 교착하거나 반복문은 끝난다.","If several guards are true, any corresponding branch may run; if all are false, selection deadlocks while guarded iteration terminates."),detail:b("전이 관계는 동일 구성에서 여러 다음 구성을 허용한다. 비결정성은 확률을 말하지 않으며, 단지 구현이나 환경이 허용된 선택 중 하나를 고른다는 뜻이다.","The transition relation permits multiple next configurations from one state. Nondeterminism is not probability; it merely leaves the choice among allowed branches unspecified."),checkpoint:b("`if b₁→c₁ ▯ b₂→c₂ fi`에서 두 가드가 모두 참이면 무엇이 보장되고 무엇은 보장되지 않는가?", "When both guards of `if b₁→c₁ ▯ b₂→c₂ fi` are true, what is guaranteed and what is not?")},
      {id:"powerdomains",covers:"§7.2–7.3",title:b("2단계 — 결과 집합의 정보 순서","Step 2 — Order sets of possible results"),summary:b("비결정적 의미는 결과 하나가 아니라 가능한 결과들의 집합이며, 발산 가능성까지 보존하는 순서가 필요하다.","A nondeterministic meaning is a set of possible results, ordered so that potential divergence is not lost."),detail:b("단순 멱집합만으로는 근사·발산·유한 관찰을 올바르게 표현하기 어렵다. 제한된 비결정성 아래 파워도메인은 may 결과와 반드시 보장되는 must 성질을 구분할 수 있게 한다.","A plain powerset mishandles approximation, divergence, and finite observation. Under bounded nondeterminism, a powerdomain supports distinctions between may outcomes and properties that must hold."),checkpoint:b("가능한 결과에 좋은 상태 하나가 있다는 것과 모든 가능한 결과가 좋다는 것은 어떤 차이인가?", "What is the difference between one possible result being good and every possible result being good?")},
      {id:"proof",covers:"§7.4",title:b("3단계 — 악의적인 선택자에 대해 증명하기","Step 3 — Prove against an adversarial chooser"),summary:b("전체 정확성은 허용된 모든 선택이 안전하고 종료함을 보여야 한다.","Total correctness must show that every allowed choice is safe and terminating."),detail:b("선택 규칙은 각 활성 분기의 사양을 증명하고, 보호 반복의 변량은 어느 분기를 택해도 감소해야 한다. 한 번의 좋은 실행을 제시하는 것으로는 보편적 명세가 증명되지 않는다.","The choice rule proves the specification for each enabled branch, and a guarded-loop variant must decrease for every possible branch. Exhibiting one good execution does not establish a universal specification."),checkpoint:b("비결정적 프로그램의 테스트 한 번이 전체 정확성 증거가 될 수 없는 이유는?", "Why can one test run never establish total correctness of a nondeterministic program?")},
      {id:"wp",covers:"§7.5",title:b("4단계 — 사후조건에서 최약 전제조건 계산","Step 4 — Calculate weakest preconditions"),summary:b("`wp(c,q)`는 c가 반드시 종료해 q를 만족하게 하는 가장 약한 초기 조건이다.","`wp(c,q)` is the weakest initial condition ensuring that c terminates and establishes q."),detail:b("순차 구성의 wp는 안쪽부터 합성하고, 비결정적 선택은 모든 가능한 분기의 wp를 만족해야 한다. 이렇게 semantic 사양이 프로그램 구조를 따라 계산되는 assertion 변환기로 바뀐다.","Sequential wp composes from the inside out; nondeterministic choice requires the wp of every possible branch. A semantic specification becomes a syntax-directed predicate transformer."),checkpoint:b("`wp(c₀;c₁,q)=wp(c₀,wp(c₁,q))`를 실행 순서로 설명하라.", "Explain `wp(c₀;c₁,q)=wp(c₀,wp(c₁,q))` using execution order."),notation:"wp(c, q) = weakest p such that [p] c [q]"},
    ],
    quiz:[
      {question:b("비결정성은 무엇과 다른가?","Nondeterminism is distinct from what?"),options:[b("확률적 선택","Probabilistic choice"),b("여러 가능한 실행","Multiple possible executions"),b("전이 관계","A transition relation")],correct:0,explanation:b("비결정성만으로 각 선택의 확률은 주어지지 않는다.","Nondeterminism assigns no probability to alternatives.")},
      {question:b("보편적 안전성 명세에서 필요한 관점은?","Which viewpoint is needed for universal safety?"),options:[b("한 성공 실행","One successful execution"),b("모든 허용된 실행","All allowed executions"),b("가장 짧은 실행만","Only the shortest execution")],correct:1,explanation:b("선택자는 가장 불리한 허용 분기를 택할 수 있다.","The chooser may select any allowed branch, including the worst one.")},
      {question:b("wp의 'weakest' 의미는?","What does 'weakest' mean in wp?"),options:[b("가장 적은 초기 상태를 허용","Allows the fewest initial states"),b("정확성을 보장하면서 가장 많은 초기 상태를 허용","Allows the most initial states while guaranteeing correctness"),b("증명할 수 없는 조건","An unprovable condition")],correct:1,explanation:b("논리적으로 약한 조건일수록 더 많은 상태가 만족한다.","A logically weaker assertion is satisfied by more states.")},
    ],
    bridge:b("여러 전이가 서로 다른 프로세스의 한 단계라면, 비결정성은 공유 변수 동시성의 인터리빙으로 해석된다.","When alternatives are steps of different processes, nondeterminism becomes interleaving concurrency over shared variables."),
  },
  {
    number:"08",slug:"shared-variable-concurrency",part:2,pages:"155–180",minutes:105,
    title:b("공유 변수 동시성","Shared-Variable Concurrency"),eyebrow:b("인터리빙, 원자성, 공정성","Interleaving, atomicity, fairness"),
    overview:b("병렬 구성의 인터리빙 의미를 출발점으로 임계 구역, 상호 배제, 교착, 공정성, 재개 의미, 전이 흔적을 다룬다.","Starting from interleaving semantics for parallel composition, the chapter studies critical regions, mutual exclusion, deadlock, fairness, resumptions, and transition traces."),
    goals:[b("원자적 단계와 가능한 인터리빙을 열거한다.","Enumerate atomic steps and possible interleavings."),b("상호 배제·교착 없음·공정성을 구분한다.","Distinguish mutual exclusion, deadlock freedom, and fairness."),b("전이 흔적에서 stuttering과 mumbling의 역할을 설명한다.","Explain stuttering and mumbling in transition traces.")],
    keyTerms:[b("인터리빙","interleaving"),b("임계 구역","critical region"),b("상호 배제","mutual exclusion"),b("교착","deadlock"),b("공정성","fairness"),b("말더듬/뭉개기","stuttering/mumbling")],
    steps:[
      {id:"parallel",covers:"§8.1",title:b("1단계 — 병렬 실행을 인터리빙으로","Step 1 — Model parallelism by interleaving"),summary:b("각 프로세스는 한 번에 한 원자적 전이를 수행하며 스케줄러가 순서를 비결정적으로 고른다.","Each process performs one atomic transition at a time, with the scheduler choosing the order nondeterministically."),detail:b("`c₀ ‖ c₁`의 규칙은 어느 한쪽의 단계를 전체 병렬 구성의 단계로 올린다. 실제 동시 수행을 모든 허용된 순차 인터리빙의 집합으로 추상화한다.","Rules for `c₀ ‖ c₁` lift a step from either side to the entire parallel command. True simultaneity is abstracted as the set of all allowed sequential interleavings."),checkpoint:b("두 프로세스가 각각 두 번 대입할 때 원자적 대입만 가정하면 가능한 순서 수를 생각해 보라.", "Consider how many schedules exist when two processes each perform two atomic assignments.")},
      {id:"critical",covers:"§8.2–8.4",title:b("2단계 — 원자성과 접근 제어","Step 2 — Atomicity and controlled access"),summary:b("임계 구역은 공유 상태에 대한 복합 동작을 원자적으로 만들고 조건부 임계 구역은 진입 조건까지 결합한다.","Critical regions make compound shared-state actions atomic; conditional critical regions also guard entry."),detail:b("상호 배제는 동시에 둘이 임계 구역에 있지 않다는 안전성이고, 교착 없음은 일부 프로세스가 계속 진행할 수 있다는 진행 성질이다. 하나가 다른 하나를 자동으로 보장하지 않는다.","Mutual exclusion is the safety property that two processes are never simultaneously in a critical region. Deadlock freedom is a progress property. Neither automatically implies the other."),checkpoint:b("두 락을 반대 순서로 잡는 프로그램은 상호 배제를 지키면서도 어떻게 교착하는가?", "How can opposite lock-acquisition orders preserve mutual exclusion yet deadlock?")},
      {id:"fairness",covers:"§8.5",title:b("3단계 — 가능한 실행에서 공정한 실행으로","Step 3 — From possible to fair executions"),summary:b("공정성은 영원히 기회가 있는 프로세스가 무한히 무시되지 않도록 스케줄을 제한한다.","Fairness restricts schedules so that a process with continuing opportunities is not ignored forever."),detail:b("약한 공정성과 강한 공정성은 '계속 활성'과 '무한히 자주 활성'을 다르게 다룬다. 공정성은 프로그램 코드가 아니라 스케줄 가정이므로 명세에 명시해야 한다.","Weak and strong fairness differ over continuously enabled versus infinitely often enabled actions. Fairness is an assumption about scheduling, not just program text, and must be stated in a specification."),checkpoint:b("어떤 명령이 무한히 자주 활성화되지만 매번 곧 비활성화된다면 약한 공정성만으로 실행이 보장되는가?", "If an action is enabled infinitely often but never continuously, does weak fairness guarantee it runs?")},
      {id:"traces",covers:"§8.6–8.8",title:b("4단계 — 환경 간섭을 포함한 합성적 흔적","Step 4 — Compositional traces with interference"),summary:b("전이 흔적은 프로그램 단계 사이의 상태 쌍을 기록하고 환경의 간섭을 조합 가능하게 만든다.","Transition traces record state pairs around program steps and make environmental interference compositional."),detail:b("stuttering은 관찰 가능한 변화가 없는 단계를 삽입하고, mumbling은 인접한 내부 단계를 합친다. 이 닫힘 조건은 구성요소 의미를 병렬 문맥에서도 안정적으로 조합하기 위한 추상화다.","Stuttering inserts a step with no observable change; mumbling combines adjacent internal steps. Closure under both abstractions makes component meanings stable and compositional in parallel contexts."),checkpoint:b("trace semantics이 최종 상태 집합보다 병렬 합성에 유리한 이유는?", "Why are traces more compositional for concurrency than sets of final states?")},
    ],
    quiz:[
      {question:b("상호 배제는 어떤 종류의 성질인가?","What kind of property is mutual exclusion?"),options:[b("안전성","Safety"),b("종료 시간","Runtime complexity"),b("syntax 성질","Syntax")],correct:0,explanation:b("나쁜 동시 진입 상태가 결코 일어나지 않음을 말한다.","It says a bad simultaneous-entry state never occurs.")},
      {question:b("공정성이 주로 제한하는 것은?","What does fairness primarily restrict?"),options:[b("변수 이름","Variable names"),b("스케줄","Schedules"),b("타입 constructor","Type constructors")],correct:1,explanation:b("가능한 인터리빙 중 부당한 기아 실행을 제외한다.","It excludes unfair starvation schedules from possible interleavings.")},
      {question:b("mumbling의 직관은?","What is the intuition behind mumbling?"),options:[b("인접 내부 단계를 한 단계로 추상화","Abstract adjacent internal steps as one"),b("무한 루프 삽입","Insert an infinite loop"),b("모든 상태 삭제","Delete all states")],correct:0,explanation:b("내부 세부 단계의 경계를 관찰 불가능한 것으로 본다.","It treats boundaries between internal detail steps as unobservable.")},
    ],
    bridge:b("공유 메모리를 제거하고 통신 사건 자체를 동기화 지점으로 삼으면 CSP 스타일의 메시지 전달 동시성으로 이동한다.","Removing shared memory and using communication events as synchronization points leads to CSP-style message-passing concurrency."),
  },
  {
    number:"09",slug:"communicating-sequential-processes",part:2,pages:"181–193",minutes:70,
    title:b("통신 순차 프로세스","Communicating Sequential Processes"),eyebrow:b("공유 상태 대신 동기식 메시지","Synchronous messages instead of shared state"),
    overview:b("프로세스가 채널의 동기식 입력·출력으로만 상호작용하는 CSP식 언어를 정의하고, 통신 전이·교착·공정성을 분석한다.","A CSP-like language lets processes interact only through synchronous channel input and output, enabling analysis of communication transitions, deadlock, and fairness."),
    goals:[b("동기식 rendezvous 규칙을 유도한다.","Derive the synchronous rendezvous rule."),b("통신 구조에서 교착 순환을 찾는다.","Find deadlock cycles in communication structure."),b("공유 변수와 메시지 전달의 관찰 모델을 비교한다.","Compare shared-variable and message-passing observation models.")],
    keyTerms:[b("CSP","communicating sequential processes"),b("랑데부","rendezvous"),b("채널","channel"),b("동기식 통신","synchronous communication"),b("통신 교착","communication deadlock")],
    steps:[
      {id:"syntax",covers:"§9.1",title:b("1단계 — 통신을 가드로 사용","Step 1 — Use communication as a guard"),summary:b("입력과 출력은 상대 프로세스가 맞는 동작을 준비했을 때만 함께 진행한다.","An input and output proceed together only when matching processes are both ready."),detail:b("프로세스는 로컬 상태를 갖고 채널 사건으로 동기화한다. 통신 가드를 가진 선택은 상대방의 준비 상태까지 활성 여부에 포함하므로 스케줄과 통신 가능성이 결합된다.","Processes have local state and synchronize through channel events. A communication-guarded choice is enabled only when a partner is ready, coupling scheduling with communication availability."),checkpoint:b("버퍼 없는 채널에서 출력 프로세스만 준비된 경우 왜 전이할 수 없는가?", "Why can no transition occur on an unbuffered channel when only the sender is ready?")},
      {id:"semantics",covers:"§9.2",title:b("2단계 — 두 로컬 단계를 하나의 통신 전이로","Step 2 — Fuse two local actions into one communication"),summary:b("한쪽의 `h!e`와 다른 쪽의 `h?v`가 만나면 값 전달과 수신 상태 갱신이 하나의 전체 전이가 된다.","Matching `h!e` and `h?v` actions combine into one global transition that transfers a value and updates the receiver."),detail:b("채널 이름과 방향이 맞아야 하고 표현식은 송신자 상태에서 평가된다. 개별 통신은 단독 전이가 없으며 병렬 구성 규칙이 상보적 동작을 동시에 소비한다.","Channel and direction must match, and the expression is evaluated in the sender's state. Neither communication has an independent step; the parallel rule consumes complementary actions together."),checkpoint:b("전달되는 값은 송신자 상태와 수신자 상태 중 어디에서 계산되어야 하는가?", "Should the transmitted value be evaluated in the sender's or receiver's state?")},
      {id:"examples",covers:"§9.3–9.4",title:b("3단계 — 프로토콜을 프로세스로 분해","Step 3 — Decompose protocols into processes"),summary:b("파이프라인, 필터, 중계 프로세스는 채널 토폴로지로 데이터 흐름과 동기화를 함께 표현한다.","Pipelines, filters, and relay processes use channel topology to express both dataflow and synchronization."),detail:b("가능한 제한은 채널 연결·입출력 방향·가드 형태를 단순화해 정적 분석을 돕는다. 예제는 작은 순차 구성요소가 통신 규약을 통해 전체 동작을 만든다는 점을 보여 준다.","Restrictions on connectivity, direction, and guarded forms simplify static analysis. The examples show how small sequential components combine through a protocol into global behavior."),checkpoint:b("파이프라인 중간 단계가 입력 후 출력을 기다릴 때 backpressure가 어떻게 생기는가?", "How does backpressure arise when a pipeline stage must output after receiving input?")},
      {id:"progress",covers:"§9.5–9.6",title:b("4단계 — 교착과 공정성 분리","Step 4 — Separate deadlock from fairness"),summary:b("교착은 맞물릴 통신이 전혀 없는 상태이고, 불공정성은 가능한 통신이 계속 선택되지 않는 실행이다.","Deadlock is a state with no matching communication; unfairness is an execution that repeatedly ignores an available communication."),detail:b("대기 그래프의 순환은 교착 후보를 드러내지만 모든 순환이 실제 교착인 것은 아니다. 공정성은 가능한 rendezvous의 장기 선택에 대한 추가 가정이다.","Cycles in a wait-for graph expose deadlock candidates, though not every cycle is an actual deadlock. Fairness is an additional assumption about the long-run selection of possible rendezvous events."),checkpoint:b("가능한 통신이 하나 있는데 다른 통신만 무한히 선택되는 경우는 교착인가 기아인가?", "If one communication remains possible but others are chosen forever, is that deadlock or starvation?")},
    ],
    quiz:[
      {question:b("동기식 채널 출력이 완료되는 시점은?","When does a synchronous channel output complete?"),options:[b("송신자가 값을 계산한 즉시","As soon as the sender computes the value"),b("맞는 수신자가 동시에 참여할 때","When a matching receiver participates"),b("타이머가 끝날 때","When a timer expires")],correct:1,explanation:b("rendezvous는 송수신 양쪽의 공동 전이다.","A rendezvous is a joint sender-receiver transition.")},
      {question:b("CSP에서 주된 동기화 수단은?","What is the main synchronization mechanism in CSP?"),options:[b("공유 변수 잠금","Shared-variable locks"),b("채널 통신","Channel communication"),b("타입 추론","Type inference")],correct:1,explanation:b("통신 사건이 데이터 전달과 동기화를 동시에 수행한다.","Communication events transfer data and synchronize at once.")},
      {question:b("교착과 기아의 차이는?","How do deadlock and starvation differ?"),options:[b("교착은 진행 가능한 전이가 없고, 기아는 있지만 특정 참여자가 계속 제외됨","Deadlock has no possible progress; starvation has progress but indefinitely excludes a participant"),b("둘은 완전히 같다","They are identical"),b("기아는 syntax error다","Starvation is a syntax error")],correct:0,explanation:b("시스템 전체의 정지와 개별 진행의 부재를 구분한다.","It separates global inability to move from individual lack of progress.")},
    ],
    bridge:b("명령형 계산과 동시성을 마친 뒤, 책은 상태를 없애고 함수 적용과 치환만으로 계산을 설명하는 람다 계산으로 전환한다.","After imperative computation and concurrency, the book removes state and turns to the lambda calculus, where application and substitution explain computation."),
  },
  {
    number:"10",slug:"lambda-calculus",part:3,pages:"194–221",minutes:105,
    title:b("람다 계산","The Lambda Calculus"),eyebrow:b("함수, 치환, 평가 전략의 핵심","Functions, substitution, and evaluation strategy"),
    overview:b("순수한 비타입 람다 계산의 syntax과 β-축약을 정의하고 정상 순서·적극 평가·표시적 의미·함수형 프로그래밍 인코딩을 연결한다.","The pure untyped lambda calculus is developed through syntax, beta-reduction, normal-order and eager evaluation, denotational semantics, and functional encodings."),
    goals:[b("α-동치와 캡처 회피 β-축약을 수행한다.","Perform alpha-equivalence and capture-avoiding beta-reduction."),b("정상 순서와 적극 평가의 종료 차이를 예측한다.","Predict termination differences between normal-order and eager evaluation."),b("함수·불리언·자연수 인코딩의 동작을 추적한다.","Trace encodings of functions, Booleans, and natural numbers.")],
    keyTerms:[b("람다 추상화","lambda abstraction"),b("β-축약","beta-reduction"),b("정상 순서","normal order"),b("적극 평가","eager evaluation"),b("고정점 결합자","fixed-point combinator")],
    steps:[
      {id:"syntax",covers:"§10.1–10.2",title:b("1단계 — 바인더가 있는 최소 언어","Step 1 — A minimal language with binding"),summary:b("변수, 추상화 `λx.e`, 적용 `e₀ e₁`만으로 계산 언어를 만든다.","Variables, abstractions `λx.e`, and applications `e₀ e₁` form a complete computational language."),detail:b("β-축약 `(λx.e) a → e[x↦a]`는 함수 호출을 치환으로 설명한다. 치환은 1장의 규율대로 캡처를 피해야 하며, α-동치인 바인더 이름 차이는 계산 의미가 없다.","Beta-reduction `(λx.e) a → e[x↦a]` explains calls by substitution. The substitution must avoid capture as in Chapter 1, while alpha-equivalent binder names are computationally irrelevant."),checkpoint:b("`(λx. λy. x) y`를 안전하게 한 단계 축약하라.", "Reduce `(λx. λy. x) y` safely by one beta step."),notation:"(λx.e) a →β e[x ↦ a]"},
      {id:"normal",covers:"§10.3",title:b("2단계 — 가장 바깥부터: 정상 순서","Step 2 — Outermost first: normal order"),summary:b("정상 순서는 가장 왼쪽의 바깥 redex를 먼저 줄이며, 정상형이 존재하면 찾아낸다.","Normal order reduces the leftmost outermost redex and finds a normal form whenever one exists."),detail:b("사용되지 않는 인수는 평가하지 않으므로 발산하는 인수를 무시할 수 있다. 대신 같은 인수가 여러 번 사용되면 같은 계산을 반복할 수 있어 call-by-name과 lazy evaluation의 차이가 생긴다.","Unused arguments are not evaluated, so a diverging argument may be ignored. But a used argument can be recomputed, motivating the distinction between call-by-name and lazy evaluation."),checkpoint:b("`(λx.1) Ω`가 정상 순서에서는 끝나는 이유는?", "Why does `(λx.1) Ω` terminate under normal order?")},
      {id:"eager",covers:"§10.4",title:b("3단계 — 인수부터: 적극 평가","Step 3 — Arguments first: eager evaluation"),summary:b("적극 평가는 적용 전에 연산자와 인수를 값으로 만들며 현대 엄격 함수형 언어의 핵심 전략이다.","Eager evaluation evaluates operator and operand to values before application, matching strict functional languages."),detail:b("인수를 한 번 평가해 재사용하기 쉽지만 사용하지 않는 인수도 평가한다. 따라서 β-동치만으로 같은 두 식이 특정 평가 전략에서 같은 종료 행동을 보인다고 결론 내리면 안 된다.","It naturally evaluates an argument once for reuse but also evaluates unused arguments. Beta-convertibility alone does not guarantee identical termination behavior under a chosen strategy."),checkpoint:b("적극 평가에서 `Ω`가 인수로 나타나면 함수 본문이 x를 쓰지 않아도 어떤 일이 일어나는가?", "Under eager evaluation, what happens when `Ω` is an argument even if the body never uses x?")},
      {id:"denotation-programming",covers:"§10.5–10.6",title:b("4단계 — 자기 적용을 의미와 프로그램으로","Step 4 — Give self-application meaning and use it for programs"),summary:b("람다 항의 의미에는 함수 공간과 값 공간이 재귀적으로 맞물리는 도메인이 필요하다.","Giving lambda terms denotations requires a domain tied recursively to its own function space."),detail:b("재귀 도메인과 최소 고정점으로 재귀 함수를 해석한다. Church식 불리언·쌍·자연수는 데이터가 그 소비 방식인 함수로 표현될 수 있음을 보여 주지만, 평가 전략에 따라 인코딩의 실용성이 달라진다.","Recursive domains and least fixed points interpret recursion. Church-style Booleans, pairs, and naturals show that data can be represented by its eliminators, though usefulness depends on evaluation strategy."),checkpoint:b("Church 불리언이 값을 저장하기보다 두 선택지 중 하나를 고르는 함수라는 설명을 해 보라.", "Explain how a Church Boolean is a function choosing between two alternatives rather than stored data.")},
    ],
    quiz:[
      {question:b("β-축약의 본질은?","What is the essence of beta-reduction?"),options:[b("함수 본문에 인수를 캡처 없이 치환","Capture-avoiding substitution of an argument into a function body"),b("변수 타입을 삭제","Delete variable types"),b("메모리를 할당","Allocate memory")],correct:0,explanation:b("람다 계산에서 함수 호출은 치환으로 계산된다.","Function application computes by substitution in lambda calculus.")},
      {question:b("정상형이 존재할 때 그것을 찾는 전략은?","Which strategy finds a normal form whenever one exists?"),options:[b("정상 순서","Normal order"),b("항상 적극 평가","Always eager evaluation"),b("무작위 축약","Random reduction")],correct:0,explanation:b("정상 순서 정리가 이 성질을 준다.","The normal-order theorem provides this property.")},
      {question:b("`(λx.1) Ω`의 적극 평가 결과는?","What happens to `(λx.1) Ω` under eager evaluation?"),options:[b("즉시 1","Immediately 1"),b("Ω 평가 때문에 발산","It diverges while evaluating Ω"),b("syntax error","Syntax error")],correct:1,explanation:b("적극 평가는 사용 여부와 무관하게 인수를 먼저 평가한다.","Eager evaluation evaluates the argument first even when unused.")},
    ],
    bridge:b("순수 계산 핵심을 얻었으니, 다음 장은 이를 concrete syntax·패턴·재귀·리스트를 갖춘 실용적 적극 함수형 언어로 확장한다.","With the pure core established, the next chapter grows it into a practical eager functional language with concrete syntax, patterns, recursion, and lists."),
  },
];
