import { b, type StudyUnit } from "./types";

export const units11to15: StudyUnit[] = [
  {
    number:"11",slug:"eager-functional-language",part:3,pages:"222–250",minutes:100,
    title:b("적극 함수형 언어","An Eager Functional Language"),eyebrow:b("람다 핵심에서 패턴·재귀·자료구조로","From lambda core to patterns, recursion, and data"),
    overview:b("엄격 평가 함수형 언어를 구체 구문과 평가 판단으로 정의하고, 정의·패턴·재귀·리스트·트리·직접 의미론·동적 바인딩을 살핀다.","A strict functional language is defined with concrete syntax and evaluation judgments, then extended with definitions, patterns, recursion, lists, trees, direct semantics, and dynamic binding."),
    goals:[b("큰 단계 평가 유도를 구성한다.","Construct big-step evaluation derivations."),b("패턴 매칭과 재귀 정의의 환경 효과를 설명한다.","Explain the environment effects of pattern matching and recursive definitions."),b("정적 바인딩과 동적 바인딩을 반례로 구분한다.","Distinguish static and dynamic binding with a counterexample.")],
    keyTerms:[b("평가 의미론","evaluation semantics"),b("클로저","closure"),b("패턴 매칭","pattern matching"),b("재귀 환경","recursive environment"),b("동적 바인딩","dynamic binding")],
    steps:[
      {id:"evaluation",covers:"§11.1–11.2",title:b("1단계 — 구체 프로그램에서 값까지","Step 1 — From concrete programs to values"),summary:b("큰 단계 판단은 환경에서 표현식이 어떤 값으로 평가되는지를 한 번에 연결한다.","A big-step judgment relates an expression in an environment directly to its resulting value."),detail:b("적용은 연산자를 클로저로, 인수를 값으로 평가한 뒤 클로저가 저장한 정의 환경을 매개변수 바인딩으로 확장한다. 이 저장된 환경이 정적 범위를 구현한다.","Application evaluates the operator to a closure and the operand to a value, then extends the closure's saved definition environment with the parameter. The saved environment implements lexical scope."),checkpoint:b("클로저에 코드뿐 아니라 환경이 필요한 예를 하나 들어라.","Give an example showing why a closure needs an environment in addition to code."),notation:"ρ ⊢ e ⇓ v"},
      {id:"definitions",covers:"§11.3",title:b("2단계 — 정의, 패턴, 재귀의 매듭","Step 2 — Definitions, patterns, and the recursive knot"),summary:b("패턴은 값을 여러 바인딩으로 분해하고, 재귀 정의는 함수가 자신을 포함한 환경을 보게 한다.","Patterns decompose a value into bindings, while recursive definitions let a function see an environment containing itself."),detail:b("비재귀 정의는 우변을 먼저 평가한 뒤 환경을 확장한다. 재귀 정의는 클로저와 환경을 상호 참조하도록 고정점을 묶어야 하며, 실패하는 패턴은 평가 결과나 선택 규칙에 영향을 준다.","A nonrecursive definition evaluates its right side before extending the environment. A recursive definition ties a fixed-point knot between closure and environment; pattern failure affects evaluation or branch selection."),checkpoint:b("재귀 함수의 클로저가 함수 이름 바인딩 전에 만들어지면 왜 자기 호출이 실패하는가?", "Why would self-calls fail if a recursive closure were created before binding the function name?")},
      {id:"data",covers:"§11.4–11.5",title:b("3단계 — 리스트와 트리로 재귀 연습","Step 3 — Practice recursion over lists and trees"),summary:b("생성자와 패턴이 대수적 자료를 만들고 구조적 재귀가 그 자료를 소비한다.","Constructors and patterns build algebraic data, and structural recursion consumes it."),detail:b("map, reduce, append와 트리 순회는 기본 사례다. 종료 논증은 입력 자료의 구조가 작아지는지 확인하고, 축약 순서가 결합 법칙이나 결과에 미치는 영향도 구분한다.","Map, reduce, append, and tree traversals are central examples. Termination follows when recursive calls consume structurally smaller data; fold direction can affect association and results."),checkpoint:b("리스트 재귀에서 길이가 자연스러운 변량이 되는 이유는?", "Why is list length a natural variant for structural recursion?")},
      {id:"scope",covers:"§11.6–11.7",title:b("4단계 — 직접 의미론과 바인딩 규율","Step 4 — Direct semantics and binding discipline"),summary:b("직접 표시적 의미론은 평가 규칙과 같은 결과를 함수로 주며, 동적 바인딩은 호출 환경에서 자유 변수를 찾는다.","Direct denotational semantics gives the same outcomes as functions; dynamic binding resolves free variables in the caller's environment."),detail:b("정적 바인딩은 이름변경과 지역 추론을 안정적으로 보존하지만, 동적 바인딩은 호출 경로가 자유 변수의 의미를 바꾼다. 그래서 단순한 α-이름변경조차 동작을 바꿀 수 있다.","Lexical binding preserves renaming and local reasoning; dynamic binding lets the call path change the meaning of free variables. Even alpha-renaming can then change behavior."),checkpoint:b("정의 위치와 호출 위치에서 x 값이 다를 때 두 바인딩 전략의 결과를 비교하라.", "Compare lexical and dynamic scope when x differs at definition and call sites.")},
    ],
    quiz:[
      {question:b("클로저가 저장하는 것은?","What does a closure store?"),options:[b("함수 코드와 정의 환경","Function code and its definition environment"),b("최종 출력만","Only the final output"),b("호출 횟수만","Only a call count")],correct:0,explanation:b("자유 변수의 정적 바인딩을 보존한다.","It preserves lexical bindings of free variables.")},
      {question:b("큰 단계 의미론의 특징은?","What characterizes big-step semantics?"),options:[b("모든 중간 한 단계를 명시","It lists every intermediate step"),b("표현식과 최종 값을 직접 연결","It directly relates an expression to its result"),b("타입만 계산","It computes only types")],correct:1,explanation:b("중간 전이를 추상화하고 최종 평가 관계를 정의한다.","It abstracts intermediate transitions into a direct evaluation relation.")},
      {question:b("동적 바인딩에서 자유 변수는 어디서 해석되는가?","Where is a free variable resolved under dynamic binding?"),options:[b("함수 정의 환경","The function's definition environment"),b("현재 호출 환경","The current calling environment"),b("전역 타입 표","A global type table")],correct:1,explanation:b("호출 경로가 이름의 의미에 영향을 준다.","The call path affects the name's meaning.")},
    ],
    bridge:b("함수 호출 뒤의 계산을 값처럼 조작하려면 평가기를 계속 전달 방식으로 바꿔야 한다. 이것이 다음 장의 주제다.","To manipulate what happens after a call as a value, the evaluator is transformed into continuation-passing form."),
  },
  {
    number:"12",slug:"functional-continuations",part:3,pages:"251–272",minutes:95,
    title:b("함수형 언어의 계속","Continuations in a Functional Language"),eyebrow:b("제어 문맥을 값과 기계로 바꾸기","Turning control context into values and machines"),
    overview:b("함수형 평가를 CPS로 바꾸고 계속을 일급 값으로 노출한 뒤, defunctionalization을 통해 일차 의미론과 추상 기계를 유도한다.","Functional evaluation is transformed into CPS, continuations are exposed as first-class values, and defunctionalization derives a first-order semantics and abstract machine."),
    goals:[b("직접 스타일 평가 규칙을 CPS로 변환한다.","Transform direct-style evaluation rules into CPS."),b("callcc/throw의 비지역 제어를 추적한다.","Trace nonlocal control with callcc/throw."),b("고차 계속을 일차 프레임 자료형으로 defunctionalize한다.","Defunctionalize higher-order continuations into a first-order frame datatype.")],
    keyTerms:[b("계속 전달 방식","continuation-passing style"),b("일급 계속","first-class continuation"),b("call/cc","call/cc"),b("비지역 탈출","nonlocal exit"),b("비함수화","defunctionalization")],
    steps:[
      {id:"cps",covers:"§12.1",title:b("1단계 — 모든 결과를 계속에 넘기기","Step 1 — Send every result to a continuation"),summary:b("평가기는 값을 반환하는 대신 그 값을 받을 함수 k를 호출한다.","Instead of returning a value, the evaluator calls a function k that receives the value."),detail:b("적용에서는 연산자 평가 계속 안에 인수 평가 계속을 넣고, 그 안에서 함수 본문을 평가한다. 이 중첩이 제어 순서를 데이터 흐름으로 명시한다.","For application, the operand continuation is nested inside the operator continuation, and body evaluation inside that. The nesting makes control order explicit as dataflow."),checkpoint:b("`f a`의 적극 평가에서 f, a, 본문 순서를 세 개의 중첩 계속으로 써 보라.", "Write the eager order f, a, body as three nested continuations."),notation:"eval(e, ρ, k)  where  k : Value → Answer"},
      {id:"first-class",covers:"§12.2–12.3",title:b("2단계 — 현재 미래를 캡처하기","Step 2 — Capture the current future"),summary:b("callcc는 현재 계속을 값으로 넘기고 throw는 현재 문맥을 버린 채 저장된 계속으로 이동한다.","callcc passes the current continuation as a value; throw discards the current context and resumes a saved continuation."),detail:b("이 기능으로 조기 반환, 깊은 탐색 탈출, 코루틴 같은 제어 패턴을 라이브러리 수준에서 표현할 수 있다. 저장된 계속이 어느 상태·자원과 함께 재사용되는지는 효과 설계의 핵심 경계다.","This expresses early return, deep search escape, and coroutine-like control patterns at library level. Whether a saved continuation can be reused with state and resources is a key effect boundary."),checkpoint:b("throw가 호출 지점의 남은 계산을 실행하지 않는 이유를 계속 관점에서 설명하라.", "Explain in continuation terms why throw does not execute the remaining computation at its call site.")},
      {id:"defunctionalize",covers:"§12.4–12.5",title:b("3단계 — 함수를 프레임 자료형으로","Step 3 — Replace functions by frame data"),summary:b("평가기에서 실제로 만들어지는 계속 함수의 모양은 유한하므로 태그된 프레임 자료형으로 바꿀 수 있다.","Only finitely many continuation-function shapes arise in the evaluator, so they can be replaced by a tagged frame datatype."),detail:b("각 람다 계속을 생성자와 저장 필드로 바꾸고, 하나의 apply-cont 함수가 태그를 해석한다. 고차 정의가 스택을 명시적으로 다루는 일차 인터프리터 또는 추상 기계가 된다.","Replace each continuation lambda by a constructor with saved fields, and interpret tags in one apply-cont function. The higher-order evaluator becomes a first-order interpreter or abstract machine with an explicit stack."),checkpoint:b("함수 적용 평가에서 '연산자 결과 대기' 프레임이 저장해야 할 정보는?", "What must an 'awaiting operator result' frame store while evaluating an application?")},
      {id:"correspondence",covers:"§12.6",title:b("4단계 — 두 의미론의 상태 대응","Step 4 — Relate the two semantics by state correspondence"),summary:b("CPS 상태와 일차 기계 상태 사이의 표현 관계를 세우면 두 평가기가 같은 답을 냄을 보일 수 있다.","A representation relation between CPS states and machine states proves that both evaluators produce the same answers."),detail:b("한쪽의 함수 계속을 다른 쪽의 프레임 목록으로 읽고 각 전이 또는 호출이 대응함을 보인다. 이는 구현 유도가 단순한 직관이 아니라 의미 보존 변환임을 확립한다.","Interpret a functional continuation as a frame list and show corresponding calls or transitions. This establishes the implementation derivation as a semantics-preserving transformation rather than intuition."),checkpoint:b("시뮬레이션 관계가 보존되어야 하는 한 단계 조건을 말하라.", "State the one-step preservation condition required of a simulation relation.")},
    ],
    quiz:[
      {question:b("CPS 함수가 추가로 받는 인수는?","What extra argument does a CPS function receive?"),options:[b("계속","A continuation"),b("타입 증명","A type proof"),b("파일 이름","A filename")],correct:0,explanation:b("결과를 어디에 전달할지를 명시한다.","It states where the result should go.")},
      {question:b("defunctionalization의 결과는?","What does defunctionalization produce?"),options:[b("고차 함수 대신 태그된 자료와 apply 함수","Tagged data and an apply function instead of higher-order functions"),b("모든 함수를 인라인","Inline every function"),b("타입을 제거","Remove all types")],correct:0,explanation:b("계속을 명시적 스택 프레임으로 바꾼다.","It turns continuations into explicit stack frames.")},
      {question:b("throw의 동작은?","What does throw do?"),options:[b("현재 계속을 이어서 실행","Continue with the current continuation"),b("현재 계속을 버리고 지정된 계속을 재개","Discard the current continuation and resume a specified one"),b("프로그램을 항상 종료","Always terminate the program")],correct:1,explanation:b("비지역 제어 이동의 핵심이다.","That is the essence of nonlocal control transfer.")},
    ],
    bridge:b("계속 기계를 얻었으니, 다음 장은 여기에 저장소와 참조를 결합해 함수형·명령형 효과를 한 언어에서 다룬다.","With the continuation machine in hand, the next chapter combines it with a store and references to support functional and imperative effects together."),
  },
  {
    number:"13",slug:"iswim-like-languages",part:3,pages:"273–297",minutes:110,
    title:b("ISWIM 계열 언어","Iswim-like Languages"),eyebrow:b("클로저, 저장소, 제어 효과의 결합","Combining closures, stores, and control effects"),
    overview:b("적극 함수형 언어에 참조와 상태를 더해 별칭을 모델링하고, CPS·일차 기계 위에서 예외·백트래킹·입출력을 통합한다.","References and state are added to the eager functional language, modeling aliasing and integrating exceptions, backtracking, and I/O in CPS and a first-order machine."),
    goals:[b("환경과 저장소의 역할을 분리한다.","Separate the roles of environment and store."),b("참조 별칭이 관찰 가능한 이유를 설명한다.","Explain why reference aliasing is observable."),b("예외·백트래킹·I/O를 계속 조작으로 연결한다.","Connect exceptions, backtracking, and I/O to continuation manipulation.")],
    keyTerms:[b("위치","location"),b("참조","reference"),b("저장소","store"),b("별칭","aliasing"),b("예외 처리기","exception handler"),b("백트래킹","backtracking")],
    steps:[
      {id:"store",covers:"§13.1–13.2",title:b("1단계 — 환경은 위치를, 저장소는 값을","Step 1 — Environments name locations; stores hold values"),summary:b("변수 바인딩과 변경 가능한 셀을 분리하면 참조 생성·읽기·쓰기를 정확히 모델링할 수 있다.","Separating variable bindings from mutable cells precisely models reference allocation, dereference, and assignment."),detail:b("환경 ρ는 이름을 값이나 위치에 연결하고 저장소 μ는 위치를 현재 값에 연결한다. 새 참조는 신선한 위치를 할당하고, 같은 위치를 가리키는 두 참조는 별칭이 되어 한쪽 쓰기가 다른 쪽 읽기에 보인다.","Environment ρ maps names to values or locations; store μ maps locations to current values. Allocation chooses a fresh location, and two references to one location alias, so a write through one is visible through the other."),checkpoint:b("두 참조가 같은 값을 담는 것과 같은 위치를 가리키는 것의 차이는?", "What is the difference between two references containing equal values and pointing to the same location?"),notation:"ρ : Name → Value    μ : Location → Value"},
      {id:"machines",covers:"§13.3–13.5",title:b("2단계 — 상태를 CPS와 기계에 통과시키기","Step 2 — Thread state through CPS and the machine"),summary:b("각 평가 단계는 값뿐 아니라 갱신된 저장소를 계속에 넘긴다.","Every evaluation step passes both a value and an updated store to its continuation."),detail:b("CPS는 제어 흐름을, 저장소 매개변수는 효과 순서를 명시한다. 비함수화하면 제어 스택과 저장소를 가진 CEK류 일차 기계가 되며 구현의 평가 순서가 노출된다.","CPS makes control flow explicit while a store parameter makes effect order explicit. Defunctionalization yields a CEK-like first-order machine with control stack and store, exposing implementation order."),checkpoint:b("두 피연산자가 모두 참조를 수정할 수 있을 때 평가 순서가 의미에 영향을 주는 이유는?", "Why does operand evaluation order matter when both operands can mutate references?")},
      {id:"effects",covers:"§13.6–13.9",title:b("3단계 — 제어 효과를 계속로 통일","Step 3 — Unify control effects with continuations"),summary:b("예외는 실패 계속, 백트래킹은 대안 계속, 입출력은 외부 응답 뒤의 계속으로 볼 수 있다.","Exceptions use failure continuations, backtracking stores alternative continuations, and I/O retains continuations after external responses."),detail:b("정상 계속과 처리기 계속을 분리하면 throw가 가장 가까운 처리기로 이동한다. 백트래킹은 상태 복원 정책까지 필요하며, 입출력은 5장의 재개 관점과 현재 추상 기계를 연결한다.","Separating normal and handler continuations sends a throw to the nearest handler. Backtracking also needs a store-restoration policy, while I/O connects this machine to Chapter 5's resumption view."),checkpoint:b("백트래킹 시 제어만 되돌리고 저장소를 복원하지 않으면 어떤 의미 변화가 생기는가?", "How does meaning change if backtracking restores control but not the store?")},
      {id:"boundaries",covers:"§13.10",title:b("4단계 — 효과의 상호작용 경계 찾기","Step 4 — Find effect-interaction boundaries"),summary:b("계속과 상태를 함께 쓸 때 캡처·복원·중복 실행 정책이 명시되지 않으면 의미가 모호해진다.","Combining continuations and state is ambiguous unless capture, restoration, and repeated-use policies are explicit."),detail:b("일급 계속을 여러 번 호출할 수 있는지, 호출 시 저장소가 캡처 시점으로 돌아가는지, 입출력이 반복되는지에 따라 언어가 크게 달라진다. 효과를 독립적으로 설계한 뒤 단순 결합할 수 없다는 교훈이다.","Whether a first-class continuation is reusable, restores the captured store, or repeats I/O radically changes the language. Effects cannot always be designed independently and then naively combined."),checkpoint:b("이미 출력한 뒤 캡처된 계속을 다시 실행할 때 출력을 반복할지 정책이 필요한 이유는?", "Why must a language specify whether invoking a captured continuation repeats prior output?")},
    ],
    quiz:[
      {question:b("저장소가 나타내는 것은?","What does the store represent?"),options:[b("이름의 철자","Name spelling"),b("위치의 현재 값","Current values of locations"),b("타입 규칙 목록","A list of typing rules")],correct:1,explanation:b("변경 가능성은 위치에서 값으로 가는 저장소를 갱신한다.","Mutation updates the location-to-value store.")},
      {question:b("별칭의 조건은?","When do references alias?"),options:[b("값이 우연히 같을 때","Whenever values happen to be equal"),b("같은 위치를 가리킬 때","When they point to the same location"),b("이름 길이가 같을 때","When names have equal length")],correct:1,explanation:b("공유 위치 때문에 한쪽의 쓰기가 다른 쪽에서 관찰된다.","A shared location makes writes through one reference visible through the other.")},
      {question:b("예외를 CPS로 모델링할 때 유용한 구조는?","What CPS structure is useful for exceptions?"),options:[b("정상 계속과 예외 계속","Normal and exception continuations"),b("두 개의 파서","Two parsers"),b("무한 타입","An infinite type")],correct:0,explanation:b("정상 반환과 비지역 처리기 이동을 분리한다.","It separates normal return from nonlocal transfer to a handler.")},
    ],
    bridge:b("상태가 있는 적극 언어와 대조하기 위해 다음 장은 정상 순서 언어로 돌아가 call-by-name과 공유하는 lazy evaluation을 구분한다.","For contrast with stateful eager evaluation, the next chapter returns to normal order and distinguishes call-by-name from sharing-based lazy evaluation."),
  },
  {
    number:"14",slug:"normal-order-language",part:3,pages:"298–314",minutes:80,
    title:b("정상 순서 언어","A Normal-Order Language"),eyebrow:b("필요할 때 계산하고 결과를 공유하기","Compute on demand and share results"),
    overview:b("정상 순서 함수형 언어의 평가 규칙과 직접 의미를 정의하고, 축약과의 관계 및 lazy evaluation의 공유 구현을 설명한다.","A normal-order functional language is defined by evaluation rules and direct semantics, related to reduction, and implemented with sharing through lazy evaluation."),
    goals:[b("call-by-name 평가 규칙을 적극 평가와 비교한다.","Compare call-by-name rules with eager evaluation."),b("무한 리스트가 유한 관찰을 제공하는 방식을 설명한다.","Explain how infinite lists support finite observations."),b("thunk의 지연·강제·메모화를 추적한다.","Trace thunk delay, forcing, and memoization.")],
    keyTerms:[b("이름에 의한 호출","call-by-name"),b("지연 평가","lazy evaluation"),b("썽크","thunk"),b("강제","forcing"),b("메모화","memoization"),b("무한 리스트","infinite list")],
    steps:[
      {id:"evaluation",covers:"§14.1–14.2",title:b("1단계 — 인수를 값이 아닌 식으로 전달","Step 1 — Pass arguments as expressions, not values"),summary:b("함수 적용은 인수를 먼저 평가하지 않고 본문에서 필요할 때 정의 환경과 함께 평가한다.","Function application does not evaluate the argument first; it evaluates it on demand in the body with its environment."),detail:b("매개변수 바인딩은 값 대신 썽크와 비슷한 `(식,환경)`을 저장한다. 이 때문에 사용되지 않는 인수의 발산과 효과를 피하지만, 순수하지 않은 효과와 결합할 때 의미 정책이 복잡해진다.","A parameter binding stores an expression-environment pair rather than a value. This avoids divergence and effects of unused arguments, but interaction with impure effects requires careful policy."),checkpoint:b("적극 평가와 정상 순서에서 인수 평가 시점을 각각 말하라.", "State when arguments are evaluated in eager versus normal-order evaluation.")},
      {id:"examples",covers:"§14.3",title:b("2단계 — 무한 자료를 유한하게 관찰","Step 2 — Observe infinite data finitely"),summary:b("리스트의 꼬리를 필요할 때만 계산하면 무한 리스트에서도 앞의 유한 부분을 얻을 수 있다.","Computing a list tail only when demanded lets programs obtain finite prefixes of infinite lists."),detail:b("생산자와 소비자를 분리해도 소비자가 요구한 만큼만 생산한다. short-circuit, 무한 수열, 생성기 파이프라인은 이 수요 주도 평가의 대표 사례다.","Producer and consumer can be separated while only demanded elements are produced. Short-circuiting, infinite sequences, and generator pipelines exemplify demand-driven evaluation."),checkpoint:b("무한 자연수 리스트에서 처음 10개만 취하는 계산이 종료하는 조건은?", "Under what conditions does taking the first 10 values of an infinite natural-number list terminate?")},
      {id:"semantics",covers:"§14.4–14.5",title:b("3단계 — 직접 의미와 축약 연결","Step 3 — Relate direct semantics and reduction"),summary:b("환경 기반 평가와 치환 기반 정상 축약이 같은 관찰 결과를 준다는 대응을 세운다.","Environment-based evaluation is related to substitution-based normal reduction through their common observable results."),detail:b("직접 의미론에서는 함수가 인수 의미를 지연된 방식으로 받는다. 축약 관점은 구문 변환을, 평가 의미는 구현 가능한 환경 조작을 강조하므로 두 설명의 일치가 중요하다.","Direct semantics lets functions receive argument meanings non-strictly. Reduction emphasizes syntax transformation; evaluation semantics emphasizes implementable environment manipulation, making their agreement important."),checkpoint:b("치환 기반 의미론과 환경 기반 의미론이 각각 피하는 비용은 무엇인가?", "What cost does substitution-based versus environment-based semantics avoid?")},
      {id:"lazy",covers:"§14.6",title:b("4단계 — call-by-need로 중복 계산 제거","Step 4 — Eliminate recomputation with call-by-need"),summary:b("lazy evaluation은 썽크를 처음 강제할 때 계산하고 결과로 셀을 갱신해 이후 사용이 공유되게 한다.","Lazy evaluation computes a thunk on first force, updates its cell with the result, and shares that result on later uses."),detail:b("call-by-name과 종료 행동은 비슷하지만 계산량은 크게 다를 수 있다. 메모화에는 변경 가능한 셀이 필요하므로 순수 언어 구현 안에서 제한된 상태 효과가 사용된다.","Call-by-name and call-by-need have similar termination behavior but can differ greatly in work. Memoization uses mutable cells internally, a disciplined state effect implementing a pure language."),checkpoint:b("인수가 본문에 세 번 나타날 때 call-by-name과 call-by-need의 평가 횟수를 비교하라.", "Compare argument evaluation counts under call-by-name and call-by-need when the parameter occurs three times.")},
    ],
    quiz:[
      {question:b("lazy evaluation이 call-by-name에 추가하는 핵심은?","What does lazy evaluation add to call-by-name?"),options:[b("결과 공유/메모화","Sharing and memoization"),b("모든 인수 선평가","Eager evaluation of all arguments"),b("동적 바인딩","Dynamic binding")],correct:0,explanation:b("한번 강제한 썽크의 결과를 재사용한다.","A forced thunk's result is reused.")},
      {question:b("무한 리스트를 다룰 수 있는 이유는?","Why can infinite lists be useful?"),options:[b("전체를 먼저 생성해서","Because the entire list is generated first"),b("소비자가 요구한 유한 부분만 평가해서","Because only the finite demanded portion is evaluated"),b("리스트가 실제로 유한해서","Because the list is secretly finite")],correct:1,explanation:b("비엄격성은 관찰에 필요한 부분만 계산한다.","Non-strictness computes only what observation demands.")},
      {question:b("썽크에 보통 들어가는 것은?","What does a thunk typically contain?"),options:[b("지연된 식과 그 환경","A delayed expression and its environment"),b("완료된 출력 파일","A completed output file"),b("타입 오류","A type error")],correct:0,explanation:b("나중 평가 시 자유 변수의 바인딩을 보존해야 한다.","The environment preserves free-variable bindings for later evaluation.")},
    ],
    bridge:b("평가 전략을 이해했으니, 다음에는 어떤 식이 어떤 종류의 값을 낼 수 있는지 실행 전에 판단하는 단순 타입 체계를 세운다.","With evaluation strategies understood, the next chapter builds a simple type system that predicts what kind of value an expression can produce before execution."),
  },
  {
    number:"15",slug:"simple-type-system",part:4,pages:"315–348",minutes:120,
    title:b("단순 타입 체계","The Simple Type System"),eyebrow:b("판단, 건전성, 타입의 두 관점","Judgments, soundness, and two views of types"),
    overview:b("타입 문맥과 추론 규칙으로 단순 타입 람다 계산을 만들고, 명시적 타입·외재적/내재적 의미·집합론적 의미·재귀 타입을 비교한다.","Typing contexts and inference rules define the simply typed lambda calculus, followed by explicit types, extrinsic and intrinsic semantics, set-theoretic semantics, and recursive types."),
    goals:[b("타입 판단 Γ⊢e:τ를 유도한다.","Derive typing judgments Γ⊢e:τ."),b("진행·보존 관점의 타입 안전성을 설명한다.","Explain type safety through progress and preservation."),b("외재적·내재적 타입 의미를 비교한다.","Compare extrinsic and intrinsic meanings of types.")],
    keyTerms:[b("타입 문맥","typing context"),b("타입 판단","typing judgment"),b("보존","preservation"),b("진행","progress"),b("외재적 의미","extrinsic semantics"),b("내재적 의미","intrinsic semantics"),b("재귀 타입","recursive type")],
    steps:[
      {id:"judgments",covers:"§15.1–15.2",title:b("1단계 — 타입을 판단으로 말하기","Step 1 — State types as judgments"),summary:b("`Γ ⊢ e : τ`는 문맥 Γ의 가정 아래 e가 타입 τ를 가진다는 유도 가능한 주장이다.","`Γ ⊢ e : τ` is a derivable claim that e has type τ under assumptions Γ."),detail:b("변수 규칙은 문맥을 조회하고, 추상화는 매개변수 가정을 추가하며, 적용은 연산자가 `τ→τ′`, 인수가 τ인지 맞춘다. 타입 유도 트리는 구문 트리를 따라 국소 제약을 조합한다.","The variable rule consults Γ, abstraction adds a parameter assumption, and application matches an operator of `τ→τ′` with an operand of τ. A typing derivation combines local constraints along the syntax tree."),checkpoint:b("`λx. x`에 가능한 단순 타입의 일반 모양은?", "What is the general simple type shape of `λx.x`?"),notation:"Γ, x:τ ⊢ e:τ′  ⇒  Γ ⊢ λx.e : τ→τ′"},
      {id:"explicit",covers:"§15.3",title:b("2단계 — 주석으로 유도 모호성 줄이기","Step 2 — Use annotations to reduce ambiguity"),summary:b("명시적 타입은 추상화·구성자에 타입 정보를 적어 검사와 의미 정의를 단순화한다.","Explicit types annotate abstractions and constructs, simplifying checking and semantic definition."),detail:b("타입 검사와 타입 추론은 다른 문제다. 주석이 충분하면 규칙은 거의 결정적으로 검사가 되지만, 주석이 없으면 미지 타입 사이의 방정식을 풀어야 한다.","Type checking and type inference are different tasks. With enough annotations, rules become nearly deterministic checking; without them, one must solve equations among unknown types."),checkpoint:b("`λx.x`를 검사하려면 x의 타입 주석이 어떤 정보를 주는가?", "What information does a parameter annotation provide when checking `λx.x`?")},
      {id:"semantics",covers:"§15.4–15.6",title:b("3단계 — 타입은 부분집합인가, 구문 자체인가","Step 3 — Are types subsets or syntax categories?"),summary:b("외재적 관점은 비타입 항 중 잘 타입된 항을 고르고, 내재적 관점은 애초에 타입별 항 집합을 만든다.","The extrinsic view selects well-typed terms from untyped syntax; the intrinsic view builds separate typed syntax from the start."),detail:b("외재적 의미는 한 항이 여러 타입 증명을 가질 수 있어 유연하고, 내재적 의미는 잘못 타입된 항을 표현 불가능하게 만든다. 집합론적 의미는 타입을 값 집합, 함수 타입을 적절한 함수 집합으로 해석해 규칙의 건전성을 설명한다.","Extrinsic semantics is flexible because one term may admit different typings; intrinsic semantics makes ill-typed terms unrepresentable. Set-theoretic semantics interprets types as sets of values and function types as suitable function sets, validating the rules."),checkpoint:b("내재적 표현이 타입 오류 상태를 만들 수 없게 하는 장점과 비용은?", "What benefit and cost follow when an intrinsic representation cannot express ill-typed states?")},
      {id:"recursive",covers:"§15.7",title:b("4단계 — 자기 참조 자료 타입","Step 4 — Recursive data types"),summary:b("리스트와 트리는 타입 방정식의 고정점으로 표현되며 fold/unfold가 재귀 구조와 한 층의 모양을 연결한다.","Lists and trees are fixed points of type equations, with fold/unfold connecting a recursive value to one layer of structure."),detail:b("예를 들어 `List τ ≅ 1 + τ × List τ`다. 등재귀적(equi-recursive) 관점은 두 타입을 같게 보고, 동형재귀적(iso-recursive) 관점은 명시적인 포장과 해제를 요구한다.","For example, `List τ ≅ 1 + τ × List τ`. Equi-recursive types identify both sides; iso-recursive types require explicit folding and unfolding."),checkpoint:b("리스트 타입 방정식의 `1`과 합 `+`가 각각 nil과 cons를 어떻게 표현하는가?", "How do `1` and sum `+` in the list equation represent nil and cons?"),notation:"List τ ≅ 1 + (τ × List τ)"},
    ],
    quiz:[
      {question:b("적용 `f a`가 타입을 가지려면?","When is application `f a` typable?"),options:[b("f:τ→τ′이고 a:τ","f:τ→τ′ and a:τ"),b("f와 a의 이름이 같음","f and a have the same name"),b("a가 반드시 정수","a must be an integer")],correct:0,explanation:b("함수의 입력 타입과 인수 타입이 맞아야 결과 타입 τ′를 얻는다.","The function domain must match the argument type, yielding τ′.")},
      {question:b("외재적 타입 관점은?","What is the extrinsic view of typing?"),options:[b("비타입 구문에 타입 성질을 부여","Assign a typing property to untyped syntax"),b("타입마다 별도 구문만 생성","Construct only type-indexed syntax"),b("실행 후 타입 결정","Determine type only after execution")],correct:0,explanation:b("항은 먼저 존재하고 타입 유도가 그 항을 분류한다.","Terms exist first; typing derivations classify them.")},
      {question:b("재귀 타입 `List τ`의 한 층 구조는?","What is one layer of `List τ`?"),options:[b("`1 + τ × List τ`","`1 + τ × List τ`"),b("`τ → τ`만","Only `τ → τ`"),b("`List τ × List τ`만","Only `List τ × List τ`")],correct:0,explanation:b("빈 리스트 또는 머리와 재귀 꼬리의 선택이다.","It is a choice between empty and a head paired with a recursive tail.")},
    ],
    bridge:b("단순 타입은 정확한 모양을 요구한다. 다음 장은 값의 사용 가능성을 보존하면서 더 구체적인 타입을 더 일반적인 타입으로 보는 서브타이핑을 추가한다.","Simple types demand exact shapes. The next chapter adds subtyping, treating more specific values as usable at more general types while preserving behavior."),
  },
];
