import { b, type StudyUnit } from "./types";

export const units01to05: StudyUnit[] = [
  {
    number: "01",
    slug: "predicate-logic",
    part: 1,
    pages: "1–23",
    minutes: 75,
    title: b("술어 논리", "Predicate Logic"),
    eyebrow: b("언어를 설명하는 네 가지 도구", "Four tools for describing languages"),
    overview: b(
      "익숙한 술어 논리를 실험대로 삼아 abstract syntax, denotational semantics, 추론 규칙, 바인딩을 분리해 본다. 이 네 도구는 뒤의 모든 언어 정의에서 반복된다.",
      "Predicate logic is used as a familiar laboratory for separating abstract syntax, denotational semantics, inference rules, and binding. The same four tools recur throughout the book."
    ),
    goals: [
      b("구체 표기와 abstract syntax 트리를 구분한다.", "Distinguish concrete notation from abstract syntax trees."),
      b("상태를 입력으로 받는 의미 함수로 식과 assertion을 해석한다.", "Interpret expressions and assertions as semantic functions of states."),
      b("자유 변수, 캡처 회피 치환, α-이름변경의 관계를 설명한다.", "Explain free variables, capture-avoiding substitution, and alpha-renaming."),
    ],
    keyTerms: [
      b("abstract syntax", "abstract syntax"), b("합성성", "compositionality"),
      b("타당성", "validity"), b("구조적 귀납법", "structural induction"),
      b("캡처 회피 치환", "capture-avoiding substitution"),
    ],
    steps: [
      {
        id: "syntax",
        covers: "§1.1",
        title: b("1단계 — 표기에서 구조를 떼어내기", "Step 1 — Separate notation from structure"),
        summary: b("추상 문법은 괄호·우선순위 같은 표기상의 우연을 버리고 constructor와 부분구조만 남긴다.", "An abstract grammar discards notational accidents such as parentheses and precedence, retaining constructors and substructure."),
        detail: b("표현식은 문자열이 아니라 constructor로 만든 트리다. 따라서 의미 함수와 증명은 문자열 모양이 아닌 트리의 구성 방식에 따라 정의할 수 있다. 이것이 syntax-directed definition과 구조적 귀납법의 기반이다.", "An expression is a tree built by constructors, not a character string. Semantics and proofs can therefore follow the way the tree is built. This supports syntax-directed definitions and structural induction."),
        checkpoint: b("`x + y × z`를 구체 표기와 constructor 트리 두 방식으로 써 보라.", "Write `x + y × z` once as concrete notation and once as a constructor tree."),
        notation: "C₊(Cvar(x), C×(Cvar(y), Cvar(z)))",
      },
      {
        id: "denotation",
        covers: "§1.2",
        title: b("2단계 — 상태에서 의미로", "Step 2 — From states to meanings"),
        summary: b("자유 변수가 있는 식의 의미는 값 하나가 아니라 상태를 값으로 보내는 함수다.", "The meaning of an open expression is not one value but a function from states to values."),
        detail: b("상태 σ가 각 변수에 정수를 배정한다면 정수식은 Σ→ℤ, assertion은 Σ→𝔹로 해석된다. 각 constructor의 의미를 부분식의 의미만으로 정의하면 semantics은 합성적이다.", "If a state σ assigns an integer to every variable, integer expressions denote Σ→ℤ and assertions denote Σ→𝔹. Defining each constructor from only the meanings of its immediate parts makes the semantics compositional."),
        checkpoint: b("σ(x)=2, σ(y)=5일 때 `x+y<10`의 의미를 계산하라.", "Evaluate the denotation of `x+y<10` when σ(x)=2 and σ(y)=5."),
        notation: "⟦e⟧ : Σ → ℤ    ⟦p⟧ : Σ → 𝔹",
      },
      {
        id: "inference",
        covers: "§1.3",
        title: b("3단계 — 진리와 증명을 분리하기", "Step 3 — Separate truth from proof"),
        summary: b("타당성은 모든 상태에서 참이라는 semantic 개념이고, 유도 가능성은 규칙으로 증명할 수 있다는 syntactic 개념이다.", "Validity is semantic truth in every state; derivability is the syntactic existence of a proof from rules."),
        detail: b("건전성은 증명 가능한 것이 모두 타당함을 보장한다. 더 강한 assertion은 더 적은 상태를 허용한다는 역방향 포함 관계도 이후 프로그램 명세 규칙에서 중요해진다.", "Soundness guarantees that every derivable assertion is valid. The reverse-inclusion intuition for stronger assertions becomes important in later program-specification rules."),
        checkpoint: b("`false`가 모든 assertion보다 강하고 `true`가 모든 assertion보다 약한 이유를 상태 집합으로 설명하라.", "Explain with sets of states why `false` is stronger than every assertion and `true` weaker."),
      },
      {
        id: "binding",
        covers: "§1.4",
        title: b("4단계 — 이름 포획을 피하는 치환", "Step 4 — Substitute without capturing names"),
        summary: b("바인더는 범위를 만들며, 단순한 텍스트 치환은 자유 변수를 우연히 묶을 수 있다.", "A binder creates a scope, and naive textual substitution can accidentally bind a free variable."),
        detail: b("치환 전에 충돌하는 바운드 변수를 새 이름으로 바꾸고, 자유 변수에만 동시에 치환한다. 일치 정리, 치환 정리, 이름변경 정리는 syntactic manipulation과 의미가 맞물린다는 핵심 안전장치다.", "Rename conflicting bound variables before simultaneously replacing free occurrences. Coincidence, substitution, and renaming theorems are the key guarantees that syntax manipulation respects meaning."),
        checkpoint: b("`∀y. x<y`에 `y+1`을 x 대신 넣을 때 왜 먼저 y를 바꿔야 하는가?", "Why must `y` be renamed before substituting `y+1` for `x` in `∀y. x<y`?"),
      },
    ],
    quiz: [
      {
        question: b("합성적 semantics의 핵심 조건은?", "What is the defining condition of compositional semantics?"),
        options: [b("의미가 소스 문자열 길이에 의존한다", "Meaning depends on source-string length"), b("구성물의 의미가 직접 부분식의 의미로 결정된다", "A construct's meaning is determined by meanings of its immediate parts"), b("모든 프로그램이 종료한다", "Every program terminates")],
        correct: 1,
        explanation: b("합성성은 표현 방식이 아니라 부분구조의 의미만을 사용한다.", "Compositionality uses the meanings of substructures, not representational details."),
      },
      {
        question: b("캡처 회피 치환이 필요한 직접적인 이유는?", "Why is capture-avoiding substitution necessary?"),
        options: [b("연산 우선순위를 정하려고", "To choose operator precedence"), b("자유 변수가 새 바인더에 묶여 의미가 바뀌는 일을 막으려고", "To prevent a free variable from becoming bound and changing meaning"), b("정수 오버플로를 막으려고", "To prevent integer overflow")],
        correct: 1,
        explanation: b("치환은 자유 변수의 지위를 보존해야 한다.", "Substitution must preserve which occurrences are free."),
      },
      {
        question: b("타당성과 유도 가능성의 올바른 관계는?", "Which correctly relates validity and derivability?"),
        options: [b("둘은 정의상 같다", "They are identical by definition"), b("타당성은 semantic이고 유도 가능성은 syntactic이다", "Validity is semantic; derivability is syntactic"), b("둘 다 상태 하나에서의 실행 결과다", "Both are outcomes in one state")],
        correct: 1,
        explanation: b("건전성·완전성은 서로 다른 두 개념을 연결하는 성질이다.", "Soundness and completeness connect these distinct notions."),
      },
    ],
    bridge: b("이제 의미가 단순한 진릿값이 아니라, 종료하지 않을 수 있는 상태 변환이 되면서 도메인 이론이 필요해진다.", "Next, meanings become possibly nonterminating state transformations, which forces us to introduce domain theory."),
  },
  {
    number: "02",
    slug: "simple-imperative-language",
    part: 1,
    pages: "24–53",
    minutes: 95,
    title: b("단순 명령형 언어", "The Simple Imperative Language"),
    eyebrow: b("상태 변환과 최소 고정점", "State transformations and least fixed points"),
    overview: b("대입, 순차 실행, 조건문, while, 지역 변수로 이루어진 작은 언어를 정의하고 비종료를 포함한 표시적 의미를 만든다.", "A small language of assignment, sequencing, conditionals, while loops, and local variables is given a denotational semantics that includes nontermination."),
    goals: [b("명령을 부분적인 상태 변환으로 해석한다.", "Interpret commands as partial state transformations."), b("while의 의미가 최소 고정점인 이유를 설명한다.", "Explain why a while loop denotes a least fixed point."), b("지역 변수와 별칭이 치환을 어렵게 만드는 방식을 추적한다.", "Trace how local variables and aliasing complicate substitution.")],
    keyTerms: [b("도메인", "domain"), b("연속 함수", "continuous function"), b("최소 고정점", "least fixed point"), b("syntactic sugar", "syntactic sugar"), b("완전 추상성", "full abstraction")],
    steps: [
      {id:"state-transformers",covers:"§2.1–2.2",title:b("1단계 — 명령을 상태 변환으로 읽기","Step 1 — Read commands as state transformers"),summary:b("식은 상태를 관찰하고, 명령은 상태를 바꾼다.","Expressions observe a state; commands transform it."),detail:b("대입은 한 변수만 갱신하고, 순차 실행은 두 변환을 합성하며, 조건문은 불 표현식의 값으로 분기한다. 비종료는 결과 없음으로 나타나므로 명령의 의미에는 바닥값 ⊥가 필요하다.","Assignment updates one variable, sequencing composes transformations, and conditionals branch on a Boolean expression. Nontermination is represented by the absence of a final state, introducing the bottom value ⊥."),checkpoint:b("`x:=x+1; y:=x`의 의미를 두 상태 변환의 합성으로 써 보라.","Express `x:=x+1; y:=x` as a composition of two state transformations."),notation:"⟦c⟧comm : Σ → Σ⊥"},
      {id:"domains",covers:"§2.3–2.4",title:b("2단계 — 근사와 최소 고정점","Step 2 — Approximation and least fixed points"),summary:b("도메인의 순서는 계산 결과의 정보량을 나타내고, 연속 함수는 증가하는 근사의 극한을 보존한다.","A domain order represents information content, and continuous functions preserve limits of increasing approximations."),detail:b("while의 의미 함수 F를 0회, 1회, 2회… 펼친 근사에서 시작한다. ⊥에서 F를 반복해 얻는 사슬의 최소 상한이 `fix F`이며, 이것이 불필요한 추가 동작을 넣지 않는 가장 작은 해다.","Approximate a while loop by allowing zero, one, two, and more unfoldings. Iterating F from ⊥ yields a chain whose least upper bound is `fix F`, the least solution that adds no unjustified behavior."),checkpoint:b("무한 루프의 모든 유한 근사가 왜 최종 상태를 주지 않는지 설명하라.","Explain why every finite approximation of an infinite loop yields no final state."),notation:"fix(F) = ⨆ₙ Fⁿ(⊥)"},
      {id:"binding",covers:"§2.5",title:b("3단계 — 선언, 범위, 별칭","Step 3 — Declarations, scope, and aliasing"),summary:b("지역 변수 선언은 이름을 묶고, 매개 이름을 같은 저장 위치에 대응시키면 별칭이 생긴다.","A local declaration binds a name; aliasing occurs when different names designate the same storage."),detail:b("semantics은 선언 전 값을 저장하고 범위가 끝날 때 복원하는 효과를 모델링한다. syntactic substitution은 바인더 이름을 피해야 할 뿐 아니라, 서로 다른 변수를 하나로 합치는 치환이 대입 효과를 바꿀 수 있음을 고려해야 한다.","The semantics models saving the old value and restoring it after the scope. Syntactic substitution must avoid binders and must account for substitutions that merge distinct variables, changing assignment effects."),checkpoint:b("입력과 출력 매개변수가 같은 변수로 치환될 때 팩토리얼 프로그램이 깨질 수 있는 이유는?", "Why can a factorial program fail when its input and output parameters are substituted by the same variable?")},
      {id:"extensions",covers:"§2.6–2.8",title:b("4단계 — 확장과 관찰 가능성","Step 4 — Extensions and observability"),summary:b("for 같은 구성은 핵심 언어로 번역할 수 있고, 산술 오류를 넣으면 관찰 가능한 결과 공간이 달라진다.","Constructs such as `for` can be translated into the core language, while arithmetic errors enlarge the space of observable results."),detail:b("syntactic sugar의 정의는 새 의미 규칙 없이 번역으로 정당화된다. 건전성은 의미적으로 같은 핵심 번역을 보장하고, 완전 추상성은 문맥이 구별하는 프로그램과 semantics이 구별하는 프로그램이 정확히 일치하는지 묻는다.","Syntactic sugar is justified by translation rather than new semantic machinery. Soundness validates the translation; full abstraction asks whether contextual and semantic distinctions coincide exactly."),checkpoint:b("어떤 두 프로그램의 의미 함수가 다르지만 어떤 언어 문맥도 차이를 관찰하지 못한다면 완전 추상성에 어떤 문제가 생기는가?", "If denotations differ but no program context can observe the difference, what goes wrong with full abstraction?")},
    ],
    quiz: [
      {question:b("while 의미의 최소 고정점을 택하는 이유는?","Why choose the least fixed point for a while loop?"),options:[b("가장 빠른 구현이어서","Because it is the fastest implementation"),b("유한 전개가 정당화하는 동작만 포함하기 위해","To include only behavior justified by finite unfoldings"),b("모든 루프를 종료시키기 위해","To make every loop terminate")],correct:1,explanation:b("최소성은 방정식만 만족하는 임의의 추가 동작을 배제한다.","Leastness excludes arbitrary extra behavior that merely satisfies the equation.")},
      {question:b("명령 의미에 ⊥가 나타내는 것은?","What does ⊥ represent in command semantics?"),options:[b("syntax error","A syntax error"),b("비종료 또는 아직 없는 정보","Nontermination or absent information"),b("빈 상태","An empty state")],correct:1,explanation:b("종료 상태를 생산하지 못하는 계산을 표현한다.","It represents a computation that produces no final state.")},
      {question:b("syntactic sugar의 가장 좋은 설명은?","What best describes syntactic sugar?"),options:[b("핵심 언어로 의미 보존 번역되는 convenience syntax","Convenient syntax translated meaning-preservingly into a core language"),b("파서가 무시하는 주석","A comment ignored by the parser"),b("새로운 하드웨어 명령","A new hardware instruction")],correct:0,explanation:b("convenience syntax은 표현력을 반드시 늘리지 않는다.","Convenience syntax need not increase expressive power.")},
    ],
    bridge:b("상태 변환의 의미를 얻었으니, 다음에는 그 변환이 원하는 사양을 만족함을 syntactic 규칙으로 증명한다.","With state-transformer meanings in hand, we next prove syntactically that those transformations meet specifications."),
  },
  {
    number:"03",slug:"program-specifications",part:1,pages:"54–80",minutes:100,
    title:b("프로그램 명세와 증명","Program Specifications and Their Proofs"),
    eyebrow:b("부분 정확성, 전체 정확성, 불변식","Partial correctness, total correctness, invariants"),
    overview:b("Hoare식 명세를 semantics으로 정의한 뒤, 프로그램 구조를 따라 증명하는 추론 규칙을 세운다. 피보나치와 빠른 거듭제곱이 불변식 설계의 사례가 된다.","Hoare-style specifications are defined semantically and then proved by syntax-directed rules. Fibonacci and fast exponentiation serve as case studies in invariant design."),
    goals:[b("부분 정확성과 전체 정확성을 구분한다.","Distinguish partial from total correctness."),b("대입·순차·조건·while 규칙을 역방향으로 사용한다.","Use assignment, sequencing, conditional, and while rules backward."),b("사후조건에서 루프 불변식과 변량을 설계한다.","Design loop invariants and variants from a postcondition.")],
    keyTerms:[b("Hoare 삼중항","Hoare triple"),b("루프 불변식","loop invariant"),b("변량 함수","variant function"),b("결과 규칙","rule of consequence"),b("건전성","soundness")],
    steps:[
      {id:"specifications",covers:"§3.1",title:b("1단계 — 명세가 약속하는 것","Step 1 — What a specification promises"),summary:b("부분 정확성은 종료했을 때의 결과를, 전체 정확성은 종료와 결과를 함께 약속한다.","Partial correctness promises the result if execution terminates; total correctness promises termination as well."),detail:b("전제 p를 만족하는 초기 상태에서 실행한 뒤 정상 종료 상태가 q를 만족하면 `{p} c {q}`가 성립한다. 전체 정확성 표기는 여기에 모든 p-상태에서 종료한다는 조건을 더한다.","`{p} c {q}` holds when every normally terminating run from a p-state ends in a q-state. Total correctness adds termination from every p-state."),checkpoint:b("무한 루프가 `{true} c {false}`를 부분 정확성으로 만족할 수 있는 이유는?", "Why can an infinite loop satisfy `{true} c {false}` as a partial-correctness claim?")},
      {id:"core-rules",covers:"§3.2–3.3",title:b("2단계 — 프로그램을 따라 증명하기","Step 2 — Let program structure drive the proof"),summary:b("각 syntax constructor에는 그 동작을 반영하는 증명 규칙이 대응한다.","Each syntax constructor has a proof rule reflecting its behavior."),detail:b("대입 규칙은 사후조건 q에서 v를 e로 치환해 필요한 사전조건을 계산한다. 순차 규칙은 중간 assertion을 찾는 문제이며, 결과 규칙은 사전조건을 강화하거나 사후조건을 약화한다.","The assignment rule computes a precondition by substituting e for v in q. Sequencing asks for an intermediate assertion; consequence strengthens a precondition or weakens a postcondition."),checkpoint:b("`{?} x:=x+1 {x>0}`의 가장 직접적인 사전조건을 계산하라.","Compute the direct precondition for `{?} x:=x+1 {x>0}`."),notation:"{ q[v ↦ e] } v := e { q }"},
      {id:"loops",covers:"§3.4–3.5",title:b("3단계 — 불변식과 종료 증명","Step 3 — Invariants and termination"),summary:b("불변식은 반복마다 보존되는 사실이고, 변량은 종료까지 엄격히 감소하는 자연수 척도다.","An invariant is preserved by each iteration; a variant is a natural-number measure that strictly decreases toward termination."),detail:b("부분 정확성은 I∧b에서 본문이 I를 보존함을 보인다. 전체 정확성은 여기에 음수가 되지 않는 변량 t가 반복마다 감소함을 보태 무한 반복을 배제한다.","Partial correctness proves that the body preserves I under I∧b. Total correctness also proves that a nonnegative variant t decreases each time, excluding infinite iteration."),checkpoint:b("배열 길이 n을 향해 k를 증가시키는 루프에서 자연스러운 변량은 무엇인가?", "What is a natural variant for a loop that increments k toward array length n?"),notation:"I ∧ b ⟹ body preserves I;  t ≥ 0 and t decreases"},
      {id:"examples",covers:"§3.6–3.8",title:b("4단계 — 알고리즘에서 불변식 뽑기","Step 4 — Extract invariants from algorithms"),summary:b("피보나치와 빠른 거듭제곱은 중간 변수들이 최종 수학 관계를 어떻게 분해해 유지하는지 보여 준다.","Fibonacci and fast exponentiation show how intermediate variables preserve a decomposition of the final mathematical relationship."),detail:b("좋은 불변식은 사후조건의 일부를 반복 중에도 참이 되도록 일반화한다. 증명 규칙의 한계는 어떤 유용한 규칙이 비합성적이거나, assertion language가 필요한 성질을 표현하지 못할 수 있다는 점이다.","A good invariant generalizes part of the postcondition so that it remains true during iteration. Limitations include noncompositional rules and assertion languages too weak to express needed properties."),checkpoint:b("빠른 거듭제곱에서 `acc × base^exp = 원래 값` 형태가 왜 좋은 불변식인가?", "Why is an equation like `acc × base^exp = original value` a useful invariant for fast exponentiation?")},
    ],
    quiz:[
      {question:b("부분 정확성에 종료가 포함되는가?","Does partial correctness include termination?"),options:[b("항상 포함된다","Always"),b("포함되지 않는다","No"),b("while이 없을 때만 포함된다","Only without while")],correct:1,explanation:b("부분 정확성은 종료한 실행의 결과만 제한한다.","Partial correctness constrains results only for terminating executions.")},
      {question:b("대입 규칙에서 사전조건을 얻는 연산은?","What operation produces the assignment precondition?"),options:[b("사후조건에 대입될 식을 치환","Substitute the assigned expression into the postcondition"),b("불변식을 삭제","Delete the invariant"),b("상태를 무작위 선택","Choose a random state")],correct:0,explanation:b("실행 뒤 q가 참이려면 실행 전에는 q[v↦e]가 참이어야 한다.","For q to hold after assignment, q[v↦e] must hold before it.")},
      {question:b("전체 정확성 while 증명에 추가로 필요한 것은?","What extra ingredient is needed for total correctness of while?"),options:[b("더 강한 파서","A stronger parser"),b("감소하는 하한 있는 변량","A decreasing, lower-bounded variant"),b("동적 바인딩","Dynamic binding")],correct:1,explanation:b("변량이 무한히 감소할 수 없으므로 종료를 얻는다.","A well-founded decreasing variant cannot decrease forever.")},
    ],
    bridge:b("스칼라 변수에서 익힌 명세와 증명 규칙을 다음 장에서 유한 함수로 모델링되는 배열까지 확장한다.","The next chapter extends these specification and proof techniques from scalar variables to arrays modeled as finite functions."),
  },
  {
    number:"04",slug:"arrays",part:1,pages:"81–96",minutes:70,
    title:b("배열","Arrays"),eyebrow:b("업데이트되는 함수와 higher-order assertion","Updatable functions and higher-order assertions"),
    overview:b("정수 첨자의 1차원 배열을 상태 속 함수로 모델링하고, 범위 검사·원소 갱신·이진 탐색·배열 불변식을 다룬다.","One-dimensional integer-indexed arrays are modeled as functions in the state, covering bounds, element update, binary search, and array invariants."),
    goals:[b("배열 읽기와 쓰기의 의미를 함수 적용과 함수 갱신으로 설명한다.","Explain array reads and writes as function application and functional update."),b("범위 오류가 명령 의미에 미치는 영향을 추적한다.","Trace how bounds errors affect command meanings."),b("구간 전체를 말하는 배열 불변식을 작성한다.","Write array invariants that quantify over ranges.")],
    keyTerms:[b("함수 갱신","functional update"),b("정의역","domain"),b("범위 오류","bounds error"),b("이진 탐색","binary search"),b("higher-order assertion","higher-order assertion")],
    steps:[
      {id:"model",covers:"§4.1–4.2",title:b("1단계 — 배열을 유한 함수로 모델링","Step 1 — Model an array as a finite function"),summary:b("배열 값은 첨자 집합에서 정수로 가는 함수이며, 배열 변수는 상태가 그런 함수를 배정하는 이름이다.","An array value is a function from an index set to integers, and a state maps an array variable to such a function."),detail:b("`X(i)`는 현재 함수 X를 i에 적용한다. `X(i):=a`는 i에서만 a를 반환하고 다른 첨자에서는 옛 X와 같은 새 함수를 만든다. i가 정의역 밖이면 오류 결과로 간다.","`X(i)` applies the current function X to i. `X(i):=a` creates a new function returning a at i and the old X elsewhere. If i is outside the domain, evaluation produces an error result."),checkpoint:b("X=[4↦10,5↦20]에서 X(5):=7 뒤의 함수를 써 보라.","Write the resulting function after X(5):=7 when X=[4↦10,5↦20]."),notation:"X[i ↦ a](j) = a if j=i, otherwise X(j)"},
      {id:"search",covers:"§4.3",title:b("2단계 — 이진 탐색을 명세에서 이해","Step 2 — Understand binary search from its specification"),summary:b("탐색 구간 불변식은 목표 값이 있을 수 있는 위치를 계속 좁힌다.","A search-interval invariant continually narrows the positions where the target may occur."),detail:b("정렬 조건과 경계 관계를 사전조건으로 두고, 매 반복에서 중간 원소 비교로 한쪽 구간을 제거한다. 불변식은 제거한 구간에는 답이 없음을 기록하고 변량은 남은 구간 길이다.","Start from sortedness and boundary conditions. Each comparison removes half the interval; the invariant records that eliminated positions cannot contain the answer, and the variant is the remaining interval length."),checkpoint:b("`lo≤target-index<hi`를 직접 모를 때 어떤 논리적 불변식으로 후보 구간을 표현할 수 있는가?", "How can a logical invariant describe the candidate interval when the target index is not known directly?")},
      {id:"rules",covers:"§4.4",title:b("3단계 — 배열 대입 규칙","Step 3 — Proof rules for array assignment"),summary:b("스칼라 치환과 달리 배열 갱신은 모든 배열 읽기에 대한 조건부 효과를 반영해야 한다.","Unlike scalar substitution, an array update has a conditional effect on every array read."),detail:b("사후조건의 X를 변형된 함수 X[i↦a]로 바꾸는 관점이 안전하다. 첨자 식 자체가 X를 읽을 수 있으므로 평가 순서와 오류 조건도 선행조건에 포함해야 한다.","A safe view replaces X in the postcondition by the updated function X[i↦a]. Because the index expression may itself read X, evaluation order and error conditions must also enter the precondition."),checkpoint:b("왜 `X(i):=a`를 단순히 사후조건의 `X(i)`만 a로 바꾸어 처리하면 안 되는가?", "Why is it unsound to handle `X(i):=a` by replacing only occurrences of `X(i)` in the postcondition?")},
      {id:"higher-order",covers:"§4.5",title:b("4단계 — 배열 전체를 양화하기","Step 4 — Quantify over whole arrays"),summary:b("정렬, 순열 보존 같은 성질은 정수 변수만의 1차 assertion보다 함수 자체를 양화하는 higher-order assertion이 자연스럽다.","Properties such as sortedness and permutation preservation naturally require higher-order assertions quantifying over functions."),detail:b("배열의 옛 값을 함수 변수 X₀로 보존하면 최종 배열이 같은 원소를 갖는지, 특정 구간만 바뀌었는지 표현할 수 있다. 표현력이 커지는 만큼 추론과 자동화는 어려워진다.","Binding the old array to a function variable X₀ lets us state that the final array has the same elements or differs only on a region. The greater expressiveness makes inference and automation harder."),checkpoint:b("정렬 알고리즘의 사후조건에 정렬성 외에 반드시 넣어야 할 보존 성질은?", "Besides sortedness, what preservation property belongs in a sorting postcondition?")},
    ],
    quiz:[
      {question:b("배열 원소 갱신의 표시적 모델은?","What is the denotational model of an array-element update?"),options:[b("원래 함수를 삭제","Delete the old function"),b("한 점에서만 다른 새 함수","A new function differing at one index"),b("첨자를 문자열로 변환","Convert the index to a string")],correct:1,explanation:b("불변 데이터 관점의 함수 갱신으로 상태 변화를 표현한다.","State change is represented by functional update in an immutable mathematical model.")},
      {question:b("이진 탐색 종료 증명에 적합한 변량은?","Which is a suitable variant for binary search?"),options:[b("배열 원소 합","Sum of array elements"),b("남은 후보 구간 길이","Length of the remaining candidate interval"),b("목표 값 자체","The target value")],correct:1,explanation:b("각 반복에서 후보 구간이 엄격히 줄어든다.","The candidate interval strictly shrinks each iteration.")},
      {question:b("higher-order assertion이 특히 필요한 성질은?","Which property especially motivates higher-order assertions?"),options:[b("한 변수의 현재 값","The current value of one variable"),b("배열 전체의 순열 보존","Permutation preservation of an entire array"),b("키워드 철자","Keyword spelling")],correct:1,explanation:b("배열을 함수 값으로 비교하거나 양화해야 하기 때문이다.","It requires quantifying over or comparing arrays as function values.")},
    ],
    bridge:b("배열 오류는 정상 종료 외의 결과를 드러낸다. 다음 장은 실패, 입출력, 비종료를 하나의 의미 구조에 담기 위해 연속성과 계속을 확장한다.","Array errors expose outcomes beyond normal termination. The next chapter unifies failure, I/O, and nontermination using richer domains and continuations."),
  },
  {
    number:"05",slug:"failure-io-continuations",part:1,pages:"97–125",minutes:105,
    title:b("실패, 입출력, 계속","Failure, Input-Output, and Continuations"),eyebrow:b("결과에서 상호작용 과정으로","From final results to interaction processes"),
    overview:b("실패와 중간 입출력을 추가하면 최종 상태 하나만으로는 동작을 설명할 수 없다. 시퀀스·재개·재귀 도메인·continuation semantics으로 관찰 가능한 실행 과정을 모델링한다.","Failure and intermediate I/O cannot be described by one final state. Sequences, resumptions, recursive domains, and continuation semantics model the observable course of execution."),
    goals:[b("정상 종료, 실패, 비종료를 구분하는 결과 도메인을 읽는다.","Read result domains that distinguish normal termination, failure, and divergence."),b("유한 관찰과 연속성의 물리적 논증을 설명한다.","Explain the physical argument from finite observation to continuity."),b("direct semantics과 continuation semantics의 정보 흐름을 비교한다.","Compare information flow in direct and continuation semantics.")],
    keyTerms:[b("시퀀스 도메인","sequence domain"),b("재귀 도메인 동형","recursive domain isomorphism"),b("재개","resumption"),b("계속","continuation"),b("CPS","continuation-passing style")],
    steps:[
      {id:"failure",covers:"§5.1",title:b("1단계 — 실패를 결과로 만들기","Step 1 — Make failure an explicit result"),summary:b("`fail`은 정상 상태와 다른 관찰 가능한 종료이며 비종료와도 구별될 수 있다.","`fail` is an observable termination distinct from both a normal state and divergence."),detail:b("결과 공간에 `(abort,σ)`를 추가하면 실패 순간의 상태를 보존할 수 있다. 순차 구성은 앞 명령이 정상 종료할 때만 뒤 명령을 실행하고, 실패나 비종료는 그대로 전파한다.","Adding `(abort,σ)` to the result space preserves the state at failure. Sequencing runs its second command only after normal termination; failure and divergence propagate."),checkpoint:b("실패를 비종료와 같은 ⊥로 합치면 catch 같은 구성을 설명할 때 어떤 정보를 잃는가?", "What information is lost if failure is collapsed into the same ⊥ as divergence when explaining catch-like constructs?")},
      {id:"output-continuity",covers:"§5.2–5.5",title:b("2단계 — 유한 관찰에서 연속성으로","Step 2 — From finite observations to continuity"),summary:b("출력은 유한 또는 무한 시퀀스로 누적되고, 유한 시간의 관찰은 유한한 계산 근사에만 의존해야 한다.","Output accumulates as finite or infinite sequences, and any finite-time observation must depend on only a finite computation approximation."),detail:b("접두사 순서는 출력 정보의 증가를 나타낸다. 제품과 분리합으로 복합 결과를 만들고, 재귀 도메인 방정식으로 무한 행동을 유한 단계 구조의 극한으로 정의한다. 연속성은 무한 정보를 갑자기 검사하는 비현실적 함수를 배제한다.","Prefix order represents growing output information. Products and disjoint unions assemble results, while recursive domain equations describe infinite behavior as limits of finite structure. Continuity rules out unrealistic functions that inspect infinite information at once."),checkpoint:b("출력 스트림의 어떤 유한 접두사를 결정하는 데 전체 무한 입력이 필요하다면 왜 비연속적인가?", "Why is a process discontinuous if deciding a finite output prefix requires the entire infinite input?")},
      {id:"resumptions",covers:"§5.6",title:b("3단계 — 입력을 기다리는 계산","Step 3 — Computations that wait for input"),summary:b("입력 명령은 한 값이 아니라 가능한 각 입력 뒤의 나머지 계산을 가진 재개 노드다.","An input command is a resumption node containing the rest of the computation for every possible input."),detail:b("재개 도메인은 종료, 실패, 출력 후 계속, 입력별 계속 같은 constructor를 재귀적으로 묶는다. 프로그램 의미는 최종 결과가 아니라 환경과 주고받는 잠재적으로 무한한 트리다.","A resumption domain recursively combines termination, failure, output-and-continue, and input-indexed continuation constructors. A program denotes a potentially infinite interaction tree rather than a single final result."),checkpoint:b("출력은 하나의 다음 재개를 갖지만 입력은 함수 형태의 여러 다음 재개를 갖는 이유는?", "Why does output have one next resumption while input has a function of possible next resumptions?")},
      {id:"continuations",covers:"§5.7–5.8",title:b("4단계 — 나머지 계산을 매개변수로","Step 4 — Pass the rest of the computation explicitly"),summary:b("계속은 현재 명령 뒤에 무엇을 할지 나타내는 함수이며, 각 syntax의 의미가 그 계속을 받아 전체 결과를 만든다.","A continuation represents what happens after the current command; each construct receives it and produces the overall result."),detail:b("순차 구성에서 `c₀;c₁`은 c₁의 의미를 현재 계속과 결합한 뒤 c₀에 넘긴다. 실패는 정상 계속을 무시하고 실패 경로로 빠지므로 예외·탈출·제어 효과를 direct semantics보다 자연스럽게 표현한다.","For `c₀;c₁`, combine c₁ with the current continuation and pass that to c₀. Failure ignores the normal continuation and follows an abort path, making exceptions, exits, and control effects more natural than in direct style."),checkpoint:b("CPS에서 순차 구성의 계산 순서가 계속의 중첩 순서로 어떻게 나타나는가?", "How does nesting continuations encode the order of sequential composition in CPS?"),notation:"⟦c₀;c₁⟧ k = ⟦c₀⟧ (⟦c₁⟧ k)"},
    ],
    quiz:[
      {question:b("resumption semantics이 final-state semantics보다 필요한 경우는?","When is resumption semantics needed beyond final-state semantics?"),options:[b("중간 입출력을 관찰할 때","When intermediate I/O is observable"),b("변수 이름을 짧게 할 때","When shortening variable names"),b("문법에 괄호가 있을 때","When syntax has parentheses")],correct:0,explanation:b("상호작용 과정 자체가 관찰되므로 최종 상태만으로 부족하다.","The interaction process itself is observable, so a final state is insufficient.")},
      {question:b("접두사 순서가 표현하는 것은?","What does prefix order represent?"),options:[b("더 긴 시퀀스가 더 많은 관찰 정보를 가짐","A longer sequence carries more observed information"),b("정수의 대소 관계","Integer magnitude"),b("소스 파일 순서","Source-file order")],correct:0,explanation:b("유한 출력은 무한 출력의 근사다.","Finite outputs approximate an infinite output.")},
      {question:b("계속의 직관은?","What is the intuition for a continuation?"),options:[b("현재까지의 로그","A log of the past"),b("현재 계산 뒤에 할 일","What to do after the current computation"),b("변수의 타입","A variable's type")],correct:1,explanation:b("계속은 미래의 계산 문맥을 함수 값으로 표현한다.","A continuation represents the future computation context as a function.")},
    ],
    bridge:b("도메인 방정식으로 계산 과정을 기술했으니, 다음에는 한 번의 실행 단계를 추론 규칙으로 직접 정의하는 transition semantics으로 관점을 바꾼다.","Having described processes denotationally, we next switch to transition semantics, defining one execution step directly by inference rules."),
  },
];
