import { b, type StudyUnit } from "./types";

export const units16toAppendix: StudyUnit[] = [
  {
    number:"16",slug:"subtypes-intersection-types",part:4,pages:"349–378",minutes:110,
    title:b("서브타입과 교차 타입","Subtypes and Intersection Types"),eyebrow:b("대체 가능성, 오버로딩, 의미의 일관성","Substitutability, overloading, and coherence"),
    overview:b("서브타이핑 추론 규칙을 곱·합·함수 타입에 확장하고 교차 타입, 외재적 의미, 일반 연산자, 내재적 의미를 비교한다.","Subtyping rules are extended across products, sums, and functions, then related to intersection types, extrinsic semantics, generic operators, and intrinsic semantics."),
    goals:[b("함수 타입의 반공변·공변 규칙을 적용한다.","Apply contravariance and covariance for function types."),b("교차 타입을 여러 사용 능력의 결합으로 읽는다.","Read intersection types as combined capabilities."),b("암시적 coercion의 coherence 문제를 설명한다.","Explain coherence for implicit coercions.")],
    keyTerms:[b("서브타이핑","subtyping"),b("대체 가능성","substitutability"),b("공변성","covariance"),b("반공변성","contravariance"),b("교차 타입","intersection type"),b("일관성","coherence")],
    steps:[
      {id:"rules",covers:"§16.1",title:b("1단계 — 더 구체적인 값을 안전하게 사용","Step 1 — Safely use more specific values"),summary:b("`S <: T`는 S 값을 T가 기대되는 모든 곳에서 안전하게 쓸 수 있다는 판단이다.","`S <: T` says every S value may safely be used wherever T is expected."),detail:b("반사성과 추이성 위에 구조 규칙을 둔다. 함수 `S₁→S₂ <: T₁→T₂`에는 입력이 반공변 `T₁<:S₁`, 출력이 공변 `S₂<:T₂`이어야 호출 안전성이 보존된다.","Structural rules extend reflexivity and transitivity. For functions, `S₁→S₂ <: T₁→T₂` requires contravariant inputs `T₁<:S₁` and covariant outputs `S₂<:T₂` to preserve call safety."),checkpoint:b("Animal→Dog 함수가 Dog→Animal이 기대되는 곳에 안전한지 규칙으로 판단하라.", "Use the variance rule to decide whether Animal→Dog is safe where Dog→Animal is expected."),notation:"T₁ <: S₁  and  S₂ <: T₂  ⇒  S₁→S₂ <: T₁→T₂"},
      {id:"products-sums",covers:"§16.2",title:b("2단계 — 이름 있는 곱과 합","Step 2 — Named products and sums"),summary:b("레코드의 추가 필드와 variant의 선택지 관계는 서로 다른 방향의 대체 가능성을 만든다.","Extra record fields and variant alternatives induce different directions of substitutability."),detail:b("더 많은 필드를 가진 레코드는 필요한 필드를 모두 제공하므로 폭 서브타입이 된다. 반대로 더 적은 대안을 가진 variant는 더 많은 대안을 처리하는 문맥에서 안전하다.","A record with more fields is a width subtype because it provides every required field. Conversely, a variant with fewer alternatives is safe in a context prepared to handle more alternatives."),checkpoint:b("레코드 폭 서브타이핑과 variant 폭 서브타이핑의 방향이 반대인 이유는?", "Why do width subtyping directions differ for records and variants?")},
      {id:"intersection",covers:"§16.3",title:b("3단계 — 한 값의 여러 타입 능력","Step 3 — Multiple capabilities of one value"),summary:b("`S ∩ T`는 같은 값이 S와 T의 요구를 모두 만족함을 나타낸다.","`S ∩ T` means the same value satisfies both S and T."),detail:b("교차 타입은 오버로드 함수, 정밀한 흐름 정보, 동일 항의 여러 사용법을 표현한다. 단순한 곱 `S×T`와 달리 두 별도 값을 담는 것이 아니라 하나의 값에 두 판단이 겹친다.","Intersection types express overloaded functions, precise flow information, and multiple uses of one term. Unlike product `S×T`, they do not pair two values; two typings overlap on one value."),checkpoint:b("`(Int→Int) ∩ (Bool→Bool)`과 두 함수의 쌍의 차이를 설명하라.", "Explain the difference between `(Int→Int) ∩ (Bool→Bool)` and a pair of two functions.")},
      {id:"semantics",covers:"§16.4–16.6",title:b("4단계 — coercion 경로가 의미를 바꾸지 않게","Step 4 — Keep coercion paths semantically coherent"),summary:b("서브타입 증명을 실행 가능한 coercion으로 해석하면 같은 판단의 여러 증명 경로가 같은 동작을 해야 한다.","If subtype proofs elaborate to executable coercions, different proof paths for one judgment must behave the same."),detail:b("외재적 의미는 비타입 값의 부분집합 관계로 단순화할 수 있지만 일반 연산자와 내재적 의미에서는 삽입되는 coercion이 드러난다. coherence는 타입 유도 선택이 런타임 관찰을 바꾸지 않음을 요구한다.","Extrinsic semantics can use subset relationships among untyped values, but generic operators and intrinsic semantics expose inserted coercions. Coherence requires that choosing a typing derivation not change runtime observations."),checkpoint:b("한 서브타입 판단에 서로 다른 coercion 경로가 있고 결과가 다르면 왜 타입 체계가 비결정적으로 보이는가?", "Why does a type system appear nondeterministic if two coercion paths for one subtype judgment produce different results?")},
    ],
    quiz:[
      {question:b("함수 입력 타입의 분산은?","What is the variance of function input types?"),options:[b("공변","Covariant"),b("반공변","Contravariant"),b("항상 무관","Always irrelevant")],correct:1,explanation:b("더 일반적인 입력을 받을 수 있는 함수가 더 안전하게 대체된다.","A function accepting more general inputs is the safer substitute.")},
      {question:b("교차 타입과 곱 타입의 핵심 차이는?","What is the key difference between intersection and product types?"),options:[b("교차는 한 값의 두 능력, 곱은 두 값을 쌍으로 묶음","Intersection gives one value two capabilities; product pairs two values"),b("둘은 완전히 같다","They are identical"),b("교차는 런타임 오류만 표현","Intersection expresses only runtime errors")],correct:0,explanation:b("교차는 동일 항에 대한 복수 판단이다.","Intersection is multiple typing information about the same term.")},
      {question:b("coherence가 보장하는 것은?","What does coherence guarantee?"),options:[b("모든 프로그램이 같은 타입","All programs have one type"),b("타입 유도 경로 선택이 관찰 의미를 바꾸지 않음","Choice of typing derivation does not change observable meaning"),b("모든 함수가 종료","All functions terminate")],correct:1,explanation:b("암시적 coercion의 경로 독립성을 요구한다.","It requires path independence of implicit coercions.")},
    ],
    bridge:b("한 항에 여러 타입 능력을 주는 생각은 타입 자체를 매개변수화하는 전칭 다형성으로 이어진다.","Giving one term reusable typing capabilities leads naturally to universal polymorphism, where types themselves become parameters."),
  },
  {
    number:"17",slug:"polymorphism",part:4,pages:"379–397",minutes:90,
    title:b("다형성","Polymorphism"),eyebrow:b("타입을 추상화하고 모든 타입에서 재사용하기","Abstract over types and reuse at every type"),
    overview:b("System F식 전칭 타입, 타입 추상화·적용, 다형적 프로그래밍 인코딩과 외재적 의미를 다룬다.","System-F-style universal types, type abstraction and application, polymorphic encodings, and extrinsic semantics are developed."),
    goals:[b("타입 추상화와 타입 적용을 유도한다.","Derive type abstraction and type application."),b("전칭 타입이 단순한 여러 단형 타입 목록보다 강한 이유를 설명한다.","Explain why a universal type is stronger than a list of monomorphic typings."),b("다형적 데이터 인코딩의 생산자·소비자 구조를 읽는다.","Read producer-consumer structure in polymorphic data encodings.")],
    keyTerms:[b("전칭 다형성","universal polymorphism"),b("타입 추상화","type abstraction"),b("타입 적용","type application"),b("System F","System F"),b("다형적 인코딩","polymorphic encoding")],
    steps:[
      {id:"rules",covers:"§17.1",title:b("1단계 — 타입 변수도 바인딩하기","Step 1 — Bind type variables too"),summary:b("`Λα.e`는 타입 α를 추상화하고 `e [T]`는 다형적 항을 구체 타입 T에서 사용한다.","`Λα.e` abstracts over a type α; `e [T]` instantiates a polymorphic term at concrete type T."),detail:b("`∀α.T` 도입 시 α가 항 문맥의 가정에 자유롭게 의존하지 않아야 한다. 제거는 T 안의 α를 원하는 타입으로 치환한다. 항 수준 바인딩과 마찬가지로 타입 변수도 캡처 회피가 필요하다.","Introducing `∀α.T` requires α not to depend freely on term-context assumptions. Elimination substitutes a chosen type for α. Type variables need capture avoidance just like term variables."),checkpoint:b("다형적 항등함수 `Λα. λx:α.x`의 타입과 Int에서의 인스턴스를 써 보라.", "Give the type of `Λα. λx:α.x` and its instantiation at Int."),notation:"Λα. λx:α. x : ∀α. α→α"},
      {id:"uniformity",covers:"§17.1",title:b("2단계 — 모든 타입에서 같은 코드","Step 2 — The same code at every type"),summary:b("전칭 타입은 각 타입마다 별도 구현이 있다는 뜻이 아니라 하나의 항이 임의 타입에서 잘 동작한다는 뜻이다.","A universal type does not mean separate implementations per type; one term works at arbitrary types."),detail:b("타입 추상화 안에서는 α 값의 내부 구조를 알 수 없으므로 가능한 동작이 제한된다. 이 균일성은 이후 parametricity로 정교해지지만 책에서는 규칙과 의미 수준에서 기반을 마련한다.","Inside a type abstraction, code cannot inspect the unknown structure of α, restricting possible behavior. This uniformity anticipates parametricity, though the book develops the foundation through rules and semantics."),checkpoint:b("종료하는 순수 함수가 `∀α. α→α`라면 왜 사실상 항등함수여야 하는지 직관을 말하라.", "Give the intuition why a terminating pure function of type `∀α. α→α` must essentially be identity.")},
      {id:"programming",covers:"§17.2",title:b("3단계 — 함수로 자료 표현하기","Step 3 — Represent data by polymorphic functions"),summary:b("불리언, 자연수, 리스트 같은 자료를 모든 결과 타입의 소비자를 받는 다형 함수로 표현할 수 있다.","Booleans, naturals, and lists can be represented as polymorphic functions accepting consumers at any result type."),detail:b("전칭 타입은 비타입 Church 인코딩에 잘못된 소비를 막는 규율을 더한다. 데이터의 타입은 어떤 제거 연산을 허용하는지 명시하고, fold가 중심 인터페이스가 된다.","Universal types add discipline to untyped Church encodings, ruling out invalid consumers. A data type specifies its allowed eliminations, with fold as the central interface."),checkpoint:b("다형적 리스트 인코딩에서 nil과 cons가 fold 소비자에게 각각 무엇을 전달하는가?", "In a polymorphic list encoding, what do nil and cons contribute to a fold consumer?")},
      {id:"semantics",covers:"§17.3",title:b("4단계 — 다형성의 외재적 의미","Step 4 — Give polymorphism extrinsic meaning"),summary:b("다형 타입은 모든 타입 해석에 걸쳐 같은 비타입 항이 조건을 만족하는 교집합 성질로 읽힌다.","A polymorphic type is read extrinsically as a property one untyped term satisfies across all type interpretations."),detail:b("단순 집합 의미만으로 impredicative 전칭을 다루면 크기·자기참조 문제가 생긴다. 의미 모델은 타입 해석의 범위와 항 동치 관계를 조심스럽게 제한해야 한다.","Naive set semantics for impredicative universals encounters size and self-reference problems. A semantic model must carefully control the universe of type interpretations and term equivalence."),checkpoint:b("`∀α.T`가 특정 α 하나의 해석만 확인해서는 안 되는 이유는?", "Why can `∀α.T` not be validated by checking just one interpretation of α?")},
    ],
    quiz:[
      {question:b("전칭 타입 제거는 무엇을 하는가?","What does universal-type elimination do?"),options:[b("타입 변수를 구체 타입으로 인스턴스화","Instantiate a type variable with a concrete type"),b("항 변수를 삭제","Delete a term variable"),b("저장소를 초기화","Initialize the store")],correct:0,explanation:b("다형적 값을 특정 타입에서 사용한다.","It uses a polymorphic value at a chosen type.")},
      {question:b("`∀α. α→α`의 핵심 제약은?","What is the key constraint of `∀α. α→α`?"),options:[b("α의 내부를 타입별로 검사 가능","The code may inspect α differently for each type"),b("임의 α에서 균일하게 동작","The code must work uniformly for arbitrary α"),b("α는 항상 정수","α is always Int")],correct:1,explanation:b("타입 추상화는 α의 구조를 알 수 없게 한다.","Type abstraction hides α's structure.")},
      {question:b("다형적 Church 인코딩이 제공하는 것은?","What do polymorphic Church encodings provide?"),options:[b("소비 방식으로 표현된 타입 안전한 자료","Type-safe data represented by its consumers"),b("공유 변수 잠금","Shared-variable locking"),b("무조건 상수 시간 실행","Guaranteed constant time")],correct:0,explanation:b("전칭 타입이 허용되는 fold/선택 연산을 규율한다.","Universal types discipline the permitted folds or choices.")},
    ],
    bridge:b("타입을 숨기면서 연산만 공개하면 추상 자료형과 모듈이 된다. 다음 장은 실존 타입으로 이 경계를 명세한다.","Hiding a representation type while exposing operations gives abstract data types and modules, specified next with existential types."),
  },
  {
    number:"18",slug:"module-specification",part:4,pages:"398–414",minutes:85,
    title:b("모듈 명세","Module Specification"),eyebrow:b("표현을 숨기고 인터페이스만 약속하기","Hide representation, promise an interface"),
    overview:b("타입 정의와 실존 양화를 사용해 모듈이 내부 표현 타입을 숨기면서 연산 계약을 공개하는 방식을 형식화한다.","Type definitions and existential quantification formalize modules that hide an internal representation type while exposing an operational contract."),
    goals:[b("투명·불투명 타입 정의를 구분한다.","Distinguish transparent and opaque type definitions."),b("실존 패키지의 pack/unpack 규칙을 사용한다.","Use pack and unpack rules for existential packages."),b("한 추상을 다른 추상으로 구현하는 표현 함수를 추적한다.","Trace representation functions when implementing one abstraction with another.")],
    keyTerms:[b("추상 타입","abstract type"),b("실존 타입","existential type"),b("패키징","packing"),b("개봉","unpacking"),b("표현 독립성","representation independence")],
    steps:[
      {id:"definitions",covers:"§18.1",title:b("1단계 — 타입 이름에 경계 세우기","Step 1 — Put a boundary around a type name"),summary:b("타입 정의는 표현 타입에 이름을 주며, 불투명 정의는 클라이언트가 그 등식을 사용하지 못하게 한다.","A type definition names a representation type; an opaque definition prevents clients from using that equality."),detail:b("구현 내부에서는 새 타입과 표현 타입의 변환을 알 수 있지만 인터페이스 밖에서는 제공된 연산만 사용할 수 있다. 이 정보 은닉이 표현 교체 가능성의 기반이다.","Inside the implementation, conversions to the representation are known; outside, only exported operations are available. This information hiding enables representation replacement."),checkpoint:b("추상 stack 타입이 list와 같다는 사실을 공개하면 클라이언트가 어떤 불변식을 깨뜨릴 수 있는가?", "What invariant could clients break if an abstract stack type were revealed to equal list?")},
      {id:"existentials",covers:"§18.2",title:b("2단계 — '어떤 표현이 존재한다'로 모듈 쓰기","Step 2 — Describe a module as 'some representation exists'"),summary:b("`∃α.T` 패키지는 숨겨진 표현 타입 α와 그 타입에서 T를 만족하는 구현을 함께 담는다.","A package of type `∃α.T` contains a hidden representation α and an implementation satisfying T at that type."),detail:b("pack은 구체 표현 타입과 구현을 봉인한다. unpack은 α를 신선한 추상 타입으로 열어 T의 연산을 쓰게 하지만, α나 그 값이 범위 밖으로 표현을 누설하면 안 된다.","Pack seals a concrete representation and implementation. Unpack opens α as a fresh abstract type for using operations in T, but α and its values must not escape in a way that leaks the representation."),checkpoint:b("unpack의 α 신선성 조건이 필요한 이유는?", "Why is freshness of α required in existential unpacking?"),notation:"pack [R, m] as ∃α.T    /    unpack [α, x] = p in e"},
      {id:"abstraction",covers:"§18.2",title:b("3단계 — 표현 독립성의 관찰 기준","Step 3 — Observable criterion for representation independence"),summary:b("서로 다른 표현을 가진 두 패키지가 인터페이스의 모든 클라이언트에서 같은 관찰을 내면 같은 모듈로 취급할 수 있다.","Two packages with different representations are equivalent when every interface-respecting client observes the same behavior."),detail:b("클라이언트는 α 값을 직접 분해하지 못하므로 공개 연산이 보존하는 관계만 관찰한다. 추상화 정리는 구현 사이의 관계가 각 연산에서 보존되면 클라이언트 동치가 따름을 보여 주는 방향으로 읽을 수 있다.","Because clients cannot inspect α directly, they observe only relations preserved by exported operations. An abstraction theorem shows that a representation relation preserved by each operation yields client equivalence."),checkpoint:b("리스트 기반 stack과 배열 기반 stack 사이에 어떤 관계를 세우면 같은 인터페이스 구현임을 보일 수 있는가?", "What relation could connect list- and array-based stacks to prove interface equivalence?")},
      {id:"implementation",covers:"§18.3",title:b("4단계 — 한 추상화를 다른 추상화로 구현","Step 4 — Implement one abstraction using another"),summary:b("기존 추상 타입의 연산만 사용해 새 모듈을 만들면 내부 표현 관계를 합성해 정확성을 증명할 수 있다.","Building a module only from operations of an existing abstraction lets representation relations compose into a correctness proof."),detail:b("구현은 단순 타입 일치 이상으로 연산 법칙을 보존해야 한다. 모듈 명세는 숨겨진 표현과 공개 관찰 사이의 증명 경계를 명확히 한다.","An implementation must preserve operational laws, not merely match types. Module specifications clarify the proof boundary between hidden representation and public observations."),checkpoint:b("큐를 두 스택으로 구현할 때 타입 일치 외에 보존해야 할 핵심 추상 관계는?", "When implementing a queue with two stacks, what key abstraction relation must be preserved beyond type matching?")},
    ],
    quiz:[
      {question:b("실존 타입이 모듈에서 숨기는 것은?","What does an existential type hide in a module?"),options:[b("표현 타입","The representation type"),b("모든 연산 이름","All operation names"),b("프로그램 종료 여부","Whether the program terminates")],correct:0,explanation:b("클라이언트는 표현을 모르고 공개 연산만 사용한다.","Clients know only exported operations, not the representation.")},
      {question:b("pack의 역할은?","What does pack do?"),options:[b("구체 표현과 구현을 실존 인터페이스로 봉인","Seal a representation and implementation behind an existential interface"),b("모든 타입을 같게 만듦","Make all types equal"),b("동적 바인딩 활성화","Enable dynamic binding")],correct:0,explanation:b("구현 세부를 숨기는 도입 연산이다.","It is the introduction form that hides implementation details.")},
      {question:b("표현 독립성이 허용하는 것은?","What does representation independence permit?"),options:[b("관찰 동작을 보존하며 내부 표현 교체","Replace an internal representation while preserving observations"),b("인터페이스 삭제","Delete the interface"),b("모든 클라이언트 수정","Modify every client")],correct:0,explanation:b("추상 경계를 지키는 클라이언트는 차이를 보지 못한다.","Clients respecting the abstraction boundary cannot tell the difference.")},
    ],
    bridge:b("추상 타입과 함수형 모듈의 아이디어를 마지막 장에서는 명령·식·위치·프로시저가 공존하는 Algol식 블록 구조에 적용한다.","The final chapter applies abstraction and typing ideas to Algol-like block structure, where commands, expressions, locations, and procedures coexist."),
  },
  {
    number:"19",slug:"algol-like-languages",part:4,pages:"415–446",minutes:120,
    title:b("Algol 계열 언어","Algol-like Languages"),eyebrow:b("블록 구조와 스택 규율의 의미론","Semantics of block structure and stack discipline"),
    overview:b("데이터 타입과 구절 타입을 구분해 명령형·함수형 구성을 통합하고, 배열·선언자·변수·프로시저의 스택 기반 의미를 정교화한다.","Data types and phrase types unify imperative and functional constructs, followed by arrays, declarators, variables, procedures, and a semantics that embodies stack discipline."),
    goals:[b("값 타입과 구절 타입을 구분한다.","Distinguish data types from phrase types."),b("expression·acceptor·variable·command의 관계를 설명한다.","Explain relationships among expression, acceptor, variable, and command phrase types."),b("스택 규율이 가능한 탈출과 저장 수명을 제한하는 방식을 설명한다.","Explain how stack discipline limits escape and storage lifetime.")],
    keyTerms:[b("구절 타입","phrase type"),b("acceptor","acceptor"),b("variable","variable"),b("선언자","declarator"),b("스택 규율","stack discipline"),b("Algol","Algol")],
    steps:[
      {id:"phrase-types",covers:"§19.1–19.2",title:b("1단계 — 값과 계산 능력의 타입 분리","Step 1 — Separate value types from computational capabilities"),summary:b("데이터 타입은 저장되는 값의 종류를, 구절 타입은 식·대입 대상·명령·프로시저 같은 사용 방식을 분류한다.","Data types classify stored values; phrase types classify modes of use such as expressions, acceptors, commands, and procedures."),detail:b("읽기 가능한 expression과 쓰기 가능한 acceptor를 짝지으면 variable이 된다. 타입 규칙은 읽기·쓰기 능력을 분리해 aliasing과 매개변수 전달을 더 정밀하게 표현한다.","Pairing a readable expression with a writable acceptor yields a variable. Typing rules separate read and write capabilities, representing aliasing and parameter passing more precisely."),checkpoint:b("읽기 전용 매개변수와 쓰기 전용 매개변수를 phrase type으로 어떻게 구분할 수 있는가?", "How can phrase types distinguish read-only and write-only parameters?"),notation:"var[τ] ≈ exp[τ] × acc[τ]"},
      {id:"examples",covers:"§19.3–19.4",title:b("2단계 — 구절 타입으로 선언과 배열 읽기","Step 2 — Read declarations and arrays through phrase types"),summary:b("배열·선언자는 값 하나가 아니라 범위 안에서 새 저장과 이름을 만드는 계산 구성이다.","Arrays and declarators are not mere values; they create fresh storage and names within a scope."),detail:b("배열 변수는 첨자에서 variable 구절로 가는 구조로 이해할 수 있다. 선언자는 본문에 신선한 저장 능력을 공급한 뒤 범위가 끝나면 회수하므로 단순 함수 값과 다르다.","An array variable can be viewed as mapping indices to variable phrases. A declarator supplies fresh storage capabilities to its body and reclaims them on scope exit, unlike an ordinary value."),checkpoint:b("배열을 `index → var[τ]`로 보는 것이 읽기와 쓰기를 함께 설명하는 이유는?", "Why does viewing an array as `index → var[τ]` explain both reading and writing?")},
      {id:"stack",covers:"§19.5",title:b("3단계 — 의미론에 스택 수명 넣기","Step 3 — Build stack lifetime into semantics"),summary:b("지역 저장이 범위 밖으로 탈출하지 못하게 하면 할당과 해제가 후입선출 규율을 따른다.","Preventing local storage from escaping its scope enforces last-in-first-out allocation and deallocation."),detail:b("일반 저장소 의미는 지역 위치가 클로저나 참조로 살아남는 heap 동작도 허용한다. Algol식 의미는 타입·범주 또는 가능 세계 구조로 범위 밖 참조를 막아 스택 구현을 정당화한다.","A general store semantics allows local locations to survive through closures or references, behaving like a heap. Algol-like semantics uses types, categories, or world structure to prevent out-of-scope references, justifying stack implementation."),checkpoint:b("지역 변수 주소를 반환할 수 있다면 스택 규율이 깨지는 이유는?", "Why does returning a local variable's address break stack discipline?")},
      {id:"variables-procedures",covers:"§19.6–19.8",title:b("4단계 — 변수와 프로시저의 이중성","Step 4 — The duality of variables and procedures"),summary:b("변수는 읽기·쓰기 동작의 쌍이고, 프로시저는 구절을 받아 명령을 만드는 고차 구절이다.","A variable pairs read and write actions; a procedure is a higher-order phrase accepting phrases and producing commands."),detail:b("call-by-name류 매개변수는 값이 아니라 계산 능력을 전달해 Jensen's device 같은 패턴을 가능하게 한다. 확장 규칙은 복사 규칙, 범위, 평가 시점이 결합될 때 생기는 미묘함을 드러낸다.","Call-by-name-like parameters pass computational capabilities rather than values, enabling patterns such as Jensen's device. Extensions expose subtle interactions among copying rules, scope, and evaluation time."),checkpoint:b("값 매개변수와 이름 매개변수가 부작용 있는 실제 인수를 몇 번 평가하는지 비교하라.", "Compare how often value and name parameters evaluate an effectful actual argument.")},
    ],
    quiz:[
      {question:b("phrase type이 분류하는 것은?","What do phrase types classify?"),options:[b("값의 비트 폭만","Only bit widths of values"),b("표현식·대입 대상·명령 같은 계산 사용 방식","Computational modes such as expressions, acceptors, and commands"),b("파일 확장자","File extensions")],correct:1,explanation:b("데이터 종류와 그 데이터를 사용하는 능력을 분리한다.","They separate data kinds from capabilities for using data.")},
      {question:b("Algol식 스택 규율의 핵심 제한은?","What is the key restriction behind Algol-like stack discipline?"),options:[b("지역 저장 위치가 범위 밖으로 탈출하지 않음","Local storage locations do not escape their scope"),b("재귀를 금지","Recursion is forbidden"),b("모든 변수가 전역","All variables are global")],correct:0,explanation:b("그래야 블록 종료 시 저장을 안전하게 회수할 수 있다.","Then storage can be safely reclaimed when the block exits.")},
      {question:b("`var[τ]`의 직관은?","What is the intuition for `var[τ]`?"),options:[b("읽기 expression과 쓰기 acceptor의 결합","A readable expression combined with a writable acceptor"),b("정수 상수","An integer constant"),b("타입 변수만","Only a type variable")],correct:0,explanation:b("변수의 두 관찰 가능한 능력을 함께 제공한다.","It combines the two observable capabilities of a variable.")},
    ],
    bridge:b("19개 장의 공통 언어는 집합·관계·함수다. 부록은 책 전체의 표기와 증명에 필요한 수학 기초를 빠르게 복습한다.","Sets, relations, and functions are the common language of all 19 chapters. The appendix provides a compact review of the notation and mathematics used throughout."),
  },
  {
    number:"A",slug:"mathematical-background",part:1,pages:"447–466",minutes:75,
    title:b("수학적 배경","Mathematical Background"),eyebrow:b("집합, 관계, 함수, 곱과 합의 도구상자","A toolbox of sets, relations, functions, products, and sums"),
    overview:b("책의 의미론과 증명에서 쓰는 집합론 표기, 관계, 함수, 곱, 분리합, 폐쇄 연산을 한곳에 정리한다.","The appendix consolidates the set-theoretic notation, relations, functions, products, disjoint unions, and closure operations used in the semantics and proofs."),
    goals:[b("집합 연산과 함수 공간 표기를 정확히 읽는다.","Read set operations and function-space notation accurately."),b("관계의 합성·역·폐쇄를 계산한다.","Compute relational composition, converse, and closure."),b("곱과 분리합을 의미 도메인 구성에 적용한다.","Apply products and disjoint unions to semantic domains.")],
    keyTerms:[b("멱집합","powerset"),b("관계 합성","relational composition"),b("부분 함수","partial function"),b("데카르트 곱","Cartesian product"),b("분리합","disjoint union"),b("반사·추이 폐쇄","reflexive-transitive closure")],
    steps:[
      {id:"sets",covers:"§A.1",title:b("1단계 — 집합 표기 안정시키기","Step 1 — Stabilize set notation"),summary:b("원소, 부분집합, 합집합, 교집합, 차집합, 멱집합을 이후 의미 도메인의 기본 문법으로 사용한다.","Membership, subset, union, intersection, difference, and powerset form the basic notation of later semantic domains."),detail:b("타입이나 구문 범주를 집합으로, 의미를 그 집합 사이의 함수로 읽는다. 포함 순서가 정보 순서로 재사용될 수 있으므로 원소 관계와 부분집합 관계를 혼동하지 않는다.","Types and syntax categories are treated as sets, with meanings as functions between them. Since inclusion can become an information order, do not confuse membership with subset."),checkpoint:b("`x∈P(S)`와 `x⊆S`가 동치인 이유를 설명하라.", "Explain why `x∈P(S)` is equivalent to `x⊆S`.")},
      {id:"relations",covers:"§A.2, A.6",title:b("2단계 — 관계와 실행 경로","Step 2 — Relations and execution paths"),summary:b("이항 관계는 비결정적 한 단계 이동을 표현하고 합성·폐쇄는 여러 단계 실행을 만든다.","A binary relation represents nondeterministic one-step movement; composition and closure build multi-step execution."),detail:b("역관계는 화살표 방향을 바꾸고, 반사·추이 폐쇄 R*는 0회 이상의 R 단계를, 추이 폐쇄 R+는 1회 이상을 나타낸다. 전이 의미론 표기의 수학적 기반이다.","Converse reverses arrows; reflexive-transitive closure R* means zero or more R steps, and transitive closure R+ means one or more. This underlies transition-semantics notation."),checkpoint:b("R*가 항상 항등 관계를 포함하는 이유는?", "Why does R* always include the identity relation?")},
      {id:"functions",covers:"§A.3–A.4",title:b("3단계 — 함수도 특별한 관계로 보기","Step 3 — View functions as special relations"),summary:b("함수는 각 입력에 정확히 하나의 출력을 대응시키는 관계이며 부분 함수는 일부 입력에서만 정의된다.","A function is a relation assigning exactly one output to each input; a partial function is defined only on some inputs."),detail:b("함수 합성의 순서, 제한, 갱신 표기는 상태와 환경 의미론에서 반복된다. 고차 함수 공간은 함수 자체를 원소로 다루며 도메인 이론과 람다 의미의 기반이 된다.","Composition order, restriction, and update recur in state and environment semantics. Higher-order function spaces treat functions as elements, supporting domain theory and lambda semantics."),checkpoint:b("상태 갱신 `σ[x↦v]`가 원래 σ와 어디에서 다른지 정의하라.", "Define exactly where state update `σ[x↦v]` differs from σ.")},
      {id:"products-sums",covers:"§A.5",title:b("4단계 — 함께 있음과 선택을 구분","Step 4 — Distinguish combination from choice"),summary:b("곱 S×T는 S와 T 값을 함께 담고, 분리합 S+T는 어느 쪽 값인지 태그와 함께 담는다.","Product S×T contains both an S and a T; disjoint union S+T contains a tagged value from one side."),detail:b("상태-명령 구성에는 곱이, 정상 결과 또는 실패 같은 대안에는 분리합이 적합하다. 태그가 없으면 두 집합에 같은 원소가 있을 때 어느 경우인지 잃는다.","Products suit command-state configurations; disjoint unions suit alternatives such as normal result or failure. Tags preserve the source side when the component sets overlap."),checkpoint:b("`State + (abort×State)`에서 분리합 태그가 필요한 이유는?", "Why are disjoint-union tags needed in `State + (abort×State)`?")},
    ],
    quiz:[
      {question:b("R*가 의미하는 것은?","What does R* mean?"),options:[b("R의 0회 이상 반복","Zero or more R steps"),b("R의 역만","Only the converse of R"),b("R의 원소 수","The cardinality of R")],correct:0,explanation:b("반사·추이 폐쇄는 길이 0인 경로도 포함한다.","Reflexive-transitive closure includes paths of length zero.")},
      {question:b("곱과 분리합의 차이는?","How do product and disjoint union differ?"),options:[b("곱은 둘 다, 분리합은 태그된 한쪽","Product contains both; disjoint union a tagged one side"),b("둘은 같은 집합","They are identical"),b("곱만 함수를 포함","Only products may contain functions")],correct:0,explanation:b("동시 구성과 대안 선택을 구분하는 기본 생성자다.","They are basic constructors for combination versus alternatives.")},
      {question:b("부분 함수가 전체 함수와 다른 점은?","How does a partial function differ from a total function?"),options:[b("일부 입력에서 결과가 정의되지 않을 수 있음","It may be undefined on some inputs"),b("출력이 두 개씩 있음","It has two outputs per input"),b("합성할 수 없음","It cannot be composed")],correct:0,explanation:b("비종료나 오류를 부분성으로 모델링할 수 있다.","Partiality can model nontermination or errors.")},
    ],
    bridge:b("이 부록은 필요할 때 되돌아오는 참조 페이지다. 준비가 되면 1장부터 네 가지 언어 설명 도구를 다시 연결해 보라.","Treat this appendix as a page to revisit on demand. When ready, return to Chapter 1 and reconnect the four tools for describing languages."),
  },
];
